enum MACRO_SYS {SYS_io_setup = 0,SYS_io_destroy = 1,SYS_io_submit = 2,SYS_io_cancel = 3,SYS_io_getevents = 4,SYS_setxattr = 5,SYS_lsetxattr = 6,SYS_fsetxattr = 7,SYS_getxattr = 8,SYS_lgetxattr = 9,SYS_fgetxattr = 10,SYS_listxattr = 11,SYS_llistxattr = 12,SYS_flistxattr = 13,SYS_removexattr = 14,SYS_lremovexattr = 15,SYS_fremovexattr = 16,SYS_getcwd = 17,SYS_lookup_dcookie = 18,SYS_eventfd2 = 19,SYS_epoll_create1 = 20,SYS_epoll_ctl = 21,SYS_epoll_pwait = 22,SYS_dup = 23,SYS_dup3 = 24,SYS_fcntl = 25,SYS_inotify_init1 = 26,SYS_inotify_add_watch = 27,SYS_inotify_rm_watch = 28,SYS_ioctl = 29,SYS_ioprio_set = 30,SYS_ioprio_get = 31,SYS_flock = 32,SYS_mknodat = 33,SYS_mkdirat = 34,SYS_unlinkat = 35,SYS_symlinkat = 36,SYS_linkat = 37,SYS_renameat = 38,SYS_umount2 = 39,SYS_mount = 40,SYS_pivot_root = 41,SYS_nfsservctl = 42,SYS_statfs = 43,SYS_fstatfs = 44,SYS_truncate = 45,SYS_ftruncate = 46,SYS_fallocate = 47,SYS_faccessat = 48,SYS_chdir = 49,SYS_fchdir = 50,SYS_chroot = 51,SYS_fchmod = 52,SYS_fchmodat = 53,SYS_fchownat = 54,SYS_fchown = 55,SYS_openat = 56,SYS_close = 57,SYS_vhangup = 58,SYS_pipe2 = 59,SYS_quotactl = 60,SYS_getdents64 = 61,SYS_lseek = 62,SYS_read = 63,SYS_write = 64,SYS_readv = 65,SYS_writev = 66,SYS_pread64 = 67,SYS_pwrite64 = 68,SYS_preadv = 69,SYS_pwritev = 70,SYS_sendfile = 71,SYS_pselect6 = 72,SYS_ppoll = 73,SYS_signalfd4 = 74,SYS_vmsplice = 75,SYS_splice = 76,SYS_tee = 77,SYS_readlinkat = 78,SYS_fstatat = 79,SYS_fstat = 80,SYS_sync = 81,SYS_fsync = 82,SYS_fdatasync = 83,SYS_sync_file_range = 84,SYS_timerfd_create = 85,SYS_timerfd_settime = 86,SYS_timerfd_gettime = 87,SYS_utimensat = 88,SYS_acct = 89,SYS_capget = 90,SYS_capset = 91,SYS_personality = 92,SYS_exit = 93,SYS_exit_group = 94,SYS_waitid = 95,SYS_set_tid_address = 96,SYS_unshare = 97,SYS_futex = 98,SYS_set_robust_list = 99,SYS_get_robust_list = 100,SYS_nanosleep = 101,SYS_getitimer = 102,SYS_setitimer = 103,SYS_kexec_load = 104,SYS_init_module = 105,SYS_delete_module = 106,SYS_timer_create = 107,SYS_timer_gettime = 108,SYS_timer_getoverrun = 109,SYS_timer_settime = 110,SYS_timer_delete = 111,SYS_clock_settime = 112,SYS_clock_gettime = 113,SYS_clock_getres = 114,SYS_clock_nanosleep = 115,SYS_syslog = 116,SYS_ptrace = 117,SYS_sched_setparam = 118,SYS_sched_setscheduler = 119,SYS_sched_getscheduler = 120,SYS_sched_getparam = 121,SYS_sched_setaffinity = 122,SYS_sched_getaffinity = 123,SYS_sched_yield = 124,SYS_sched_get_priority_max = 125,SYS_sched_get_priority_min = 126,SYS_sched_rr_get_interval = 127,SYS_restart_syscall = 128,SYS_kill = 129,SYS_tkill = 130,SYS_tgkill = 131,SYS_sigaltstack = 132,SYS_rt_sigsuspend = 133,SYS_rt_sigaction = 134,SYS_rt_sigprocmask = 135,SYS_rt_sigpending = 136,SYS_rt_sigtimedwait = 137,SYS_rt_sigqueueinfo = 138,SYS_rt_sigreturn = 139,SYS_setpriority = 140,SYS_getpriority = 141,SYS_reboot = 142,SYS_setregid = 143,SYS_setgid = 144,SYS_setreuid = 145,SYS_setuid = 146,SYS_setresuid = 147,SYS_getresuid = 148,SYS_setresgid = 149,SYS_getresgid = 150,SYS_setfsuid = 151,SYS_setfsgid = 152,SYS_times = 153,SYS_setpgid = 154,SYS_getpgid = 155,SYS_getsid = 156,SYS_setsid = 157,SYS_getgroups = 158,SYS_setgroups = 159,SYS_uname = 160,SYS_sethostname = 161,SYS_setdomainname = 162,SYS_getrlimit = 163,SYS_setrlimit = 164,SYS_getrusage = 165,SYS_umask = 166,SYS_prctl = 167,SYS_getcpu = 168,SYS_gettimeofday = 169,SYS_settimeofday = 170,SYS_adjtimex = 171,SYS_getpid = 172,SYS_getppid = 173,SYS_getuid = 174,SYS_geteuid = 175,SYS_getgid = 176,SYS_getegid = 177,SYS_gettid = 178,SYS_sysinfo = 179,SYS_mq_open = 180,SYS_mq_unlink = 181,SYS_mq_timedsend = 182,SYS_mq_timedreceive = 183,SYS_mq_notify = 184,SYS_mq_getsetattr = 185,SYS_msgget = 186,SYS_msgctl = 187,SYS_msgrcv = 188,SYS_msgsnd = 189,SYS_semget = 190,SYS_semctl = 191,SYS_semtimedop = 192,SYS_semop = 193,SYS_shmget = 194,SYS_shmctl = 195,SYS_shmat = 196,SYS_shmdt = 197,SYS_socket = 198,SYS_socketpair = 199,SYS_bind = 200,SYS_listen = 201,SYS_accept = 202,SYS_connect = 203,SYS_getsockname = 204,SYS_getpeername = 205,SYS_sendto = 206,SYS_recvfrom = 207,SYS_setsockopt = 208,SYS_getsockopt = 209,SYS_shutdown = 210,SYS_sendmsg = 211,SYS_recvmsg = 212,SYS_readahead = 213,SYS_brk = 214,SYS_munmap = 215,SYS_mremap = 216,SYS_add_key = 217,SYS_request_key = 218,SYS_keyctl = 219,SYS_clone = 220,SYS_execve = 221,SYS_mmap = 222,SYS_fadvise64 = 223,SYS_swapon = 224,SYS_swapoff = 225,SYS_mprotect = 226,SYS_msync = 227,SYS_mlock = 228,SYS_munlock = 229,SYS_mlockall = 230,SYS_munlockall = 231,SYS_mincore = 232,SYS_madvise = 233,SYS_remap_file_pages = 234,SYS_mbind = 235,SYS_get_mempolicy = 236,SYS_set_mempolicy = 237,SYS_migrate_pages = 238,SYS_move_pages = 239,SYS_rt_tgsigqueueinfo = 240,SYS_perf_event_open = 241,SYS_accept4 = 242,SYS_recvmmsg = 243,SYS_or1k_atomic = 244,SYS_wait4 = 260,SYS_prlimit64 = 261,SYS_fanotify_init = 262,SYS_fanotify_mark = 263,SYS_name_to_handle_at = 264,SYS_open_by_handle_at = 265,SYS_clock_adjtime = 266,SYS_syncfs = 267,SYS_setns = 268,SYS_sendmmsg = 269,SYS_process_vm_readv = 270,SYS_process_vm_writev = 271,SYS_kcmp = 272,SYS_finit_module = 273,SYS_sched_setattr = 274,SYS_sched_getattr = 275,SYS_renameat2 = 276,SYS_seccomp = 277,SYS_getrandom = 278,SYS_memfd_create = 279,SYS_bpf = 280,SYS_execveat = 281,SYS_userfaultfd = 282,SYS_membarrier = 283,SYS_mlock2 = 284,SYS_copy_file_range = 285,SYS_preadv2 = 286,SYS_pwritev2 = 287,};
enum MACRO___NR {__NR_io_setup = 0,__NR_io_destroy = 1,__NR_io_submit = 2,__NR_io_cancel = 3,__NR_io_getevents = 4,__NR_setxattr = 5,__NR_lsetxattr = 6,__NR_fsetxattr = 7,__NR_getxattr = 8,__NR_lgetxattr = 9,__NR_fgetxattr = 10,__NR_listxattr = 11,__NR_llistxattr = 12,__NR_flistxattr = 13,__NR_removexattr = 14,__NR_lremovexattr = 15,__NR_fremovexattr = 16,__NR_getcwd = 17,__NR_lookup_dcookie = 18,__NR_eventfd2 = 19,__NR_epoll_create1 = 20,__NR_epoll_ctl = 21,__NR_epoll_pwait = 22,__NR_dup = 23,__NR_dup3 = 24,__NR_fcntl = 25,__NR_inotify_init1 = 26,__NR_inotify_add_watch = 27,__NR_inotify_rm_watch = 28,__NR_ioctl = 29,__NR_ioprio_set = 30,__NR_ioprio_get = 31,__NR_flock = 32,__NR_mknodat = 33,__NR_mkdirat = 34,__NR_unlinkat = 35,__NR_symlinkat = 36,__NR_linkat = 37,__NR_renameat = 38,__NR_umount2 = 39,__NR_mount = 40,__NR_pivot_root = 41,__NR_nfsservctl = 42,__NR_statfs = 43,__NR_fstatfs = 44,__NR_truncate = 45,__NR_ftruncate = 46,__NR_fallocate = 47,__NR_faccessat = 48,__NR_chdir = 49,__NR_fchdir = 50,__NR_chroot = 51,__NR_fchmod = 52,__NR_fchmodat = 53,__NR_fchownat = 54,__NR_fchown = 55,__NR_openat = 56,__NR_close = 57,__NR_vhangup = 58,__NR_pipe2 = 59,__NR_quotactl = 60,__NR_getdents64 = 61,__NR_lseek = 62,__NR_read = 63,__NR_write = 64,__NR_readv = 65,__NR_writev = 66,__NR_pread64 = 67,__NR_pwrite64 = 68,__NR_preadv = 69,__NR_pwritev = 70,__NR_sendfile = 71,__NR_pselect6 = 72,__NR_ppoll = 73,__NR_signalfd4 = 74,__NR_vmsplice = 75,__NR_splice = 76,__NR_tee = 77,__NR_readlinkat = 78,__NR_fstatat = 79,__NR_fstat = 80,__NR_sync = 81,__NR_fsync = 82,__NR_fdatasync = 83,__NR_sync_file_range = 84,__NR_timerfd_create = 85,__NR_timerfd_settime = 86,__NR_timerfd_gettime = 87,__NR_utimensat = 88,__NR_acct = 89,__NR_capget = 90,__NR_capset = 91,__NR_personality = 92,__NR_exit = 93,__NR_exit_group = 94,__NR_waitid = 95,__NR_set_tid_address = 96,__NR_unshare = 97,__NR_futex = 98,__NR_set_robust_list = 99,__NR_get_robust_list = 100,__NR_nanosleep = 101,__NR_getitimer = 102,__NR_setitimer = 103,__NR_kexec_load = 104,__NR_init_module = 105,__NR_delete_module = 106,__NR_timer_create = 107,__NR_timer_gettime = 108,__NR_timer_getoverrun = 109,__NR_timer_settime = 110,__NR_timer_delete = 111,__NR_clock_settime = 112,__NR_clock_gettime = 113,__NR_clock_getres = 114,__NR_clock_nanosleep = 115,__NR_syslog = 116,__NR_ptrace = 117,__NR_sched_setparam = 118,__NR_sched_setscheduler = 119,__NR_sched_getscheduler = 120,__NR_sched_getparam = 121,__NR_sched_setaffinity = 122,__NR_sched_getaffinity = 123,__NR_sched_yield = 124,__NR_sched_get_priority_max = 125,__NR_sched_get_priority_min = 126,__NR_sched_rr_get_interval = 127,__NR_restart_syscall = 128,__NR_kill = 129,__NR_tkill = 130,__NR_tgkill = 131,__NR_sigaltstack = 132,__NR_rt_sigsuspend = 133,__NR_rt_sigaction = 134,__NR_rt_sigprocmask = 135,__NR_rt_sigpending = 136,__NR_rt_sigtimedwait = 137,__NR_rt_sigqueueinfo = 138,__NR_rt_sigreturn = 139,__NR_setpriority = 140,__NR_getpriority = 141,__NR_reboot = 142,__NR_setregid = 143,__NR_setgid = 144,__NR_setreuid = 145,__NR_setuid = 146,__NR_setresuid = 147,__NR_getresuid = 148,__NR_setresgid = 149,__NR_getresgid = 150,__NR_setfsuid = 151,__NR_setfsgid = 152,__NR_times = 153,__NR_setpgid = 154,__NR_getpgid = 155,__NR_getsid = 156,__NR_setsid = 157,__NR_getgroups = 158,__NR_setgroups = 159,__NR_uname = 160,__NR_sethostname = 161,__NR_setdomainname = 162,__NR_getrlimit = 163,__NR_setrlimit = 164,__NR_getrusage = 165,__NR_umask = 166,__NR_prctl = 167,__NR_getcpu = 168,__NR_gettimeofday = 169,__NR_settimeofday = 170,__NR_adjtimex = 171,__NR_getpid = 172,__NR_getppid = 173,__NR_getuid = 174,__NR_geteuid = 175,__NR_getgid = 176,__NR_getegid = 177,__NR_gettid = 178,__NR_sysinfo = 179,__NR_mq_open = 180,__NR_mq_unlink = 181,__NR_mq_timedsend = 182,__NR_mq_timedreceive = 183,__NR_mq_notify = 184,__NR_mq_getsetattr = 185,__NR_msgget = 186,__NR_msgctl = 187,__NR_msgrcv = 188,__NR_msgsnd = 189,__NR_semget = 190,__NR_semctl = 191,__NR_semtimedop = 192,__NR_semop = 193,__NR_shmget = 194,__NR_shmctl = 195,__NR_shmat = 196,__NR_shmdt = 197,__NR_socket = 198,__NR_socketpair = 199,__NR_bind = 200,__NR_listen = 201,__NR_accept = 202,__NR_connect = 203,__NR_getsockname = 204,__NR_getpeername = 205,__NR_sendto = 206,__NR_recvfrom = 207,__NR_setsockopt = 208,__NR_getsockopt = 209,__NR_shutdown = 210,__NR_sendmsg = 211,__NR_recvmsg = 212,__NR_readahead = 213,__NR_brk = 214,__NR_munmap = 215,__NR_mremap = 216,__NR_add_key = 217,__NR_request_key = 218,__NR_keyctl = 219,__NR_clone = 220,__NR_execve = 221,__NR_mmap = 222,__NR_fadvise64 = 223,__NR_swapon = 224,__NR_swapoff = 225,__NR_mprotect = 226,__NR_msync = 227,__NR_mlock = 228,__NR_munlock = 229,__NR_mlockall = 230,__NR_munlockall = 231,__NR_mincore = 232,__NR_madvise = 233,__NR_remap_file_pages = 234,__NR_mbind = 235,__NR_get_mempolicy = 236,__NR_set_mempolicy = 237,__NR_migrate_pages = 238,__NR_move_pages = 239,__NR_rt_tgsigqueueinfo = 240,__NR_perf_event_open = 241,__NR_accept4 = 242,__NR_recvmmsg = 243,__NR_or1k_atomic = 244,__NR_wait4 = 260,__NR_prlimit64 = 261,__NR_fanotify_init = 262,__NR_fanotify_mark = 263,__NR_name_to_handle_at = 264,__NR_open_by_handle_at = 265,__NR_clock_adjtime = 266,__NR_syncfs = 267,__NR_setns = 268,__NR_sendmmsg = 269,__NR_process_vm_readv = 270,__NR_process_vm_writev = 271,__NR_kcmp = 272,__NR_finit_module = 273,__NR_sched_setattr = 274,__NR_sched_getattr = 275,__NR_renameat2 = 276,__NR_seccomp = 277,__NR_getrandom = 278,__NR_memfd_create = 279,__NR_bpf = 280,__NR_execveat = 281,__NR_userfaultfd = 282,__NR_membarrier = 283,__NR_mlock2 = 284,__NR_copy_file_range = 285,__NR_preadv2 = 286,__NR_pwritev2 = 287,};
struct __old_kernel_stat;
union bpf_attr;
struct compat_stat;
struct compat_timeval;
struct getcpu_cache;
struct iattr;
struct inode;
typedef int32_t key_serial_t;
struct linux_dirent;
struct linux_dirent64;
struct list_head;
struct mmap_arg_struct;
typedef __kernel_mqd_t mqd_t;
struct nfsctl_arg;
struct old_linux_dirent;
typedef unsigned __int64 old_sigset_t;
struct perf_event_attr;
typedef __kernel_uid32_t qid_t;
struct sched_attr;
struct sel_arg_struct;
struct semaphore;
typedef unsigned int u32;
typedef unsigned __int64 u64;
typedef unsigned __int16 umode_t;
struct user_msghdr;

MACRO_SYS SYS_accept;
MACRO_SYS SYS_accept4;
MACRO_SYS SYS_acct;
MACRO_SYS SYS_add_key;
MACRO_SYS SYS_adjtimex;
MACRO_SYS SYS_bind;
MACRO_SYS SYS_bpf;
MACRO_SYS SYS_brk;
MACRO_SYS SYS_capget;
MACRO_SYS SYS_capset;
MACRO_SYS SYS_chdir;
MACRO_SYS SYS_chroot;
MACRO_SYS SYS_clock_adjtime;
MACRO_SYS SYS_clock_getres;
MACRO_SYS SYS_clock_gettime;
MACRO_SYS SYS_clock_nanosleep;
MACRO_SYS SYS_clock_settime;
MACRO_SYS SYS_clone;
MACRO_SYS SYS_close;
MACRO_SYS SYS_connect;
MACRO_SYS SYS_copy_file_range;
MACRO_SYS SYS_delete_module;
MACRO_SYS SYS_dup;
MACRO_SYS SYS_dup3;
MACRO_SYS SYS_epoll_create1;
MACRO_SYS SYS_epoll_ctl;
MACRO_SYS SYS_epoll_pwait;
MACRO_SYS SYS_eventfd2;
MACRO_SYS SYS_execve;
MACRO_SYS SYS_execveat;
MACRO_SYS SYS_exit;
MACRO_SYS SYS_exit_group;
MACRO_SYS SYS_faccessat;
MACRO_SYS SYS_fadvise64;
MACRO_SYS SYS_fallocate;
MACRO_SYS SYS_fanotify_init;
MACRO_SYS SYS_fanotify_mark;
MACRO_SYS SYS_fchdir;
MACRO_SYS SYS_fchmod;
MACRO_SYS SYS_fchmodat;
MACRO_SYS SYS_fchown;
MACRO_SYS SYS_fchownat;
MACRO_SYS SYS_fcntl;
MACRO_SYS SYS_fdatasync;
MACRO_SYS SYS_fgetxattr;
MACRO_SYS SYS_finit_module;
MACRO_SYS SYS_flistxattr;
MACRO_SYS SYS_flock;
MACRO_SYS SYS_fremovexattr;
MACRO_SYS SYS_fsetxattr;
MACRO_SYS SYS_fstat;
MACRO_SYS SYS_fstatat;
MACRO_SYS SYS_fstatfs;
MACRO_SYS SYS_fsync;
MACRO_SYS SYS_ftruncate;
MACRO_SYS SYS_futex;
MACRO_SYS SYS_get_mempolicy;
MACRO_SYS SYS_get_robust_list;
MACRO_SYS SYS_getcpu;
MACRO_SYS SYS_getcwd;
MACRO_SYS SYS_getdents64;
MACRO_SYS SYS_getegid;
MACRO_SYS SYS_geteuid;
MACRO_SYS SYS_getgid;
MACRO_SYS SYS_getgroups;
MACRO_SYS SYS_getitimer;
MACRO_SYS SYS_getpeername;
MACRO_SYS SYS_getpgid;
MACRO_SYS SYS_getpid;
MACRO_SYS SYS_getppid;
MACRO_SYS SYS_getpriority;
MACRO_SYS SYS_getrandom;
MACRO_SYS SYS_getresgid;
MACRO_SYS SYS_getresuid;
MACRO_SYS SYS_getrlimit;
MACRO_SYS SYS_getrusage;
MACRO_SYS SYS_getsid;
MACRO_SYS SYS_getsockname;
MACRO_SYS SYS_getsockopt;
MACRO_SYS SYS_gettid;
MACRO_SYS SYS_gettimeofday;
MACRO_SYS SYS_getuid;
MACRO_SYS SYS_getxattr;
MACRO_SYS SYS_init_module;
MACRO_SYS SYS_inotify_add_watch;
MACRO_SYS SYS_inotify_init1;
MACRO_SYS SYS_inotify_rm_watch;
MACRO_SYS SYS_io_cancel;
MACRO_SYS SYS_io_destroy;
MACRO_SYS SYS_io_getevents;
MACRO_SYS SYS_io_setup;
MACRO_SYS SYS_io_submit;
MACRO_SYS SYS_ioctl;
MACRO_SYS SYS_ioprio_get;
MACRO_SYS SYS_ioprio_set;
MACRO_SYS SYS_kcmp;
MACRO_SYS SYS_kexec_load;
MACRO_SYS SYS_keyctl;
MACRO_SYS SYS_kill;
MACRO_SYS SYS_lgetxattr;
MACRO_SYS SYS_linkat;
MACRO_SYS SYS_listen;
MACRO_SYS SYS_listxattr;
MACRO_SYS SYS_llistxattr;
MACRO_SYS SYS_lookup_dcookie;
MACRO_SYS SYS_lremovexattr;
MACRO_SYS SYS_lseek;
MACRO_SYS SYS_lsetxattr;
MACRO_SYS SYS_madvise;
MACRO_SYS SYS_mbind;
MACRO_SYS SYS_membarrier;
MACRO_SYS SYS_memfd_create;
MACRO_SYS SYS_migrate_pages;
MACRO_SYS SYS_mincore;
MACRO_SYS SYS_mkdirat;
MACRO_SYS SYS_mknodat;
MACRO_SYS SYS_mlock;
MACRO_SYS SYS_mlock2;
MACRO_SYS SYS_mlockall;
MACRO_SYS SYS_mmap;
MACRO_SYS SYS_mount;
MACRO_SYS SYS_move_pages;
MACRO_SYS SYS_mprotect;
MACRO_SYS SYS_mq_getsetattr;
MACRO_SYS SYS_mq_notify;
MACRO_SYS SYS_mq_open;
MACRO_SYS SYS_mq_timedreceive;
MACRO_SYS SYS_mq_timedsend;
MACRO_SYS SYS_mq_unlink;
MACRO_SYS SYS_mremap;
MACRO_SYS SYS_msgctl;
MACRO_SYS SYS_msgget;
MACRO_SYS SYS_msgrcv;
MACRO_SYS SYS_msgsnd;
MACRO_SYS SYS_msync;
MACRO_SYS SYS_munlock;
MACRO_SYS SYS_munlockall;
MACRO_SYS SYS_munmap;
MACRO_SYS SYS_name_to_handle_at;
MACRO_SYS SYS_nanosleep;
MACRO_SYS SYS_nfsservctl;
MACRO_SYS SYS_open_by_handle_at;
MACRO_SYS SYS_openat;
MACRO_SYS SYS_or1k_atomic;
MACRO_SYS SYS_perf_event_open;
MACRO_SYS SYS_personality;
MACRO_SYS SYS_pipe2;
MACRO_SYS SYS_pivot_root;
MACRO_SYS SYS_ppoll;
MACRO_SYS SYS_prctl;
MACRO_SYS SYS_pread64;
MACRO_SYS SYS_preadv;
MACRO_SYS SYS_preadv2;
MACRO_SYS SYS_prlimit64;
MACRO_SYS SYS_process_vm_readv;
MACRO_SYS SYS_process_vm_writev;
MACRO_SYS SYS_pselect6;
MACRO_SYS SYS_ptrace;
MACRO_SYS SYS_pwrite64;
MACRO_SYS SYS_pwritev;
MACRO_SYS SYS_pwritev2;
MACRO_SYS SYS_quotactl;
MACRO_SYS SYS_read;
MACRO_SYS SYS_readahead;
MACRO_SYS SYS_readlinkat;
MACRO_SYS SYS_readv;
MACRO_SYS SYS_reboot;
MACRO_SYS SYS_recvfrom;
MACRO_SYS SYS_recvmmsg;
MACRO_SYS SYS_recvmsg;
MACRO_SYS SYS_remap_file_pages;
MACRO_SYS SYS_removexattr;
MACRO_SYS SYS_renameat;
MACRO_SYS SYS_renameat2;
MACRO_SYS SYS_request_key;
MACRO_SYS SYS_restart_syscall;
MACRO_SYS SYS_rt_sigaction;
MACRO_SYS SYS_rt_sigpending;
MACRO_SYS SYS_rt_sigprocmask;
MACRO_SYS SYS_rt_sigqueueinfo;
MACRO_SYS SYS_rt_sigreturn;
MACRO_SYS SYS_rt_sigsuspend;
MACRO_SYS SYS_rt_sigtimedwait;
MACRO_SYS SYS_rt_tgsigqueueinfo;
MACRO_SYS SYS_sched_get_priority_max;
MACRO_SYS SYS_sched_get_priority_min;
MACRO_SYS SYS_sched_getaffinity;
MACRO_SYS SYS_sched_getattr;
MACRO_SYS SYS_sched_getparam;
MACRO_SYS SYS_sched_getscheduler;
MACRO_SYS SYS_sched_rr_get_interval;
MACRO_SYS SYS_sched_setaffinity;
MACRO_SYS SYS_sched_setattr;
MACRO_SYS SYS_sched_setparam;
MACRO_SYS SYS_sched_setscheduler;
MACRO_SYS SYS_sched_yield;
MACRO_SYS SYS_seccomp;
MACRO_SYS SYS_semctl;
MACRO_SYS SYS_semget;
MACRO_SYS SYS_semop;
MACRO_SYS SYS_semtimedop;
MACRO_SYS SYS_sendfile;
MACRO_SYS SYS_sendmmsg;
MACRO_SYS SYS_sendmsg;
MACRO_SYS SYS_sendto;
MACRO_SYS SYS_set_mempolicy;
MACRO_SYS SYS_set_robust_list;
MACRO_SYS SYS_set_tid_address;
MACRO_SYS SYS_setdomainname;
MACRO_SYS SYS_setfsgid;
MACRO_SYS SYS_setfsuid;
MACRO_SYS SYS_setgid;
MACRO_SYS SYS_setgroups;
MACRO_SYS SYS_sethostname;
MACRO_SYS SYS_setitimer;
MACRO_SYS SYS_setns;
MACRO_SYS SYS_setpgid;
MACRO_SYS SYS_setpriority;
MACRO_SYS SYS_setregid;
MACRO_SYS SYS_setresgid;
MACRO_SYS SYS_setresuid;
MACRO_SYS SYS_setreuid;
MACRO_SYS SYS_setrlimit;
MACRO_SYS SYS_setsid;
MACRO_SYS SYS_setsockopt;
MACRO_SYS SYS_settimeofday;
MACRO_SYS SYS_setuid;
MACRO_SYS SYS_setxattr;
MACRO_SYS SYS_shmat;
MACRO_SYS SYS_shmctl;
MACRO_SYS SYS_shmdt;
MACRO_SYS SYS_shmget;
MACRO_SYS SYS_shutdown;
MACRO_SYS SYS_sigaltstack;
MACRO_SYS SYS_signalfd4;
MACRO_SYS SYS_socket;
MACRO_SYS SYS_socketpair;
MACRO_SYS SYS_splice;
MACRO_SYS SYS_statfs;
MACRO_SYS SYS_swapoff;
MACRO_SYS SYS_swapon;
MACRO_SYS SYS_symlinkat;
MACRO_SYS SYS_sync;
MACRO_SYS SYS_sync_file_range;
MACRO_SYS SYS_syncfs;
MACRO_SYS SYS_sysinfo;
MACRO_SYS SYS_syslog;
MACRO_SYS SYS_tee;
MACRO_SYS SYS_tgkill;
MACRO_SYS SYS_timer_create;
MACRO_SYS SYS_timer_delete;
MACRO_SYS SYS_timer_getoverrun;
MACRO_SYS SYS_timer_gettime;
MACRO_SYS SYS_timer_settime;
MACRO_SYS SYS_timerfd_create;
MACRO_SYS SYS_timerfd_gettime;
MACRO_SYS SYS_timerfd_settime;
MACRO_SYS SYS_times;
MACRO_SYS SYS_tkill;
MACRO_SYS SYS_truncate;
MACRO_SYS SYS_umask;
MACRO_SYS SYS_umount2;
MACRO_SYS SYS_uname;
MACRO_SYS SYS_unlinkat;
MACRO_SYS SYS_unshare;
MACRO_SYS SYS_userfaultfd;
MACRO_SYS SYS_utimensat;
MACRO_SYS SYS_vhangup;
MACRO_SYS SYS_vmsplice;
MACRO_SYS SYS_wait4;
MACRO_SYS SYS_waitid;
MACRO_SYS SYS_write;
MACRO_SYS SYS_writev;
MACRO___NR __NR_accept;
MACRO___NR __NR_accept4;
MACRO___NR __NR_acct;
MACRO___NR __NR_add_key;
MACRO___NR __NR_adjtimex;
MACRO___NR __NR_bind;
MACRO___NR __NR_bpf;
MACRO___NR __NR_brk;
MACRO___NR __NR_capget;
MACRO___NR __NR_capset;
MACRO___NR __NR_chdir;
MACRO___NR __NR_chroot;
MACRO___NR __NR_clock_adjtime;
MACRO___NR __NR_clock_getres;
MACRO___NR __NR_clock_gettime;
MACRO___NR __NR_clock_nanosleep;
MACRO___NR __NR_clock_settime;
MACRO___NR __NR_clone;
MACRO___NR __NR_close;
MACRO___NR __NR_connect;
MACRO___NR __NR_copy_file_range;
MACRO___NR __NR_delete_module;
MACRO___NR __NR_dup;
MACRO___NR __NR_dup3;
MACRO___NR __NR_epoll_create1;
MACRO___NR __NR_epoll_ctl;
MACRO___NR __NR_epoll_pwait;
MACRO___NR __NR_eventfd2;
MACRO___NR __NR_execve;
MACRO___NR __NR_execveat;
MACRO___NR __NR_exit;
MACRO___NR __NR_exit_group;
MACRO___NR __NR_faccessat;
MACRO___NR __NR_fadvise64;
MACRO___NR __NR_fallocate;
MACRO___NR __NR_fanotify_init;
MACRO___NR __NR_fanotify_mark;
MACRO___NR __NR_fchdir;
MACRO___NR __NR_fchmod;
MACRO___NR __NR_fchmodat;
MACRO___NR __NR_fchown;
MACRO___NR __NR_fchownat;
MACRO___NR __NR_fcntl;
MACRO___NR __NR_fdatasync;
MACRO___NR __NR_fgetxattr;
MACRO___NR __NR_finit_module;
MACRO___NR __NR_flistxattr;
MACRO___NR __NR_flock;
MACRO___NR __NR_fremovexattr;
MACRO___NR __NR_fsetxattr;
MACRO___NR __NR_fstat;
MACRO___NR __NR_fstatat;
MACRO___NR __NR_fstatfs;
MACRO___NR __NR_fsync;
MACRO___NR __NR_ftruncate;
MACRO___NR __NR_futex;
MACRO___NR __NR_get_mempolicy;
MACRO___NR __NR_get_robust_list;
MACRO___NR __NR_getcpu;
MACRO___NR __NR_getcwd;
MACRO___NR __NR_getdents64;
MACRO___NR __NR_getegid;
MACRO___NR __NR_geteuid;
MACRO___NR __NR_getgid;
MACRO___NR __NR_getgroups;
MACRO___NR __NR_getitimer;
MACRO___NR __NR_getpeername;
MACRO___NR __NR_getpgid;
MACRO___NR __NR_getpid;
MACRO___NR __NR_getppid;
MACRO___NR __NR_getpriority;
MACRO___NR __NR_getrandom;
MACRO___NR __NR_getresgid;
MACRO___NR __NR_getresuid;
MACRO___NR __NR_getrlimit;
MACRO___NR __NR_getrusage;
MACRO___NR __NR_getsid;
MACRO___NR __NR_getsockname;
MACRO___NR __NR_getsockopt;
MACRO___NR __NR_gettid;
MACRO___NR __NR_gettimeofday;
MACRO___NR __NR_getuid;
MACRO___NR __NR_getxattr;
MACRO___NR __NR_init_module;
MACRO___NR __NR_inotify_add_watch;
MACRO___NR __NR_inotify_init1;
MACRO___NR __NR_inotify_rm_watch;
MACRO___NR __NR_io_cancel;
MACRO___NR __NR_io_destroy;
MACRO___NR __NR_io_getevents;
MACRO___NR _NR_io_setup;
MACRO___NR __NR_io_submit;
MACRO___NR __NR_ioctl;
MACRO___NR __NR_ioprio_get;
MACRO___NR __NR_ioprio_set;
MACRO___NR __NR_kcmp;
MACRO___NR __NR_kexec_load;
MACRO___NR __NR_keyctl;
MACRO___NR __NR_kill;
MACRO___NR __NR_lgetxattr;
MACRO___NR __NR_linkat;
MACRO___NR __NR_listen;
MACRO___NR __NR_listxattr;
MACRO___NR __NR_llistxattr;
MACRO___NR __NR_lookup_dcookie;
MACRO___NR __NR_lremovexattr;
MACRO___NR __NR_lseek;
MACRO___NR __NR_lsetxattr;
MACRO___NR __NR_madvise;
MACRO___NR __NR_mbind;
MACRO___NR __NR_membarrier;
MACRO___NR __NR_memfd_create;
MACRO___NR __NR_migrate_pages;
MACRO___NR __NR_mincore;
MACRO___NR __NR_mkdirat;
MACRO___NR __NR_mknodat;
MACRO___NR __NR_mlock;
MACRO___NR __NR_mlock2;
MACRO___NR __NR_mlockall;
MACRO___NR __NR_mmap;
MACRO___NR __NR_mount;
MACRO___NR __NR_move_pages;
MACRO___NR __NR_mprotect;
MACRO___NR __NR_mq_getsetattr;
MACRO___NR __NR_mq_notify;
MACRO___NR __NR_mq_open;
MACRO___NR __NR_mq_timedreceive;
MACRO___NR __NR_mq_timedsend;
MACRO___NR __NR_mq_unlink;
MACRO___NR __NR_mremap;
MACRO___NR __NR_msgctl;
MACRO___NR __NR_msgget;
MACRO___NR __NR_msgrcv;
MACRO___NR __NR_msgsnd;
MACRO___NR __NR_msync;
MACRO___NR __NR_munlock;
MACRO___NR __NR_munlockall;
MACRO___NR __NR_munmap;
MACRO___NR __NR_name_to_handle_at;
MACRO___NR __NR_nanosleep;
MACRO___NR __NR_nfsservctl;
MACRO___NR __NR_open_by_handle_at;
MACRO___NR __NR_openat;
MACRO___NR __NR_or1k_atomic;
MACRO___NR __NR_perf_event_open;
MACRO___NR __NR_personality;
MACRO___NR __NR_pipe2;
MACRO___NR __NR_pivot_root;
MACRO___NR __NR_ppoll;
MACRO___NR __NR_prctl;
MACRO___NR __NR_pread64;
MACRO___NR __NR_preadv;
MACRO___NR __NR_preadv2;
MACRO___NR __NR_prlimit64;
MACRO___NR __NR_process_vm_readv;
MACRO___NR __NR_process_vm_writev;
MACRO___NR __NR_pselect6;
MACRO___NR __NR_ptrace;
MACRO___NR __NR_pwrite64;
MACRO___NR __NR_pwritev;
MACRO___NR __NR_pwritev2;
MACRO___NR __NR_quotactl;
MACRO___NR __NR_read;
MACRO___NR __NR_readahead;
MACRO___NR __NR_readlinkat;
MACRO___NR __NR_readv;
MACRO___NR __NR_reboot;
MACRO___NR __NR_recvfrom;
MACRO___NR __NR_recvmmsg;
MACRO___NR __NR_recvmsg;
MACRO___NR __NR_remap_file_pages;
MACRO___NR __NR_removexattr;
MACRO___NR __NR_renameat;
MACRO___NR __NR_renameat2;
MACRO___NR __NR_request_key;
MACRO___NR __NR_restart_syscall;
MACRO___NR __NR_rt_sigaction;
MACRO___NR __NR_rt_sigpending;
MACRO___NR __NR_rt_sigprocmask;
MACRO___NR __NR_rt_sigqueueinfo;
MACRO___NR __NR_rt_sigreturn;
MACRO___NR __NR_rt_sigsuspend;
MACRO___NR __NR_rt_sigtimedwait;
MACRO___NR __NR_rt_tgsigqueueinfo;
MACRO___NR __NR_sched_get_priority_max;
MACRO___NR __NR_sched_get_priority_min;
MACRO___NR __NR_sched_getaffinity;
MACRO___NR __NR_sched_getattr;
MACRO___NR __NR_sched_getparam;
MACRO___NR __NR_sched_getscheduler;
MACRO___NR __NR_sched_rr_get_interval;
MACRO___NR __NR_sched_setaffinity;
MACRO___NR __NR_sched_setattr;
MACRO___NR __NR_sched_setparam;
MACRO___NR __NR_sched_setscheduler;
MACRO___NR __NR_sched_yield;
MACRO___NR __NR_seccomp;
MACRO___NR __NR_semctl;
MACRO___NR __NR_semget;
MACRO___NR __NR_semop;
MACRO___NR __NR_semtimedop;
MACRO___NR __NR_sendfile;
MACRO___NR __NR_sendmmsg;
MACRO___NR __NR_sendmsg;
MACRO___NR __NR_sendto;
MACRO___NR __NR_set_mempolicy;
MACRO___NR __NR_set_robust_list;
MACRO___NR __NR_set_tid_address;
MACRO___NR __NR_setdomainname;
MACRO___NR __NR_setfsgid;
MACRO___NR __NR_setfsuid;
MACRO___NR __NR_setgid;
MACRO___NR __NR_setgroups;
MACRO___NR __NR_sethostname;
MACRO___NR __NR_setitimer;
MACRO___NR __NR_setns;
MACRO___NR __NR_setpgid;
MACRO___NR __NR_setpriority;
MACRO___NR __NR_setregid;
MACRO___NR __NR_setresgid;
MACRO___NR __NR_setresuid;
MACRO___NR __NR_setreuid;
MACRO___NR __NR_setrlimit;
MACRO___NR __NR_setsid;
MACRO___NR __NR_setsockopt;
MACRO___NR __NR_settimeofday;
MACRO___NR __NR_setuid;
MACRO___NR __NR_setxattr;
MACRO___NR __NR_shmat;
MACRO___NR __NR_shmctl;
MACRO___NR __NR_shmdt;
MACRO___NR __NR_shmget;
MACRO___NR __NR_shutdown;
MACRO___NR __NR_sigaltstack;
MACRO___NR __NR_signalfd4;
MACRO___NR __NR_socket;
MACRO___NR __NR_socketpair;
MACRO___NR __NR_splice;
MACRO___NR __NR_statfs;
MACRO___NR __NR_swapoff;
MACRO___NR __NR_swapon;
MACRO___NR __NR_symlinkat;
MACRO___NR __NR_sync;
MACRO___NR __NR_sync_file_range;
MACRO___NR __NR_syncfs;
MACRO___NR __NR_sysinfo;
MACRO___NR __NR_syslog;
MACRO___NR __NR_tee;
MACRO___NR __NR_tgkill;
MACRO___NR __NR_timer_create;
MACRO___NR __NR_timer_delete;
MACRO___NR __NR_timer_getoverrun;
MACRO___NR __NR_timer_gettime;
MACRO___NR __NR_timer_settime;
MACRO___NR __NR_timerfd_create;
MACRO___NR __NR_timerfd_gettime;
MACRO___NR __NR_timerfd_settime;
MACRO___NR __NR_times;
MACRO___NR __NR_tkill;
MACRO___NR __NR_truncate;
MACRO___NR __NR_umask;
MACRO___NR __NR_umount2;
MACRO___NR __NR_uname;
MACRO___NR __NR_unlinkat;
MACRO___NR __NR_unshare;
MACRO___NR __NR_userfaultfd;
MACRO___NR __NR_utimensat;
MACRO___NR __NR_vhangup;
MACRO___NR __NR_vmsplice;
MACRO___NR __NR_wait4;
MACRO___NR __NR_waitid;
MACRO___NR __NR_write;
MACRO___NR __NR_writev;
__int64 sys32_quotactl(unsigned int cmd, const char *special, qid_t id, void *addr);
__int64 sys_accept(int, struct sockaddr *, int *);
__int64 sys_accept4(int, struct sockaddr *, int *, int);
__int64 sys_access(const char *filename, int mode);
__int64 sys_acct(const char *name);
__int64 sys_add_key(const char *type, const char *description, const void *payload, size_t plen, key_serial_t destringid);
__int64 sys_adjtimex(struct timex *txc_p);
__int64 sys_alarm(unsigned int seconds);
__int64 sys_bdflush(int func, __int64 data);
__int64 sys_bind(int, struct sockaddr *, int);
__int64 sys_bpf(int cmd, union bpf_attr *attr, unsigned int size);
__int64 sys_brk(unsigned __int64 brk);
__int64 sys_capget(cap_user_header_t header, cap_user_data_t dataptr);
__int64 sys_capset(cap_user_header_t header, const cap_user_data_t data);
__int64 sys_chdir(const char *filename);
__int64 sys_chmod(const char *filename, umode_t mode);
__int64 sys_chown(const char *filename, uid_t user, gid_t group);
__int64 sys_chroot(const char *filename);
__int64 sys_clock_adjtime(clockid_t which_clock, struct timex *tx);
__int64 sys_clock_getres(clockid_t which_clock, struct timespec *tp);
__int64 sys_clock_gettime(clockid_t which_clock, struct timespec *tp);
__int64 sys_clock_nanosleep(clockid_t which_clock, int flags, const struct timespec *rqtp, struct timespec *rmtp);
__int64 sys_clock_settime(clockid_t which_clock, const struct timespec *tp);
__int64 sys_clone(unsigned __int64, unsigned __int64, int *, int *, unsigned __int64);
__int64 sys_close(unsigned int fd);
__int64 sys_connect(int, struct sockaddr *, int);
__int64 sys_copy_file_range(int fd_in, loff_t *off_in, int fd_out, loff_t *off_out, size_t len, unsigned int flags);
__int64 sys_creat(const char *pathname, umode_t mode);
__int64 sys_delete_module(const char *name_user, unsigned int flags);
__int64 sys_dup(unsigned int fildes);
__int64 sys_dup2(unsigned int oldfd, unsigned int newfd);
__int64 sys_dup3(unsigned int oldfd, unsigned int newfd, int flags);
__int64 sys_epoll_create(int size);
__int64 sys_epoll_create1(int flags);
__int64 sys_epoll_ctl(int epfd, int op, int fd, struct epoll_event *event);
__int64 sys_epoll_pwait(int epfd, struct epoll_event *events, int maxevents, int timeout, const sigset_t *sigmask, size_t sigsetsize);
__int64 sys_epoll_wait(int epfd, struct epoll_event *events, int maxevents, int timeout);
__int64 sys_eventfd(unsigned int count);
__int64 sys_eventfd2(unsigned int count, int flags);
__int64 sys_execve(const char *filename, const char *const *argv, const char *const *envp);
__int64 sys_execveat(int dfd, const char *filename, const char *const *argv, const char *const *envp, int flags);
__int64 sys_exit(int error_code);
__int64 sys_exit_group(int error_code);
__int64 sys_faccessat(int dfd, const char *filename, int mode);
__int64 sys_fadvise64(int fd, loff_t offset, size_t len, int advice);
__int64 sys_fadvise64_64(int fd, loff_t offset, loff_t len, int advice);
__int64 sys_fallocate(int fd, int mode, loff_t offset, loff_t len);
__int64 sys_fanotify_init(unsigned int flags, unsigned int event_f_flags);
__int64 sys_fanotify_mark(int fanotify_fd, unsigned int flags, u64 mask, int fd, const char *pathname);
__int64 sys_fchdir(unsigned int fd);
__int64 sys_fchmod(unsigned int fd, umode_t mode);
__int64 sys_fchmodat(int dfd, const char *filename, umode_t mode);
__int64 sys_fchown(unsigned int fd, uid_t user, gid_t group);
__int64 sys_fchownat(int dfd, const char *filename, uid_t user, gid_t group, int flag);
__int64 sys_fcntl(unsigned int fd, unsigned int cmd, unsigned __int64 arg);
__int64 sys_fdatasync(unsigned int fd);
__int64 sys_fgetxattr(int fd, const char *name, void *value, size_t size);
__int64 sys_finit_module(int fd, const char *uargs, int flags);
__int64 sys_flistxattr(int fd, char *list, size_t size);
__int64 sys_flock(unsigned int fd, unsigned int cmd);
__int64 sys_fork(void);
__int64 sys_fremovexattr(int fd, const char *name);
__int64 sys_fsetxattr(int fd, const char *name, const void *value, size_t size, int flags);
__int64 sys_fstat(unsigned int fd, struct __old_kernel_stat *statbuf);
__int64 sys_fstatfs(unsigned int fd, struct statfs *buf);
__int64 sys_fstatfs64(unsigned int fd, size_t sz, struct statfs64 *buf);
__int64 sys_fsync(unsigned int fd);
__int64 sys_ftruncate(unsigned int fd, unsigned __int64 length);
__int64 sys_futex(u32 *uaddr, int op, u32 val, struct timespec *utime, u32 *uaddr2, u32 val3);
__int64 sys_futimesat(int dfd, const char *filename, struct timeval *utimes);
__int64 sys_get_mempolicy(int *policy, unsigned __int64 *nmask, unsigned __int64 maxnode, unsigned __int64 addr, unsigned __int64 flags);
__int64 sys_get_robust_list(int pid, struct robust_list_head **head_ptr, size_t *len_ptr);
__int64 sys_getcpu(unsigned int *cpu, unsigned int *node, struct getcpu_cache *cache);
__int64 sys_getcwd(char *buf, unsigned __int64 size);
__int64 sys_getdents(unsigned int fd, struct linux_dirent *dirent, unsigned int count);
__int64 sys_getdents64(unsigned int fd, struct linux_dirent64 *dirent, unsigned int count);
__int64 sys_getegid(void);
__int64 sys_geteuid(void);
__int64 sys_getgid(void);
__int64 sys_getgroups(int gidsetsize, gid_t *grouplist);
__int64 sys_gethostname(char *name, int len);
__int64 sys_getitimer(int which, struct itimerval *value);
__int64 sys_getpeername(int, struct sockaddr *, int *);
__int64 sys_getpgid(pid_t pid);
__int64 sys_getpgrp(void);
__int64 sys_getpid(void);
__int64 sys_getppid(void);
__int64 sys_getpriority(int which, int who);
__int64 sys_getrandom(char *buf, size_t count, unsigned int flags);
__int64 sys_getresgid(gid_t *rgid, gid_t *egid, gid_t *sgid);
__int64 sys_getresuid(uid_t *ruid, uid_t *euid, uid_t *suid);
__int64 sys_getrlimit(unsigned int resource, struct rlimit *rlim);
__int64 sys_getrusage(int who, struct rusage *ru);
__int64 sys_getsid(pid_t pid);
__int64 sys_getsockname(int, struct sockaddr *, int *);
__int64 sys_getsockopt(int fd, int level, int optname, char *optval, int *optlen);
__int64 sys_gettid(void);
__int64 sys_gettimeofday(struct timeval *tv, struct timezone *tz);
__int64 sys_getuid(void);
__int64 sys_getxattr(const char *path, const char *name, void *value, size_t size);
__int64 sys_init_module(void *umod, unsigned __int64 len, const char *uargs);
__int64 sys_inotify_add_watch(int fd, const char *path, u32 mask);
__int64 sys_inotify_init(void);
__int64 sys_inotify_init1(int flags);
__int64 sys_inotify_rm_watch(int fd, __s32 wd);
__int64 sys_io_cancel(aio_context_t ctx_id, struct iocb *iocb, struct io_event *result);
__int64 sys_io_destroy(aio_context_t ctx);
__int64 sys_io_getevents(aio_context_t ctx_id, __int64 min_nr, __int64 nr, struct io_event *events, struct timespec *timeout);
__int64 sys_io_setup(unsigned int nr_reqs, aio_context_t *ctx);
__int64 sys_io_submit(aio_context_t, __int64, struct iocb **);
__int64 sys_ioctl(unsigned int fd, unsigned int cmd, unsigned __int64 arg);
__int64 sys_ioperm(unsigned __int64 from, unsigned __int64 num, int on);
__int64 sys_ioprio_get(int which, int who);
__int64 sys_ioprio_set(int which, int who, int ioprio);
__int64 sys_ipc(unsigned int call, int first, unsigned __int64 second, unsigned __int64 third, void *ptr, __int64 fifth);
__int64 sys_kcmp(pid_t pid1, pid_t pid2, int type, unsigned __int64 idx1, unsigned __int64 idx2);
__int64 sys_kexec_file_load(int kernel_fd, int initrd_fd, unsigned __int64 cmdline_len, const char *cmdline_ptr, unsigned __int64 flags);
__int64 sys_kexec_load(unsigned __int64 entry, unsigned __int64 nr_segments, struct kexec_segment *segments, unsigned __int64 flags);
__int64 sys_keyctl(int cmd, unsigned __int64 arg2, unsigned __int64 arg3, unsigned __int64 arg4, unsigned __int64 arg5);
__int64 sys_kill(pid_t pid, int sig);
__int64 sys_lchown(const char *filename, uid_t user, gid_t group);
__int64 sys_lgetxattr(const char *path, const char *name, void *value, size_t size);
__int64 sys_link(const char *oldname, const char *newname);
__int64 sys_linkat(int olddfd, const char *oldname, int newdfd, const char *newname, int flags);
__int64 sys_listen(int, int);
__int64 sys_listxattr(const char *path, char *list, size_t size);
__int64 sys_llistxattr(const char *path, char *list, size_t size);
__int64 sys_llseek(unsigned int fd, unsigned __int64 offset_high, unsigned __int64 offset_low, loff_t *result, unsigned int whence);
__int64 sys_lookup_dcookie(u64 cookie64, char *buf, size_t len);
__int64 sys_lremovexattr(const char *path, const char *name);
__int64 sys_lseek(unsigned int fd, off_t offset, unsigned int whence);
__int64 sys_lsetxattr(const char *path, const char *name, const void *value, size_t size, int flags);
__int64 sys_lstat(const char *filename, struct __old_kernel_stat *statbuf);
__int64 sys_madvise(unsigned __int64 start, size_t len, int behavior);
__int64 sys_mbind(unsigned __int64 start, unsigned __int64 len, unsigned __int64 mode, const unsigned __int64 *nmask, unsigned __int64 maxnode, unsigned int flags);
__int64 sys_membarrier(int cmd, int flags);
__int64 sys_memfd_create(const char *uname_ptr, unsigned int flags);
__int64 sys_migrate_pages(pid_t pid, unsigned __int64 maxnode, const unsigned __int64 *from, const unsigned __int64 *to);
__int64 sys_mincore(unsigned __int64 start, size_t len, unsigned __int8 *vec);
__int64 sys_mkdir(const char *pathname, umode_t mode);
__int64 sys_mkdirat(int dfd, const char *pathname, umode_t mode);
__int64 sys_mknod(const char *filename, umode_t mode, unsigned int dev);
__int64 sys_mknodat(int dfd, const char *filename, umode_t mode, unsigned int dev);
__int64 sys_mlock(unsigned __int64 start, size_t len);
__int64 sys_mlock2(unsigned __int64 start, size_t len, int flags);
__int64 sys_mlockall(int flags);
__int64 sys_mmap_pgoff(unsigned __int64 addr, unsigned __int64 len, unsigned __int64 prot, unsigned __int64 flags, unsigned __int64 fd, unsigned __int64 pgoff);
__int64 sys_mount(char *dev_name, char *dir_name, char *type, unsigned __int64 flags, void *data);
__int64 sys_move_pages(pid_t pid, unsigned __int64 nr_pages, const void **pages, const int *nodes, int *status, int flags);
__int64 sys_mprotect(unsigned __int64 start, size_t len, unsigned __int64 prot);
__int64 sys_mq_getsetattr(mqd_t mqdes, const struct mq_attr *mqstat, struct mq_attr *omqstat);
__int64 sys_mq_notify(mqd_t mqdes, const struct sigevent *notification);
__int64 sys_mq_open(const char *name, int oflag, umode_t mode, struct mq_attr *attr);
__int64 sys_mq_timedreceive(mqd_t mqdes, char *msg_ptr, size_t msg_len, unsigned int *msg_prio, const struct timespec *abs_timeout);
__int64 sys_mq_timedsend(mqd_t mqdes, const char *msg_ptr, size_t msg_len, unsigned int msg_prio, const struct timespec *abs_timeout);
__int64 sys_mq_unlink(const char *name);
__int64 sys_mremap(unsigned __int64 addr, unsigned __int64 old_len, unsigned __int64 new_len, unsigned __int64 flags, unsigned __int64 new_addr);
__int64 sys_msgctl(int msqid, int cmd, struct msqid_ds *buf);
__int64 sys_msgget(key_t key, int msgflg);
__int64 sys_msgrcv(int msqid, struct msgbuf *msgp, size_t msgsz, __int64 msgtyp, int msgflg);
__int64 sys_msgsnd(int msqid, struct msgbuf *msgp, size_t msgsz, int msgflg);
__int64 sys_msync(unsigned __int64 start, size_t len, int flags);
__int64 sys_munlock(unsigned __int64 start, size_t len);
__int64 sys_munlockall(void);
__int64 sys_munmap(unsigned __int64 addr, size_t len);
__int64 sys_name_to_handle_at(int dfd, const char *name, struct file_handle *handle, int *mnt_id, int flag);
__int64 sys_nanosleep(struct timespec *rqtp, struct timespec *rmtp);
__int64 sys_newfstat(unsigned int fd, struct stat *statbuf);
__int64 sys_newfstatat(int dfd, const char *filename, struct stat *statbuf, int flag);
__int64 sys_newlstat(const char *filename, struct stat *statbuf);
__int64 sys_newstat(const char *filename, struct stat *statbuf);
__int64 sys_newuname(struct new_utsname *name);
__int64 sys_ni_syscall(void);
__int64 sys_nice(int increment);
__int64 sys_old_getrlimit(unsigned int resource, struct rlimit *rlim);
__int64 sys_old_mmap(struct mmap_arg_struct *arg);
__int64 sys_old_readdir(unsigned int, struct old_linux_dirent *, unsigned int);
__int64 sys_old_select(struct sel_arg_struct *arg);
__int64 sys_oldumount(char *name);
__int64 sys_olduname(struct oldold_utsname *);
__int64 sys_open(const char *filename, int flags, umode_t mode);
__int64 sys_open_by_handle_at(int mountdirfd, struct file_handle *handle, int flags);
__int64 sys_openat(int dfd, const char *filename, int flags, umode_t mode);
__int64 sys_pause(void);
__int64 sys_pciconfig_iobase(__int64 which, unsigned __int64 bus, unsigned __int64 devfn);
__int64 sys_pciconfig_read(unsigned __int64 bus, unsigned __int64 dfn, unsigned __int64 off, unsigned __int64 len, void *buf);
__int64 sys_pciconfig_write(unsigned __int64 bus, unsigned __int64 dfn, unsigned __int64 off, unsigned __int64 len, void *buf);
__int64 sys_perf_event_open(struct perf_event_attr *attr_uptr, pid_t pid, int cpu, int group_fd, unsigned __int64 flags);
__int64 sys_personality(unsigned int personality);
__int64 sys_pipe(int *fildes);
__int64 sys_pipe2(int *fildes, int flags);
__int64 sys_pivot_root(const char *new_root, const char *put_old);
__int64 sys_poll(struct pollfd *ufds, unsigned int nfds, int timeout);
__int64 sys_ppoll(struct pollfd *, unsigned int, struct timespec *, const sigset_t *, size_t);
__int64 sys_prctl(int option, unsigned __int64 arg2, unsigned __int64 arg3, unsigned __int64 arg4, unsigned __int64 arg5);
__int64 sys_pread64(unsigned int fd, char *buf, size_t count, loff_t pos);
__int64 sys_preadv(unsigned __int64 fd, const struct iovec *vec, unsigned __int64 vlen, unsigned __int64 pos_l, unsigned __int64 pos_h);
__int64 sys_preadv2(unsigned __int64 fd, const struct iovec *vec, unsigned __int64 vlen, unsigned __int64 pos_l, unsigned __int64 pos_h, int flags);
__int64 sys_prlimit64(pid_t pid, unsigned int resource, const struct rlimit64 *new_rlim, struct rlimit64 *old_rlim);
__int64 sys_process_vm_readv(pid_t pid, const struct iovec *lvec, unsigned __int64 liovcnt, const struct iovec *rvec, unsigned __int64 riovcnt, unsigned __int64 flags);
__int64 sys_process_vm_writev(pid_t pid, const struct iovec *lvec, unsigned __int64 liovcnt, const struct iovec *rvec, unsigned __int64 riovcnt, unsigned __int64 flags);
__int64 sys_pselect6(int, fd_set *, fd_set *, fd_set *, struct timespec *, void *);
__int64 sys_ptrace(__int64 request, __int64 pid, unsigned __int64 addr, unsigned __int64 data);
__int64 sys_pwrite64(unsigned int fd, const char *buf, size_t count, loff_t pos);
__int64 sys_pwritev(unsigned __int64 fd, const struct iovec *vec, unsigned __int64 vlen, unsigned __int64 pos_l, unsigned __int64 pos_h);
__int64 sys_pwritev2(unsigned __int64 fd, const struct iovec *vec, unsigned __int64 vlen, unsigned __int64 pos_l, unsigned __int64 pos_h, int flags);
__int64 sys_quotactl(unsigned int cmd, const char *special, qid_t id, void *addr);
__int64 sys_read(unsigned int fd, char *buf, size_t count);
__int64 sys_readahead(int fd, loff_t offset, size_t count);
__int64 sys_readlink(const char *path, char *buf, int bufsiz);
__int64 sys_readlinkat(int dfd, const char *path, char *buf, int bufsiz);
__int64 sys_readv(unsigned __int64 fd, const struct iovec *vec, unsigned __int64 vlen);
__int64 sys_reboot(int magic1, int magic2, unsigned int cmd, void *arg);
__int64 sys_recv(int, void *, size_t, unsigned int);
__int64 sys_recvfrom(int, void *, size_t, unsigned int, struct sockaddr *, int *);
__int64 sys_recvmmsg(int fd, struct mmsghdr *msg, unsigned int vlen, unsigned int flags, struct timespec *timeout);
__int64 sys_recvmsg(int fd, struct user_msghdr *msg, unsigned int flags);
__int64 sys_remap_file_pages(unsigned __int64 start, unsigned __int64 size, unsigned __int64 prot, unsigned __int64 pgoff, unsigned __int64 flags);
__int64 sys_removexattr(const char *path, const char *name);
__int64 sys_rename(const char *oldname, const char *newname);
__int64 sys_renameat(int olddfd, const char *oldname, int newdfd, const char *newname);
__int64 sys_renameat2(int olddfd, const char *oldname, int newdfd, const char *newname, unsigned int flags);
__int64 sys_request_key(const char *type, const char *description, const char *callout_info, key_serial_t destringid);
__int64 sys_restart_syscall(void);
__int64 sys_rmdir(const char *pathname);
__int64 sys_rt_sigaction(int, const struct sigaction *, struct sigaction *, size_t);
__int64 sys_rt_sigpending(sigset_t *set, size_t sigsetsize);
__int64 sys_rt_sigprocmask(int how, sigset_t *set, sigset_t *oset, size_t sigsetsize);
__int64 sys_rt_sigqueueinfo(pid_t pid, int sig, siginfo_t *uinfo);
__int64 sys_rt_sigsuspend(sigset_t *unewset, size_t sigsetsize);
__int64 sys_rt_sigtimedwait(const sigset_t *uthese, siginfo_t *uinfo, const struct timespec *uts, size_t sigsetsize);
__int64 sys_rt_tgsigqueueinfo(pid_t tgid, pid_t pid, int sig, siginfo_t *uinfo);
__int64 sys_sched_get_priority_max(int policy);
__int64 sys_sched_get_priority_min(int policy);
__int64 sys_sched_getaffinity(pid_t pid, unsigned int len, unsigned __int64 *user_mask_ptr);
__int64 sys_sched_getattr(pid_t pid, struct sched_attr *attr, unsigned int size, unsigned int flags);
__int64 sys_sched_getparam(pid_t pid, struct sched_param *param);
__int64 sys_sched_getscheduler(pid_t pid);
__int64 sys_sched_rr_get_interval(pid_t pid, struct timespec *interval);
__int64 sys_sched_setaffinity(pid_t pid, unsigned int len, unsigned __int64 *user_mask_ptr);
__int64 sys_sched_setattr(pid_t pid, struct sched_attr *attr, unsigned int flags);
__int64 sys_sched_setparam(pid_t pid, struct sched_param *param);
__int64 sys_sched_setscheduler(pid_t pid, int policy, struct sched_param *param);
__int64 sys_sched_yield(void);
__int64 sys_seccomp(unsigned int op, unsigned int flags, const char *uargs);
__int64 sys_select(int n, fd_set *inp, fd_set *outp, fd_set *exp, struct timeval *tvp);
__int64 sys_semctl(int semid, int semnum, int cmd, unsigned __int64 arg);
__int64 sys_semget(key_t key, int nsems, int semflg);
__int64 sys_semop(int semid, struct sembuf *sops, unsigned int nsops);
__int64 sys_semtimedop(int semid, struct sembuf *sops, unsigned int nsops, const struct timespec *timeout);
__int64 sys_send(int, void *, size_t, unsigned int);
__int64 sys_sendfile(int out_fd, int in_fd, off_t *offset, size_t count);
__int64 sys_sendfile64(int out_fd, int in_fd, loff_t *offset, size_t count);
__int64 sys_sendmmsg(int fd, struct mmsghdr *msg, unsigned int vlen, unsigned int flags);
__int64 sys_sendmsg(int fd, struct user_msghdr *msg, unsigned int flags);
__int64 sys_sendto(int, void *, size_t, unsigned int, struct sockaddr *, int);
__int64 sys_set_mempolicy(int mode, const unsigned __int64 *nmask, unsigned __int64 maxnode);
__int64 sys_set_robust_list(struct robust_list_head *head, size_t len);
__int64 sys_set_tid_address(int *tidptr);
__int64 sys_setdomainname(char *name, int len);
__int64 sys_setfsgid(gid_t gid);
__int64 sys_setfsuid(uid_t uid);
__int64 sys_setgid(gid_t gid);
__int64 sys_setgroups(int gidsetsize, gid_t *grouplist);
__int64 sys_sethostname(char *name, int len);
__int64 sys_setitimer(int which, struct itimerval *value, struct itimerval *ovalue);
__int64 sys_setns(int fd, int nstype);
__int64 sys_setpgid(pid_t pid, pid_t pgid);
__int64 sys_setpriority(int which, int who, int niceval);
__int64 sys_setregid(gid_t rgid, gid_t egid);
__int64 sys_setresgid(gid_t rgid, gid_t egid, gid_t sgid);
__int64 sys_setresuid(uid_t ruid, uid_t euid, uid_t suid);
__int64 sys_setreuid(uid_t ruid, uid_t euid);
__int64 sys_setrlimit(unsigned int resource, struct rlimit *rlim);
__int64 sys_setsid(void);
__int64 sys_setsockopt(int fd, int level, int optname, char *optval, int optlen);
__int64 sys_settimeofday(struct timeval *tv, struct timezone *tz);
__int64 sys_setuid(uid_t uid);
__int64 sys_setxattr(const char *path, const char *name, const void *value, size_t size, int flags);
__int64 sys_sgetmask(void);
__int64 sys_shmat(int shmid, char *shmaddr, int shmflg);
__int64 sys_shmctl(int shmid, int cmd, struct shmid_ds *buf);
__int64 sys_shmdt(char *shmaddr);
__int64 sys_shmget(key_t key, size_t size, int flag);
__int64 sys_shutdown(int, int);
__int64 sys_sigaltstack(const struct sigaltstack *uss, struct sigaltstack *uoss);
__int64 sys_signal(int sig, __sighandler_t handler);
__int64 sys_signalfd(int ufd, sigset_t *user_mask, size_t sizemask);
__int64 sys_signalfd4(int ufd, sigset_t *user_mask, size_t sizemask, int flags);
__int64 sys_sigpending(old_sigset_t *set);
__int64 sys_sigprocmask(int how, old_sigset_t *set, old_sigset_t *oset);
__int64 sys_socket(int, int, int);
__int64 sys_socketcall(int call, unsigned __int64 *args);
__int64 sys_socketpair(int, int, int, int *);
__int64 sys_splice(int fd_in, loff_t *off_in, int fd_out, loff_t *off_out, size_t len, unsigned int flags);
__int64 sys_spu_create(const char *name, unsigned int flags, umode_t mode, int fd);
__int64 sys_spu_run(int fd, __u32 *unpc, __u32 *ustatus);
__int64 sys_ssetmask(int newmask);
__int64 sys_stat(const char *filename, struct __old_kernel_stat *statbuf);
__int64 sys_statfs(const char *path, struct statfs *buf);
__int64 sys_statfs64(const char *path, size_t sz, struct statfs64 *buf);
__int64 sys_stime(time_t *tptr);
__int64 sys_swapoff(const char *specialfile);
__int64 sys_swapon(const char *specialfile, int swap_flags);
__int64 sys_symlink(const char *old, const char *new);
__int64 sys_symlinkat(const char *oldname, int newdfd, const char *newname);
__int64 sys_sync(void);
__int64 sys_sync_file_range(int fd, loff_t offset, loff_t nbytes, unsigned int flags);
__int64 sys_sync_file_range2(int fd, unsigned int flags, loff_t offset, loff_t nbytes);
__int64 sys_syncfs(int fd);
__int64 sys_sysctl(struct __sysctl_args *args);
__int64 sys_sysfs(int option, unsigned __int64 arg1, unsigned __int64 arg2);
__int64 sys_sysinfo(struct sysinfo *info);
__int64 sys_syslog(int type, char *buf, int len);
__int64 sys_tee(int fdin, int fdout, size_t len, unsigned int flags);
__int64 sys_tgkill(pid_t tgid, pid_t pid, int sig);
__int64 sys_time(time_t *tloc);
__int64 sys_timer_create(clockid_t which_clock, struct sigevent *timer_event_spec, timer_t *created_timer_id);
__int64 sys_timer_delete(timer_t timer_id);
__int64 sys_timer_getoverrun(timer_t timer_id);
__int64 sys_timer_gettime(timer_t timer_id, struct itimerspec *setting);
__int64 sys_timer_settime(timer_t timer_id, int flags, const struct itimerspec *new_setting, struct itimerspec *old_setting);
__int64 sys_timerfd_create(int clockid, int flags);
__int64 sys_timerfd_gettime(int ufd, struct itimerspec *otmr);
__int64 sys_timerfd_settime(int ufd, int flags, const struct itimerspec *utmr, struct itimerspec *otmr);
__int64 sys_times(struct tms *tbuf);
__int64 sys_tkill(pid_t pid, int sig);
__int64 sys_truncate(const char *path, __int64 length);
__int64 sys_umask(int mask);
__int64 sys_umount(char *name, int flags);
__int64 sys_uname(struct old_utsname *);
__int64 sys_unlink(const char *pathname);
__int64 sys_unlinkat(int dfd, const char *pathname, int flag);
__int64 sys_unshare(unsigned __int64 unshare_flags);
__int64 sys_uselib(const char *library);
__int64 sys_userfaultfd(int flags);
__int64 sys_ustat(unsigned int dev, struct ustat *ubuf);
__int64 sys_utime(char *filename, struct utimbuf *times);
__int64 sys_utimensat(int dfd, const char *filename, struct timespec *utimes, int flags);
__int64 sys_utimes(char *filename, struct timeval *utimes);
__int64 sys_vfork(void);
__int64 sys_vhangup(void);
__int64 sys_vmsplice(int fd, const struct iovec *iov, unsigned __int64 nr_segs, unsigned int flags);
__int64 sys_wait4(pid_t pid, int *stat_addr, int options, struct rusage *ru);
__int64 sys_waitid(int which, pid_t pid, struct siginfo *infop, int options, struct rusage *ru);
__int64 sys_waitpid(pid_t pid, int *stat_addr, int options);
__int64 sys_write(unsigned int fd, const char *buf, size_t count);
__int64 sys_writev(unsigned __int64 fd, const struct iovec *vec, unsigned __int64 vlen);
