enum MACRO_SYS {SYS_restart_syscall = 0,SYS_exit = 1,SYS_fork = 2,SYS_read = 3,SYS_write = 4,SYS_open = 5,SYS_close = 6,SYS_waitpid = 7,SYS_creat = 8,SYS_link = 9,SYS_unlink = 10,SYS_execve = 11,SYS_chdir = 12,SYS_time = 13,SYS_mknod = 14,SYS_chmod = 15,SYS_lchown = 16,SYS_break = 17,SYS_oldstat = 18,SYS_lseek = 19,SYS_getpid = 20,SYS_mount = 21,SYS_umount = 22,SYS_setuid = 23,SYS_getuid = 24,SYS_stime = 25,SYS_ptrace = 26,SYS_alarm = 27,SYS_oldfstat = 28,SYS_pause = 29,SYS_utime = 30,SYS_stty = 31,SYS_gtty = 32,SYS_access = 33,SYS_nice = 34,SYS_ftime = 35,SYS_sync = 36,SYS_kill = 37,SYS_rename = 38,SYS_mkdir = 39,SYS_rmdir = 40,SYS_dup = 41,SYS_pipe = 42,SYS_times = 43,SYS_prof = 44,SYS_brk = 45,SYS_setgid = 46,SYS_getgid = 47,SYS_signal = 48,SYS_geteuid = 49,SYS_getegid = 50,SYS_acct = 51,SYS_umount2 = 52,SYS_lock = 53,SYS_ioctl = 54,SYS_fcntl = 55,SYS_mpx = 56,SYS_setpgid = 57,SYS_ulimit = 58,SYS_oldolduname = 59,SYS_umask = 60,SYS_chroot = 61,SYS_ustat = 62,SYS_dup2 = 63,SYS_getppid = 64,SYS_getpgrp = 65,SYS_setsid = 66,SYS_sigaction = 67,SYS_sgetmask = 68,SYS_ssetmask = 69,SYS_setreuid = 70,SYS_setregid = 71,SYS_sigsuspend = 72,SYS_sigpending = 73,SYS_sethostname = 74,SYS_setrlimit = 75,SYS_getrlimit = 76,SYS_getrusage = 77,SYS_gettimeofday = 78,SYS_settimeofday = 79,SYS_getgroups = 80,SYS_setgroups = 81,SYS_select = 82,SYS_symlink = 83,SYS_oldlstat = 84,SYS_readlink = 85,SYS_uselib = 86,SYS_swapon = 87,SYS_reboot = 88,SYS_readdir = 89,SYS_mmap = 90,SYS_munmap = 91,SYS_truncate = 92,SYS_ftruncate = 93,SYS_fchmod = 94,SYS_fchown = 95,SYS_getpriority = 96,SYS_setpriority = 97,SYS_profil = 98,SYS_statfs = 99,SYS_fstatfs = 100,SYS_ioperm = 101,SYS_socketcall = 102,SYS_syslog = 103,SYS_setitimer = 104,SYS_getitimer = 105,SYS_stat = 106,SYS_lstat = 107,SYS_fstat = 108,SYS_olduname = 109,SYS_iopl = 110,SYS_vhangup = 111,SYS_idle = 112,SYS_vm86old = 113,SYS_wait4 = 114,SYS_swapoff = 115,SYS_sysinfo = 116,SYS_ipc = 117,SYS_fsync = 118,SYS_sigreturn = 119,SYS_clone = 120,SYS_setdomainname = 121,SYS_uname = 122,SYS_modify_ldt = 123,SYS_adjtimex = 124,SYS_mprotect = 125,SYS_sigprocmask = 126,SYS_create_module = 127,SYS_init_module = 128,SYS_delete_module = 129,SYS_get_kernel_syms = 130,SYS_quotactl = 131,SYS_getpgid = 132,SYS_fchdir = 133,SYS_bdflush = 134,SYS_sysfs = 135,SYS_personality = 136,SYS_afs_syscall = 137,SYS_setfsuid = 138,SYS_setfsgid = 139,SYS__llseek = 140,SYS_getdents = 141,SYS__newselect = 142,SYS_flock = 143,SYS_msync = 144,SYS_readv = 145,SYS_writev = 146,SYS_getsid = 147,SYS_fdatasync = 148,SYS__sysctl = 149,SYS_mlock = 150,SYS_munlock = 151,SYS_mlockall = 152,SYS_munlockall = 153,SYS_sched_setparam = 154,SYS_sched_getparam = 155,SYS_sched_setscheduler = 156,SYS_sched_getscheduler = 157,SYS_sched_yield = 158,SYS_sched_get_priority_max = 159,SYS_sched_get_priority_min = 160,SYS_sched_rr_get_interval = 161,SYS_nanosleep = 162,SYS_mremap = 163,SYS_setresuid = 164,SYS_getresuid = 165,SYS_vm86 = 166,SYS_query_module = 167,SYS_poll = 168,SYS_nfsservctl = 169,SYS_setresgid = 170,SYS_getresgid = 171,SYS_prctl = 172,SYS_rt_sigreturn = 173,SYS_rt_sigaction = 174,SYS_rt_sigprocmask = 175,SYS_rt_sigpending = 176,SYS_rt_sigtimedwait = 177,SYS_rt_sigqueueinfo = 178,SYS_rt_sigsuspend = 179,SYS_pread64 = 180,SYS_pwrite64 = 181,SYS_chown = 182,SYS_getcwd = 183,SYS_capget = 184,SYS_capset = 185,SYS_sigaltstack = 186,SYS_sendfile = 187,SYS_getpmsg = 188,SYS_putpmsg = 189,SYS_vfork = 190,SYS_ugetrlimit = 191,SYS_mmap2 = 192,SYS_truncate64 = 193,SYS_ftruncate64 = 194,SYS_stat64 = 195,SYS_lstat64 = 196,SYS_fstat64 = 197,SYS_lchown32 = 198,SYS_getuid32 = 199,SYS_getgid32 = 200,SYS_geteuid32 = 201,SYS_getegid32 = 202,SYS_setreuid32 = 203,SYS_setregid32 = 204,SYS_getgroups32 = 205,SYS_setgroups32 = 206,SYS_fchown32 = 207,SYS_setresuid32 = 208,SYS_getresuid32 = 209,SYS_setresgid32 = 210,SYS_getresgid32 = 211,SYS_chown32 = 212,SYS_setuid32 = 213,SYS_setgid32 = 214,SYS_setfsuid32 = 215,SYS_setfsgid32 = 216,SYS_pivot_root = 217,SYS_mincore = 218,SYS_madvise = 219,SYS_madvise1 = 219,SYS_getdents64 = 220,SYS_fcntl64 = 221,SYS_gettid = 224,SYS_readahead = 225,SYS_setxattr = 226,SYS_lsetxattr = 227,SYS_fsetxattr = 228,SYS_getxattr = 229,SYS_lgetxattr = 230,SYS_fgetxattr = 231,SYS_listxattr = 232,SYS_llistxattr = 233,SYS_flistxattr = 234,SYS_removexattr = 235,SYS_lremovexattr = 236,SYS_fremovexattr = 237,SYS_tkill = 238,SYS_sendfile64 = 239,SYS_futex = 240,SYS_sched_setaffinity = 241,SYS_sched_getaffinity = 242,SYS_set_thread_area = 243,SYS_get_thread_area = 244,SYS_io_setup = 245,SYS_io_destroy = 246,SYS_io_getevents = 247,SYS_io_submit = 248,SYS_io_cancel = 249,SYS_fadvise64 = 250,SYS_exit_group = 252,SYS_lookup_dcookie = 253,SYS_epoll_create = 254,SYS_epoll_ctl = 255,SYS_epoll_wait = 256,SYS_remap_file_pages = 257,SYS_set_tid_address = 258,SYS_timer_create = 259,SYS_timer_settime = 260,SYS_timer_gettime = 261,SYS_timer_getoverrun = 262,SYS_timer_delete = 263,SYS_clock_settime = 264,SYS_clock_gettime = 265,SYS_clock_getres = 266,SYS_clock_nanosleep = 267,SYS_statfs64 = 268,SYS_fstatfs64 = 269,SYS_tgkill = 270,SYS_utimes = 271,SYS_fadvise64_64 = 272,SYS_vserver = 273,SYS_mbind = 274,SYS_get_mempolicy = 275,SYS_set_mempolicy = 276,SYS_mq_open = 277,SYS_mq_unlink = 278,SYS_mq_timedsend = 279,SYS_mq_timedreceive = 280,SYS_mq_notify = 281,SYS_mq_getsetattr = 282,SYS_kexec_load = 283,SYS_waitid = 284,SYS_add_key = 286,SYS_request_key = 287,SYS_keyctl = 288,SYS_ioprio_set = 289,SYS_ioprio_get = 290,SYS_inotify_init = 291,SYS_inotify_add_watch = 292,SYS_inotify_rm_watch = 293,SYS_migrate_pages = 294,SYS_openat = 295,SYS_mkdirat = 296,SYS_mknodat = 297,SYS_fchownat = 298,SYS_futimesat = 299,SYS_fstatat64 = 300,SYS_unlinkat = 301,SYS_renameat = 302,SYS_linkat = 303,SYS_symlinkat = 304,SYS_readlinkat = 305,SYS_fchmodat = 306,SYS_faccessat = 307,SYS_pselect6 = 308,SYS_ppoll = 309,SYS_unshare = 310,SYS_set_robust_list = 311,SYS_get_robust_list = 312,SYS_splice = 313,SYS_sync_file_range = 314,SYS_tee = 315,SYS_vmsplice = 316,SYS_move_pages = 317,SYS_getcpu = 318,SYS_epoll_pwait = 319,SYS_utimensat = 320,SYS_signalfd = 321,SYS_timerfd_create = 322,SYS_eventfd = 323,SYS_fallocate = 324,SYS_timerfd_settime = 325,SYS_timerfd_gettime = 326,SYS_signalfd4 = 327,SYS_eventfd2 = 328,SYS_epoll_create1 = 329,SYS_dup3 = 330,SYS_pipe2 = 331,SYS_inotify_init1 = 332,SYS_preadv = 333,SYS_pwritev = 334,SYS_rt_tgsigqueueinfo = 335,SYS_perf_event_open = 336,SYS_recvmmsg = 337,SYS_fanotify_init = 338,SYS_fanotify_mark = 339,SYS_prlimit64 = 340,SYS_name_to_handle_at = 341,SYS_open_by_handle_at = 342,SYS_clock_adjtime = 343,SYS_syncfs = 344,SYS_sendmmsg = 345,SYS_setns = 346,SYS_process_vm_readv = 347,SYS_process_vm_writev = 348,SYS_kcmp = 349,SYS_finit_module = 350,SYS_sched_setattr = 351,SYS_sched_getattr = 352,SYS_renameat2 = 353,SYS_seccomp = 354,SYS_getrandom = 355,SYS_memfd_create = 356,SYS_bpf = 357,SYS_execveat = 358,SYS_socket = 359,SYS_socketpair = 360,SYS_bind = 361,SYS_connect = 362,SYS_listen = 363,SYS_accept4 = 364,SYS_getsockopt = 365,SYS_setsockopt = 366,SYS_getsockname = 367,SYS_getpeername = 368,SYS_sendto = 369,SYS_sendmsg = 370,SYS_recvfrom = 371,SYS_recvmsg = 372,SYS_shutdown = 373,SYS_userfaultfd = 374,SYS_membarrier = 375,SYS_mlock2 = 376,SYS_copy_file_range = 377,SYS_preadv2 = 378,SYS_pwritev2 = 379,};
enum MACRO___NR {__NR_restart_syscall = 0,__NR_exit = 1,__NR_fork = 2,__NR_read = 3,__NR_write = 4,__NR_open = 5,__NR_close = 6,__NR_waitpid = 7,__NR_creat = 8,__NR_link = 9,__NR_unlink = 10,__NR_execve = 11,__NR_chdir = 12,__NR_time = 13,__NR_mknod = 14,__NR_chmod = 15,__NR_lchown = 16,__NR_break = 17,__NR_oldstat = 18,__NR_lseek = 19,__NR_getpid = 20,__NR_mount = 21,__NR_umount = 22,__NR_setuid = 23,__NR_getuid = 24,__NR_stime = 25,__NR_ptrace = 26,__NR_alarm = 27,__NR_oldfstat = 28,__NR_pause = 29,__NR_utime = 30,__NR_stty = 31,__NR_gtty = 32,__NR_access = 33,__NR_nice = 34,__NR_ftime = 35,__NR_sync = 36,__NR_kill = 37,__NR_rename = 38,__NR_mkdir = 39,__NR_rmdir = 40,__NR_dup = 41,__NR_pipe = 42,__NR_times = 43,__NR_prof = 44,__NR_brk = 45,__NR_setgid = 46,__NR_getgid = 47,__NR_signal = 48,__NR_geteuid = 49,__NR_getegid = 50,__NR_acct = 51,__NR_umount2 = 52,__NR_lock = 53,__NR_ioctl = 54,__NR_fcntl = 55,__NR_mpx = 56,__NR_setpgid = 57,__NR_ulimit = 58,__NR_oldolduname = 59,__NR_umask = 60,__NR_chroot = 61,__NR_ustat = 62,__NR_dup2 = 63,__NR_getppid = 64,__NR_getpgrp = 65,__NR_setsid = 66,__NR_sigaction = 67,__NR_sgetmask = 68,__NR_ssetmask = 69,__NR_setreuid = 70,__NR_setregid = 71,__NR_sigsuspend = 72,__NR_sigpending = 73,__NR_sethostname = 74,__NR_setrlimit = 75,__NR_getrlimit = 76,__NR_getrusage = 77,__NR_gettimeofday = 78,__NR_settimeofday = 79,__NR_getgroups = 80,__NR_setgroups = 81,__NR_select = 82,__NR_symlink = 83,__NR_oldlstat = 84,__NR_readlink = 85,__NR_uselib = 86,__NR_swapon = 87,__NR_reboot = 88,__NR_readdir = 89,__NR_mmap = 90,__NR_munmap = 91,__NR_truncate = 92,__NR_ftruncate = 93,__NR_fchmod = 94,__NR_fchown = 95,__NR_getpriority = 96,__NR_setpriority = 97,__NR_profil = 98,__NR_statfs = 99,__NR_fstatfs = 100,__NR_ioperm = 101,__NR_socketcall = 102,__NR_syslog = 103,__NR_setitimer = 104,__NR_getitimer = 105,__NR_stat = 106,__NR_lstat = 107,__NR_fstat = 108,__NR_olduname = 109,__NR_iopl = 110,__NR_vhangup = 111,__NR_idle = 112,__NR_vm86old = 113,__NR_wait4 = 114,__NR_swapoff = 115,__NR_sysinfo = 116,__NR_ipc = 117,__NR_fsync = 118,__NR_sigreturn = 119,__NR_clone = 120,__NR_setdomainname = 121,__NR_uname = 122,__NR_modify_ldt = 123,__NR_adjtimex = 124,__NR_mprotect = 125,__NR_sigprocmask = 126,__NR_create_module = 127,__NR_init_module = 128,__NR_delete_module = 129,__NR_get_kernel_syms = 130,__NR_quotactl = 131,__NR_getpgid = 132,__NR_fchdir = 133,__NR_bdflush = 134,__NR_sysfs = 135,__NR_personality = 136,__NR_afs_syscall = 137,__NR_setfsuid = 138,__NR_setfsgid = 139,__NR__llseek = 140,__NR_getdents = 141,__NR__newselect = 142,__NR_flock = 143,__NR_msync = 144,__NR_readv = 145,__NR_writev = 146,__NR_getsid = 147,__NR_fdatasync = 148,__NR__sysctl = 149,__NR_mlock = 150,__NR_munlock = 151,__NR_mlockall = 152,__NR_munlockall = 153,__NR_sched_setparam = 154,__NR_sched_getparam = 155,__NR_sched_setscheduler = 156,__NR_sched_getscheduler = 157,__NR_sched_yield = 158,__NR_sched_get_priority_max = 159,__NR_sched_get_priority_min = 160,__NR_sched_rr_get_interval = 161,__NR_nanosleep = 162,__NR_mremap = 163,__NR_setresuid = 164,__NR_getresuid = 165,__NR_vm86 = 166,__NR_query_module = 167,__NR_poll = 168,__NR_nfsservctl = 169,__NR_setresgid = 170,__NR_getresgid = 171,__NR_prctl = 172,__NR_rt_sigreturn = 173,__NR_rt_sigaction = 174,__NR_rt_sigprocmask = 175,__NR_rt_sigpending = 176,__NR_rt_sigtimedwait = 177,__NR_rt_sigqueueinfo = 178,__NR_rt_sigsuspend = 179,__NR_pread64 = 180,__NR_pwrite64 = 181,__NR_chown = 182,__NR_getcwd = 183,__NR_capget = 184,__NR_capset = 185,__NR_sigaltstack = 186,__NR_sendfile = 187,__NR_getpmsg = 188,__NR_putpmsg = 189,__NR_vfork = 190,__NR_ugetrlimit = 191,__NR_mmap2 = 192,__NR_truncate64 = 193,__NR_ftruncate64 = 194,__NR_stat64 = 195,__NR_lstat64 = 196,__NR_fstat64 = 197,__NR_lchown32 = 198,__NR_getuid32 = 199,__NR_getgid32 = 200,__NR_geteuid32 = 201,__NR_getegid32 = 202,__NR_setreuid32 = 203,__NR_setregid32 = 204,__NR_getgroups32 = 205,__NR_setgroups32 = 206,__NR_fchown32 = 207,__NR_setresuid32 = 208,__NR_getresuid32 = 209,__NR_setresgid32 = 210,__NR_getresgid32 = 211,__NR_chown32 = 212,__NR_setuid32 = 213,__NR_setgid32 = 214,__NR_setfsuid32 = 215,__NR_setfsgid32 = 216,__NR_pivot_root = 217,__NR_mincore = 218,__NR_madvise = 219,__NR_madvise1 = 219,__NR_getdents64 = 220,__NR_fcntl64 = 221,__NR_gettid = 224,__NR_readahead = 225,__NR_setxattr = 226,__NR_lsetxattr = 227,__NR_fsetxattr = 228,__NR_getxattr = 229,__NR_lgetxattr = 230,__NR_fgetxattr = 231,__NR_listxattr = 232,__NR_llistxattr = 233,__NR_flistxattr = 234,__NR_removexattr = 235,__NR_lremovexattr = 236,__NR_fremovexattr = 237,__NR_tkill = 238,__NR_sendfile64 = 239,__NR_futex = 240,__NR_sched_setaffinity = 241,__NR_sched_getaffinity = 242,__NR_set_thread_area = 243,__NR_get_thread_area = 244,__NR_io_setup = 245,__NR_io_destroy = 246,__NR_io_getevents = 247,__NR_io_submit = 248,__NR_io_cancel = 249,__NR_fadvise64 = 250,__NR_exit_group = 252,__NR_lookup_dcookie = 253,__NR_epoll_create = 254,__NR_epoll_ctl = 255,__NR_epoll_wait = 256,__NR_remap_file_pages = 257,__NR_set_tid_address = 258,__NR_timer_create = 259,__NR_timer_settime = 260,__NR_timer_gettime = 261,__NR_timer_getoverrun = 262,__NR_timer_delete = 263,__NR_clock_settime = 264,__NR_clock_gettime = 265,__NR_clock_getres = 266,__NR_clock_nanosleep = 267,__NR_statfs64 = 268,__NR_fstatfs64 = 269,__NR_tgkill = 270,__NR_utimes = 271,__NR_fadvise64_64 = 272,__NR_vserver = 273,__NR_mbind = 274,__NR_get_mempolicy = 275,__NR_set_mempolicy = 276,__NR_mq_open = 277,__NR_mq_unlink = 278,__NR_mq_timedsend = 279,__NR_mq_timedreceive = 280,__NR_mq_notify = 281,__NR_mq_getsetattr = 282,__NR_kexec_load = 283,__NR_waitid = 284,__NR_add_key = 286,__NR_request_key = 287,__NR_keyctl = 288,__NR_ioprio_set = 289,__NR_ioprio_get = 290,__NR_inotify_init = 291,__NR_inotify_add_watch = 292,__NR_inotify_rm_watch = 293,__NR_migrate_pages = 294,__NR_openat = 295,__NR_mkdirat = 296,__NR_mknodat = 297,__NR_fchownat = 298,__NR_futimesat = 299,__NR_fstatat64 = 300,__NR_unlinkat = 301,__NR_renameat = 302,__NR_linkat = 303,__NR_symlinkat = 304,__NR_readlinkat = 305,__NR_fchmodat = 306,__NR_faccessat = 307,__NR_pselect6 = 308,__NR_ppoll = 309,__NR_unshare = 310,__NR_set_robust_list = 311,__NR_get_robust_list = 312,__NR_splice = 313,__NR_sync_file_range = 314,__NR_tee = 315,__NR_vmsplice = 316,__NR_move_pages = 317,__NR_getcpu = 318,__NR_epoll_pwait = 319,__NR_utimensat = 320,__NR_signalfd = 321,__NR_timerfd_create = 322,__NR_eventfd = 323,__NR_fallocate = 324,__NR_timerfd_settime = 325,__NR_timerfd_gettime = 326,__NR_signalfd4 = 327,__NR_eventfd2 = 328,__NR_epoll_create1 = 329,__NR_dup3 = 330,__NR_pipe2 = 331,__NR_inotify_init1 = 332,__NR_preadv = 333,__NR_pwritev = 334,__NR_rt_tgsigqueueinfo = 335,__NR_perf_event_open = 336,__NR_recvmmsg = 337,__NR_fanotify_init = 338,__NR_fanotify_mark = 339,__NR_prlimit64 = 340,__NR_name_to_handle_at = 341,__NR_open_by_handle_at = 342,__NR_clock_adjtime = 343,__NR_syncfs = 344,__NR_sendmmsg = 345,__NR_setns = 346,__NR_process_vm_readv = 347,__NR_process_vm_writev = 348,__NR_kcmp = 349,__NR_finit_module = 350,__NR_sched_setattr = 351,__NR_sched_getattr = 352,__NR_renameat2 = 353,__NR_seccomp = 354,__NR_getrandom = 355,__NR_memfd_create = 356,__NR_bpf = 357,__NR_execveat = 358,__NR_socket = 359,__NR_socketpair = 360,__NR_bind = 361,__NR_connect = 362,__NR_listen = 363,__NR_accept4 = 364,__NR_getsockopt = 365,__NR_setsockopt = 366,__NR_getsockname = 367,__NR_getpeername = 368,__NR_sendto = 369,__NR_sendmsg = 370,__NR_recvfrom = 371,__NR_recvmsg = 372,__NR_shutdown = 373,__NR_userfaultfd = 374,__NR_membarrier = 375,__NR_mlock2 = 376,__NR_copy_file_range = 377,__NR_preadv2 = 378,__NR_pwritev2 = 379,};
typedef unsigned int __kernel_ulong_t;
struct __old_kernel_stat;
struct __user_cap_data_struct {__u32 effective;__u32 permitted;__u32 inheritable;};
struct __user_cap_header_struct {__u32 version;int pid;};
typedef __kernel_ulong_t aio_context_t;
union bpf_attr;
typedef struct __user_cap_data_struct *cap_user_data_t;
typedef struct __user_cap_header_struct *cap_user_header_t;
struct compat_stat;
struct compat_timeval;
struct file_handle;
struct getcpu_cache;
struct iattr;
struct inode;
struct io_event;
struct iocb;
struct kexec_segment;
typedef int32_t key_serial_t;
struct linux_dirent;
struct linux_dirent64;
struct list_head;
struct mmap_arg_struct;
struct mmsghdr;
struct msgbuf;
struct new_utsname;
struct nfsctl_arg;
struct old_linux_dirent;
typedef unsigned int old_sigset_t;
struct old_utsname;
struct oldold_utsname;
struct perf_event_attr;
typedef __kernel_uid32_t qid_t;
struct rlimit64;
struct robust_list_head;
struct sched_attr;
struct sel_arg_struct;
struct semaphore;
struct stat64;
struct statfs64;
typedef unsigned int u32;
typedef unsigned __int64 u64;
struct user_msghdr;

MACRO_SYS SYS__llseek;
MACRO_SYS SYS__newselect;
MACRO_SYS SYS__sysctl;
MACRO_SYS SYS_accept4;
MACRO_SYS SYS_access;
MACRO_SYS SYS_acct;
MACRO_SYS SYS_add_key;
MACRO_SYS SYS_adjtimex;
MACRO_SYS SYS_afs_syscall;
MACRO_SYS SYS_alarm;
MACRO_SYS SYS_bdflush;
MACRO_SYS SYS_bind;
MACRO_SYS SYS_bpf;
MACRO_SYS SYS_break;
MACRO_SYS SYS_brk;
MACRO_SYS SYS_capget;
MACRO_SYS SYS_capset;
MACRO_SYS SYS_chdir;
MACRO_SYS SYS_chmod;
MACRO_SYS SYS_chown;
MACRO_SYS SYS_chown32;
MACRO_SYS SYS_chroot;
MACRO_SYS SYS_clock_adjtime;
MACRO_SYS SYS_clock_getres;
MACRO_SYS SYS_clock_gettime;
MACRO_SYS SYS_clock_nanosleep;
MACRO_SYS SYS_clock_settime;
MACRO_SYS SYS_clone;
MACRO_SYS SYS_close;
MACRO_SYS SYS_connect;
MACRO_SYS SYS_copy_file_range;
MACRO_SYS SYS_creat;
MACRO_SYS SYS_create_module;
MACRO_SYS SYS_delete_module;
MACRO_SYS SYS_dup;
MACRO_SYS SYS_dup2;
MACRO_SYS SYS_dup3;
MACRO_SYS SYS_epoll_create;
MACRO_SYS SYS_epoll_create1;
MACRO_SYS SYS_epoll_ctl;
MACRO_SYS SYS_epoll_pwait;
MACRO_SYS SYS_epoll_wait;
MACRO_SYS SYS_eventfd;
MACRO_SYS SYS_eventfd2;
MACRO_SYS SYS_execve;
MACRO_SYS SYS_execveat;
MACRO_SYS SYS_exit;
MACRO_SYS SYS_exit_group;
MACRO_SYS SYS_faccessat;
MACRO_SYS SYS_fadvise64;
MACRO_SYS SYS_fadvise64_64;
MACRO_SYS SYS_fallocate;
MACRO_SYS SYS_fanotify_init;
MACRO_SYS SYS_fanotify_mark;
MACRO_SYS SYS_fchdir;
MACRO_SYS SYS_fchmod;
MACRO_SYS SYS_fchmodat;
MACRO_SYS SYS_fchown;
MACRO_SYS SYS_fchown32;
MACRO_SYS SYS_fchownat;
MACRO_SYS SYS_fcntl;
MACRO_SYS SYS_fcntl64;
MACRO_SYS SYS_fdatasync;
MACRO_SYS SYS_fgetxattr;
MACRO_SYS SYS_finit_module;
MACRO_SYS SYS_flistxattr;
MACRO_SYS SYS_flock;
MACRO_SYS SYS_fork;
MACRO_SYS SYS_fremovexattr;
MACRO_SYS SYS_fsetxattr;
MACRO_SYS SYS_fstat;
MACRO_SYS SYS_fstat64;
MACRO_SYS SYS_fstatat64;
MACRO_SYS SYS_fstatfs;
MACRO_SYS SYS_fstatfs64;
MACRO_SYS SYS_fsync;
MACRO_SYS SYS_ftime;
MACRO_SYS SYS_ftruncate;
MACRO_SYS SYS_ftruncate64;
MACRO_SYS SYS_futex;
MACRO_SYS SYS_futimesat;
MACRO_SYS SYS_get_kernel_syms;
MACRO_SYS SYS_get_mempolicy;
MACRO_SYS SYS_get_robust_list;
MACRO_SYS SYS_get_thread_area;
MACRO_SYS SYS_getcpu;
MACRO_SYS SYS_getcwd;
MACRO_SYS SYS_getdents;
MACRO_SYS SYS_getdents64;
MACRO_SYS SYS_getegid;
MACRO_SYS SYS_getegid32;
MACRO_SYS SYS_geteuid;
MACRO_SYS SYS_geteuid32;
MACRO_SYS SYS_getgid;
MACRO_SYS SYS_getgid32;
MACRO_SYS SYS_getgroups;
MACRO_SYS SYS_getgroups32;
MACRO_SYS SYS_getitimer;
MACRO_SYS SYS_getpeername;
MACRO_SYS SYS_getpgid;
MACRO_SYS SYS_getpgrp;
MACRO_SYS SYS_getpid;
MACRO_SYS SYS_getpmsg;
MACRO_SYS SYS_getppid;
MACRO_SYS SYS_getpriority;
MACRO_SYS SYS_getrandom;
MACRO_SYS SYS_getresgid;
MACRO_SYS SYS_getresgid32;
MACRO_SYS SYS_getresuid;
MACRO_SYS SYS_getresuid32;
MACRO_SYS SYS_getrlimit;
MACRO_SYS SYS_getrusage;
MACRO_SYS SYS_getsid;
MACRO_SYS SYS_getsockname;
MACRO_SYS SYS_getsockopt;
MACRO_SYS SYS_gettid;
MACRO_SYS SYS_gettimeofday;
MACRO_SYS SYS_getuid;
MACRO_SYS SYS_getuid32;
MACRO_SYS SYS_getxattr;
MACRO_SYS SYS_gtty;
MACRO_SYS SYS_idle;
MACRO_SYS SYS_init_module;
MACRO_SYS SYS_inotify_add_watch;
MACRO_SYS SYS_inotify_init;
MACRO_SYS SYS_inotify_init1;
MACRO_SYS SYS_inotify_rm_watch;
MACRO_SYS SYS_io_cancel;
MACRO_SYS SYS_io_destroy;
MACRO_SYS SYS_io_getevents;
MACRO_SYS SYS_io_setup;
MACRO_SYS SYS_io_submit;
MACRO_SYS SYS_ioctl;
MACRO_SYS SYS_ioperm;
MACRO_SYS SYS_iopl;
MACRO_SYS SYS_ioprio_get;
MACRO_SYS SYS_ioprio_set;
MACRO_SYS SYS_ipc;
MACRO_SYS SYS_kcmp;
MACRO_SYS SYS_kexec_load;
MACRO_SYS SYS_keyctl;
MACRO_SYS SYS_kill;
MACRO_SYS SYS_lchown;
MACRO_SYS SYS_lchown32;
MACRO_SYS SYS_lgetxattr;
MACRO_SYS SYS_link;
MACRO_SYS SYS_linkat;
MACRO_SYS SYS_listen;
MACRO_SYS SYS_listxattr;
MACRO_SYS SYS_llistxattr;
MACRO_SYS SYS_lock;
MACRO_SYS SYS_lookup_dcookie;
MACRO_SYS SYS_lremovexattr;
MACRO_SYS SYS_lseek;
MACRO_SYS SYS_lsetxattr;
MACRO_SYS SYS_lstat;
MACRO_SYS SYS_lstat64;
MACRO_SYS SYS_madvise;
MACRO_SYS SYS_madvise1;
MACRO_SYS SYS_mbind;
MACRO_SYS SYS_membarrier;
MACRO_SYS SYS_memfd_create;
MACRO_SYS SYS_migrate_pages;
MACRO_SYS SYS_mincore;
MACRO_SYS SYS_mkdir;
MACRO_SYS SYS_mkdirat;
MACRO_SYS SYS_mknod;
MACRO_SYS SYS_mknodat;
MACRO_SYS SYS_mlock;
MACRO_SYS SYS_mlock2;
MACRO_SYS SYS_mlockall;
MACRO_SYS SYS_mmap;
MACRO_SYS SYS_mmap2;
MACRO_SYS SYS_modify_ldt;
MACRO_SYS SYS_mount;
MACRO_SYS SYS_move_pages;
MACRO_SYS SYS_mprotect;
MACRO_SYS SYS_mpx;
MACRO_SYS SYS_mq_getsetattr;
MACRO_SYS SYS_mq_notify;
MACRO_SYS SYS_mq_open;
MACRO_SYS SYS_mq_timedreceive;
MACRO_SYS SYS_mq_timedsend;
MACRO_SYS SYS_mq_unlink;
MACRO_SYS SYS_mremap;
MACRO_SYS SYS_msync;
MACRO_SYS SYS_munlock;
MACRO_SYS SYS_munlockall;
MACRO_SYS SYS_munmap;
MACRO_SYS SYS_name_to_handle_at;
MACRO_SYS SYS_nanosleep;
MACRO_SYS SYS_nfsservctl;
MACRO_SYS SYS_nice;
MACRO_SYS SYS_oldfstat;
MACRO_SYS SYS_oldlstat;
MACRO_SYS SYS_oldolduname;
MACRO_SYS SYS_oldstat;
MACRO_SYS SYS_olduname;
MACRO_SYS SYS_open;
MACRO_SYS SYS_open_by_handle_at;
MACRO_SYS SYS_openat;
MACRO_SYS SYS_pause;
MACRO_SYS SYS_perf_event_open;
MACRO_SYS SYS_personality;
MACRO_SYS SYS_pipe;
MACRO_SYS SYS_pipe2;
MACRO_SYS SYS_pivot_root;
MACRO_SYS SYS_poll;
MACRO_SYS SYS_ppoll;
MACRO_SYS SYS_prctl;
MACRO_SYS SYS_pread64;
MACRO_SYS SYS_preadv;
MACRO_SYS SYS_preadv2;
MACRO_SYS SYS_prlimit64;
MACRO_SYS SYS_process_vm_readv;
MACRO_SYS SYS_process_vm_writev;
MACRO_SYS SYS_prof;
MACRO_SYS SYS_profil;
MACRO_SYS SYS_pselect6;
MACRO_SYS SYS_ptrace;
MACRO_SYS SYS_putpmsg;
MACRO_SYS SYS_pwrite64;
MACRO_SYS SYS_pwritev;
MACRO_SYS SYS_pwritev2;
MACRO_SYS SYS_query_module;
MACRO_SYS SYS_quotactl;
MACRO_SYS SYS_read;
MACRO_SYS SYS_readahead;
MACRO_SYS SYS_readdir;
MACRO_SYS SYS_readlink;
MACRO_SYS SYS_readlinkat;
MACRO_SYS SYS_readv;
MACRO_SYS SYS_reboot;
MACRO_SYS SYS_recvfrom;
MACRO_SYS SYS_recvmmsg;
MACRO_SYS SYS_recvmsg;
MACRO_SYS SYS_remap_file_pages;
MACRO_SYS SYS_removexattr;
MACRO_SYS SYS_rename;
MACRO_SYS SYS_renameat;
MACRO_SYS SYS_renameat2;
MACRO_SYS SYS_request_key;
MACRO_SYS SYS_restart_syscall;
MACRO_SYS SYS_rmdir;
MACRO_SYS SYS_rt_sigaction;
MACRO_SYS SYS_rt_sigpending;
MACRO_SYS SYS_rt_sigprocmask;
MACRO_SYS SYS_rt_sigqueueinfo;
MACRO_SYS SYS_rt_sigreturn;
MACRO_SYS SYS_rt_sigsuspend;
MACRO_SYS SYS_rt_sigtimedwait;
MACRO_SYS SYS_rt_tgsigqueueinfo;
MACRO_SYS SYS_sched_get_priority_max;
MACRO_SYS SYS_sched_get_priority_min;
MACRO_SYS SYS_sched_getaffinity;
MACRO_SYS SYS_sched_getattr;
MACRO_SYS SYS_sched_getparam;
MACRO_SYS SYS_sched_getscheduler;
MACRO_SYS SYS_sched_rr_get_interval;
MACRO_SYS SYS_sched_setaffinity;
MACRO_SYS SYS_sched_setattr;
MACRO_SYS SYS_sched_setparam;
MACRO_SYS SYS_sched_setscheduler;
MACRO_SYS SYS_sched_yield;
MACRO_SYS SYS_seccomp;
MACRO_SYS SYS_select;
MACRO_SYS SYS_sendfile;
MACRO_SYS SYS_sendfile64;
MACRO_SYS SYS_sendmmsg;
MACRO_SYS SYS_sendmsg;
MACRO_SYS SYS_sendto;
MACRO_SYS SYS_set_mempolicy;
MACRO_SYS SYS_set_robust_list;
MACRO_SYS SYS_set_thread_area;
MACRO_SYS SYS_set_tid_address;
MACRO_SYS SYS_setdomainname;
MACRO_SYS SYS_setfsgid;
MACRO_SYS SYS_setfsgid32;
MACRO_SYS SYS_setfsuid;
MACRO_SYS SYS_setfsuid32;
MACRO_SYS SYS_setgid;
MACRO_SYS SYS_setgid32;
MACRO_SYS SYS_setgroups;
MACRO_SYS SYS_setgroups32;
MACRO_SYS SYS_sethostname;
MACRO_SYS SYS_setitimer;
MACRO_SYS SYS_setns;
MACRO_SYS SYS_setpgid;
MACRO_SYS SYS_setpriority;
MACRO_SYS SYS_setregid;
MACRO_SYS SYS_setregid32;
MACRO_SYS SYS_setresgid;
MACRO_SYS SYS_setresgid32;
MACRO_SYS SYS_setresuid;
MACRO_SYS SYS_setresuid32;
MACRO_SYS SYS_setreuid;
MACRO_SYS SYS_setreuid32;
MACRO_SYS SYS_setrlimit;
MACRO_SYS SYS_setsid;
MACRO_SYS SYS_setsockopt;
MACRO_SYS SYS_settimeofday;
MACRO_SYS SYS_setuid;
MACRO_SYS SYS_setuid32;
MACRO_SYS SYS_setxattr;
MACRO_SYS SYS_sgetmask;
MACRO_SYS SYS_shutdown;
MACRO_SYS SYS_sigaction;
MACRO_SYS SYS_sigaltstack;
MACRO_SYS SYS_signal;
MACRO_SYS SYS_signalfd;
MACRO_SYS SYS_signalfd4;
MACRO_SYS SYS_sigpending;
MACRO_SYS SYS_sigprocmask;
MACRO_SYS SYS_sigreturn;
MACRO_SYS SYS_sigsuspend;
MACRO_SYS SYS_socket;
MACRO_SYS SYS_socketcall;
MACRO_SYS SYS_socketpair;
MACRO_SYS SYS_splice;
MACRO_SYS SYS_ssetmask;
MACRO_SYS SYS_stat;
MACRO_SYS SYS_stat64;
MACRO_SYS SYS_statfs;
MACRO_SYS SYS_statfs64;
MACRO_SYS SYS_stime;
MACRO_SYS SYS_stty;
MACRO_SYS SYS_swapoff;
MACRO_SYS SYS_swapon;
MACRO_SYS SYS_symlink;
MACRO_SYS SYS_symlinkat;
MACRO_SYS SYS_sync;
MACRO_SYS SYS_sync_file_range;
MACRO_SYS SYS_syncfs;
MACRO_SYS SYS_sysfs;
MACRO_SYS SYS_sysinfo;
MACRO_SYS SYS_syslog;
MACRO_SYS SYS_tee;
MACRO_SYS SYS_tgkill;
MACRO_SYS SYS_time;
MACRO_SYS SYS_timer_create;
MACRO_SYS SYS_timer_delete;
MACRO_SYS SYS_timer_getoverrun;
MACRO_SYS SYS_timer_gettime;
MACRO_SYS SYS_timer_settime;
MACRO_SYS SYS_timerfd_create;
MACRO_SYS SYS_timerfd_gettime;
MACRO_SYS SYS_timerfd_settime;
MACRO_SYS SYS_times;
MACRO_SYS SYS_tkill;
MACRO_SYS SYS_truncate;
MACRO_SYS SYS_truncate64;
MACRO_SYS SYS_ugetrlimit;
MACRO_SYS SYS_ulimit;
MACRO_SYS SYS_umask;
MACRO_SYS SYS_umount;
MACRO_SYS SYS_umount2;
MACRO_SYS SYS_uname;
MACRO_SYS SYS_unlink;
MACRO_SYS SYS_unlinkat;
MACRO_SYS SYS_unshare;
MACRO_SYS SYS_uselib;
MACRO_SYS SYS_userfaultfd;
MACRO_SYS SYS_ustat;
MACRO_SYS SYS_utime;
MACRO_SYS SYS_utimensat;
MACRO_SYS SYS_utimes;
MACRO_SYS SYS_vfork;
MACRO_SYS SYS_vhangup;
MACRO_SYS SYS_vm86;
MACRO_SYS SYS_vm86old;
MACRO_SYS SYS_vmsplice;
MACRO_SYS SYS_vserver;
MACRO_SYS SYS_wait4;
MACRO_SYS SYS_waitid;
MACRO_SYS SYS_waitpid;
MACRO_SYS SYS_write;
MACRO_SYS SYS_writev;
MACRO___NR __NR__llseek;
MACRO___NR __NR__newselect;
MACRO___NR __NR__sysctl;
MACRO___NR __NR_accept4;
MACRO___NR __NR_access;
MACRO___NR __NR_acct;
MACRO___NR __NR_add_key;
MACRO___NR __NR_adjtimex;
MACRO___NR __NR_afs_syscall;
MACRO___NR __NR_alarm;
MACRO___NR __NR_bdflush;
MACRO___NR __NR_bind;
MACRO___NR __NR_bpf;
MACRO___NR __NR_break;
MACRO___NR __NR_brk;
MACRO___NR __NR_capget;
MACRO___NR __NR_capset;
MACRO___NR __NR_chdir;
MACRO___NR __NR_chmod;
MACRO___NR __NR_chown;
MACRO___NR __NR_chown32;
MACRO___NR __NR_chroot;
MACRO___NR __NR_clock_adjtime;
MACRO___NR __NR_clock_getres;
MACRO___NR __NR_clock_gettime;
MACRO___NR __NR_clock_nanosleep;
MACRO___NR __NR_clock_settime;
MACRO___NR __NR_clone;
MACRO___NR __NR_close;
MACRO___NR __NR_connect;
MACRO___NR __NR_copy_file_range;
MACRO___NR __NR_creat;
MACRO___NR __NR_create_module;
MACRO___NR __NR_delete_module;
MACRO___NR __NR_dup;
MACRO___NR __NR_dup2;
MACRO___NR __NR_dup3;
MACRO___NR __NR_epoll_create;
MACRO___NR __NR_epoll_create1;
MACRO___NR __NR_epoll_ctl;
MACRO___NR __NR_epoll_pwait;
MACRO___NR __NR_epoll_wait;
MACRO___NR __NR_eventfd;
MACRO___NR __NR_eventfd2;
MACRO___NR __NR_execve;
MACRO___NR __NR_execveat;
MACRO___NR __NR_exit;
MACRO___NR __NR_exit_group;
MACRO___NR __NR_faccessat;
MACRO___NR __NR_fadvise64;
MACRO___NR __NR_fadvise64_64;
MACRO___NR __NR_fallocate;
MACRO___NR __NR_fanotify_init;
MACRO___NR __NR_fanotify_mark;
MACRO___NR __NR_fchdir;
MACRO___NR __NR_fchmod;
MACRO___NR __NR_fchmodat;
MACRO___NR __NR_fchown;
MACRO___NR __NR_fchown32;
MACRO___NR __NR_fchownat;
MACRO___NR __NR_fcntl;
MACRO___NR __NR_fcntl64;
MACRO___NR __NR_fdatasync;
MACRO___NR __NR_fgetxattr;
MACRO___NR __NR_finit_module;
MACRO___NR __NR_flistxattr;
MACRO___NR __NR_flock;
MACRO___NR __NR_fork;
MACRO___NR __NR_fremovexattr;
MACRO___NR __NR_fsetxattr;
MACRO___NR __NR_fstat;
MACRO___NR __NR_fstat64;
MACRO___NR __NR_fstatat64;
MACRO___NR __NR_fstatfs;
MACRO___NR __NR_fstatfs64;
MACRO___NR __NR_fsync;
MACRO___NR __NR_ftime;
MACRO___NR __NR_ftruncate;
MACRO___NR __NR_ftruncate64;
MACRO___NR __NR_futex;
MACRO___NR __NR_futimesat;
MACRO___NR __NR_get_kernel_syms;
MACRO___NR __NR_get_mempolicy;
MACRO___NR __NR_get_robust_list;
MACRO___NR __NR_get_thread_area;
MACRO___NR __NR_getcpu;
MACRO___NR __NR_getcwd;
MACRO___NR __NR_getdents;
MACRO___NR __NR_getdents64;
MACRO___NR __NR_getegid;
MACRO___NR __NR_getegid32;
MACRO___NR __NR_geteuid;
MACRO___NR __NR_geteuid32;
MACRO___NR __NR_getgid;
MACRO___NR __NR_getgid32;
MACRO___NR __NR_getgroups;
MACRO___NR __NR_getgroups32;
MACRO___NR __NR_getitimer;
MACRO___NR __NR_getpeername;
MACRO___NR __NR_getpgid;
MACRO___NR __NR_getpgrp;
MACRO___NR __NR_getpid;
MACRO___NR __NR_getpmsg;
MACRO___NR __NR_getppid;
MACRO___NR __NR_getpriority;
MACRO___NR __NR_getrandom;
MACRO___NR __NR_getresgid;
MACRO___NR __NR_getresgid32;
MACRO___NR __NR_getresuid;
MACRO___NR __NR_getresuid32;
MACRO___NR __NR_getrlimit;
MACRO___NR __NR_getrusage;
MACRO___NR __NR_getsid;
MACRO___NR __NR_getsockname;
MACRO___NR __NR_getsockopt;
MACRO___NR __NR_gettid;
MACRO___NR __NR_gettimeofday;
MACRO___NR __NR_getuid;
MACRO___NR __NR_getuid32;
MACRO___NR __NR_getxattr;
MACRO___NR __NR_gtty;
MACRO___NR __NR_idle;
MACRO___NR __NR_init_module;
MACRO___NR __NR_inotify_add_watch;
MACRO___NR __NR_inotify_init;
MACRO___NR __NR_inotify_init1;
MACRO___NR __NR_inotify_rm_watch;
MACRO___NR __NR_io_cancel;
MACRO___NR __NR_io_destroy;
MACRO___NR __NR_io_getevents;
MACRO___NR __NR_io_setup;
MACRO___NR __NR_io_submit;
MACRO___NR __NR_ioctl;
MACRO___NR __NR_ioperm;
MACRO___NR __NR_iopl;
MACRO___NR __NR_ioprio_get;
MACRO___NR __NR_ioprio_set;
MACRO___NR __NR_ipc;
MACRO___NR __NR_kcmp;
MACRO___NR __NR_kexec_load;
MACRO___NR __NR_keyctl;
MACRO___NR __NR_kill;
MACRO___NR __NR_lchown;
MACRO___NR __NR_lchown32;
MACRO___NR __NR_lgetxattr;
MACRO___NR __NR_link;
MACRO___NR __NR_linkat;
MACRO___NR __NR_listen;
MACRO___NR __NR_listxattr;
MACRO___NR __NR_llistxattr;
MACRO___NR __NR_lock;
MACRO___NR __NR_lookup_dcookie;
MACRO___NR __NR_lremovexattr;
MACRO___NR __NR_lseek;
MACRO___NR __NR_lsetxattr;
MACRO___NR __NR_lstat;
MACRO___NR __NR_lstat64;
MACRO___NR __NR_madvise;
MACRO___NR __NR_madvise1;
MACRO___NR __NR_mbind;
MACRO___NR __NR_membarrier;
MACRO___NR __NR_memfd_create;
MACRO___NR __NR_migrate_pages;
MACRO___NR __NR_mincore;
MACRO___NR __NR_mkdir;
MACRO___NR __NR_mkdirat;
MACRO___NR __NR_mknod;
MACRO___NR __NR_mknodat;
MACRO___NR __NR_mlock;
MACRO___NR __NR_mlock2;
MACRO___NR __NR_mlockall;
MACRO___NR __NR_mmap;
MACRO___NR __NR_mmap2;
MACRO___NR __NR_modify_ldt;
MACRO___NR __NR_mount;
MACRO___NR __NR_move_pages;
MACRO___NR __NR_mprotect;
MACRO___NR __NR_mpx;
MACRO___NR __NR_mq_getsetattr;
MACRO___NR __NR_mq_notify;
MACRO___NR __NR_mq_open;
MACRO___NR __NR_mq_timedreceive;
MACRO___NR __NR_mq_timedsend;
MACRO___NR __NR_mq_unlink;
MACRO___NR __NR_mremap;
MACRO___NR __NR_msync;
MACRO___NR __NR_munlock;
MACRO___NR __NR_munlockall;
MACRO___NR __NR_munmap;
MACRO___NR __NR_name_to_handle_at;
MACRO___NR __NR_nanosleep;
MACRO___NR __NR_nfsservctl;
MACRO___NR __NR_nice;
MACRO___NR __NR_oldfstat;
MACRO___NR __NR_oldlstat;
MACRO___NR __NR_oldolduname;
MACRO___NR __NR_oldstat;
MACRO___NR __NR_olduname;
MACRO___NR __NR_open;
MACRO___NR __NR_open_by_handle_at;
MACRO___NR __NR_openat;
MACRO___NR __NR_pause;
MACRO___NR __NR_perf_event_open;
MACRO___NR __NR_personality;
MACRO___NR __NR_pipe;
MACRO___NR __NR_pipe2;
MACRO___NR __NR_pivot_root;
MACRO___NR __NR_poll;
MACRO___NR __NR_ppoll;
MACRO___NR __NR_prctl;
MACRO___NR __NR_pread64;
MACRO___NR __NR_preadv;
MACRO___NR __NR_preadv2;
MACRO___NR __NR_prlimit64;
MACRO___NR __NR_process_vm_readv;
MACRO___NR __NR_process_vm_writev;
MACRO___NR __NR_prof;
MACRO___NR __NR_profil;
MACRO___NR __NR_pselect6;
MACRO___NR __NR_ptrace;
MACRO___NR __NR_putpmsg;
MACRO___NR __NR_pwrite64;
MACRO___NR __NR_pwritev;
MACRO___NR __NR_pwritev2;
MACRO___NR __NR_query_module;
MACRO___NR __NR_quotactl;
MACRO___NR __NR_read;
MACRO___NR __NR_readahead;
MACRO___NR __NR_readdir;
MACRO___NR __NR_readlink;
MACRO___NR __NR_readlinkat;
MACRO___NR __NR_readv;
MACRO___NR __NR_reboot;
MACRO___NR __NR_recvfrom;
MACRO___NR __NR_recvmmsg;
MACRO___NR __NR_recvmsg;
MACRO___NR __NR_remap_file_pages;
MACRO___NR __NR_removexattr;
MACRO___NR __NR_rename;
MACRO___NR __NR_renameat;
MACRO___NR __NR_renameat2;
MACRO___NR __NR_request_key;
MACRO___NR _NR_restart_syscall;
MACRO___NR __NR_rmdir;
MACRO___NR __NR_rt_sigaction;
MACRO___NR __NR_rt_sigpending;
MACRO___NR __NR_rt_sigprocmask;
MACRO___NR __NR_rt_sigqueueinfo;
MACRO___NR __NR_rt_sigreturn;
MACRO___NR __NR_rt_sigsuspend;
MACRO___NR __NR_rt_sigtimedwait;
MACRO___NR __NR_rt_tgsigqueueinfo;
MACRO___NR __NR_sched_get_priority_max;
MACRO___NR __NR_sched_get_priority_min;
MACRO___NR __NR_sched_getaffinity;
MACRO___NR __NR_sched_getattr;
MACRO___NR __NR_sched_getparam;
MACRO___NR __NR_sched_getscheduler;
MACRO___NR __NR_sched_rr_get_interval;
MACRO___NR __NR_sched_setaffinity;
MACRO___NR __NR_sched_setattr;
MACRO___NR __NR_sched_setparam;
MACRO___NR __NR_sched_setscheduler;
MACRO___NR __NR_sched_yield;
MACRO___NR __NR_seccomp;
MACRO___NR __NR_select;
MACRO___NR __NR_sendfile;
MACRO___NR __NR_sendfile64;
MACRO___NR __NR_sendmmsg;
MACRO___NR __NR_sendmsg;
MACRO___NR __NR_sendto;
MACRO___NR __NR_set_mempolicy;
MACRO___NR __NR_set_robust_list;
MACRO___NR __NR_set_thread_area;
MACRO___NR __NR_set_tid_address;
MACRO___NR __NR_setdomainname;
MACRO___NR __NR_setfsgid;
MACRO___NR __NR_setfsgid32;
MACRO___NR __NR_setfsuid;
MACRO___NR __NR_setfsuid32;
MACRO___NR __NR_setgid;
MACRO___NR __NR_setgid32;
MACRO___NR __NR_setgroups;
MACRO___NR __NR_setgroups32;
MACRO___NR __NR_sethostname;
MACRO___NR __NR_setitimer;
MACRO___NR __NR_setns;
MACRO___NR __NR_setpgid;
MACRO___NR __NR_setpriority;
MACRO___NR __NR_setregid;
MACRO___NR __NR_setregid32;
MACRO___NR __NR_setresgid;
MACRO___NR __NR_setresgid32;
MACRO___NR __NR_setresuid;
MACRO___NR __NR_setresuid32;
MACRO___NR __NR_setreuid;
MACRO___NR __NR_setreuid32;
MACRO___NR __NR_setrlimit;
MACRO___NR __NR_setsid;
MACRO___NR __NR_setsockopt;
MACRO___NR __NR_settimeofday;
MACRO___NR __NR_setuid;
MACRO___NR __NR_setuid32;
MACRO___NR __NR_setxattr;
MACRO___NR __NR_sgetmask;
MACRO___NR __NR_shutdown;
MACRO___NR __NR_sigaction;
MACRO___NR __NR_sigaltstack;
MACRO___NR __NR_signal;
MACRO___NR __NR_signalfd;
MACRO___NR __NR_signalfd4;
MACRO___NR __NR_sigpending;
MACRO___NR __NR_sigprocmask;
MACRO___NR __NR_sigreturn;
MACRO___NR __NR_sigsuspend;
MACRO___NR __NR_socket;
MACRO___NR __NR_socketcall;
MACRO___NR __NR_socketpair;
MACRO___NR __NR_splice;
MACRO___NR __NR_ssetmask;
MACRO___NR __NR_stat;
MACRO___NR __NR_stat64;
MACRO___NR __NR_statfs;
MACRO___NR __NR_statfs64;
MACRO___NR __NR_stime;
MACRO___NR __NR_stty;
MACRO___NR __NR_swapoff;
MACRO___NR __NR_swapon;
MACRO___NR __NR_symlink;
MACRO___NR __NR_symlinkat;
MACRO___NR __NR_sync;
MACRO___NR __NR_sync_file_range;
MACRO___NR __NR_syncfs;
MACRO___NR __NR_sysfs;
MACRO___NR __NR_sysinfo;
MACRO___NR __NR_syslog;
MACRO___NR __NR_tee;
MACRO___NR __NR_tgkill;
MACRO___NR __NR_time;
MACRO___NR __NR_timer_create;
MACRO___NR __NR_timer_delete;
MACRO___NR __NR_timer_getoverrun;
MACRO___NR __NR_timer_gettime;
MACRO___NR __NR_timer_settime;
MACRO___NR __NR_timerfd_create;
MACRO___NR __NR_timerfd_gettime;
MACRO___NR __NR_timerfd_settime;
MACRO___NR __NR_times;
MACRO___NR __NR_tkill;
MACRO___NR __NR_truncate;
MACRO___NR __NR_truncate64;
MACRO___NR __NR_ugetrlimit;
MACRO___NR __NR_ulimit;
MACRO___NR __NR_umask;
MACRO___NR __NR_umount;
MACRO___NR __NR_umount2;
MACRO___NR __NR_uname;
MACRO___NR __NR_unlink;
MACRO___NR __NR_unlinkat;
MACRO___NR __NR_unshare;
MACRO___NR __NR_uselib;
MACRO___NR __NR_userfaultfd;
MACRO___NR __NR_ustat;
MACRO___NR __NR_utime;
MACRO___NR __NR_utimensat;
MACRO___NR __NR_utimes;
MACRO___NR __NR_vfork;
MACRO___NR __NR_vhangup;
MACRO___NR __NR_vm86;
MACRO___NR __NR_vm86old;
MACRO___NR __NR_vmsplice;
MACRO___NR __NR_vserver;
MACRO___NR __NR_wait4;
MACRO___NR __NR_waitid;
MACRO___NR __NR_waitpid;
MACRO___NR __NR_write;
MACRO___NR __NR_writev;
int sys32_quotactl(unsigned int cmd, const char *special, qid_t id, void *addr);
int sys_accept(int, struct sockaddr *, int *);
int sys_accept4(int, struct sockaddr *, int *, int);
int sys_access(const char *filename, int mode);
int sys_acct(const char *name);
int sys_add_key(const char *type, const char *description, const void *payload, size_t plen, key_serial_t destringid);
int sys_adjtimex(struct timex *txc_p);
int sys_alarm(unsigned int seconds);
int sys_bdflush(int func, int data);
int sys_bind(int, struct sockaddr *, int);
int sys_bpf(int cmd, union bpf_attr *attr, unsigned int size);
int sys_brk(unsigned int brk);
int sys_capget(cap_user_header_t header, cap_user_data_t dataptr);
int sys_capset(cap_user_header_t header, const cap_user_data_t data);
int sys_chdir(const char *filename);
int sys_chmod(const char *filename, umode_t mode);
int sys_chown(const char *filename, uid_t user, gid_t group);
int sys_chroot(const char *filename);
int sys_clock_adjtime(clockid_t which_clock, struct timex *tx);
int sys_clock_getres(clockid_t which_clock, struct timespec *tp);
int sys_clock_gettime(clockid_t which_clock, struct timespec *tp);
int sys_clock_nanosleep(clockid_t which_clock, int flags, const struct timespec *rqtp, struct timespec *rmtp);
int sys_clock_settime(clockid_t which_clock, const struct timespec *tp);
int sys_clone(unsigned int, unsigned int, int *, int *, unsigned int);
int sys_close(unsigned int fd);
int sys_connect(int, struct sockaddr *, int);
int sys_copy_file_range(int fd_in, loff_t *off_in, int fd_out, loff_t *off_out, size_t len, unsigned int flags);
int sys_creat(const char *pathname, umode_t mode);
int sys_delete_module(const char *name_user, unsigned int flags);
int sys_dup(unsigned int fildes);
int sys_dup2(unsigned int oldfd, unsigned int newfd);
int sys_dup3(unsigned int oldfd, unsigned int newfd, int flags);
int sys_epoll_create(int size);
int sys_epoll_create1(int flags);
int sys_epoll_ctl(int epfd, int op, int fd, struct epoll_event *event);
int sys_epoll_pwait(int epfd, struct epoll_event *events, int maxevents, int timeout, const sigset_t *sigmask, size_t sigsetsize);
int sys_epoll_wait(int epfd, struct epoll_event *events, int maxevents, int timeout);
int sys_eventfd(unsigned int count);
int sys_eventfd2(unsigned int count, int flags);
int sys_execve(const char *filename, const char *const *argv, const char *const *envp);
int sys_execveat(int dfd, const char *filename, const char *const *argv, const char *const *envp, int flags);
int sys_exit(int error_code);
int sys_exit_group(int error_code);
int sys_faccessat(int dfd, const char *filename, int mode);
int sys_fadvise64(int fd, loff_t offset, size_t len, int advice);
int sys_fadvise64_64(int fd, loff_t offset, loff_t len, int advice);
int sys_fallocate(int fd, int mode, loff_t offset, loff_t len);
int sys_fanotify_init(unsigned int flags, unsigned int event_f_flags);
int sys_fanotify_mark(int fanotify_fd, unsigned int flags, u64 mask, int fd, const char *pathname);
int sys_fchdir(unsigned int fd);
int sys_fchmod(unsigned int fd, umode_t mode);
int sys_fchmodat(int dfd, const char *filename, umode_t mode);
int sys_fchown(unsigned int fd, uid_t user, gid_t group);
int sys_fchownat(int dfd, const char *filename, uid_t user, gid_t group, int flag);
int sys_fcntl(unsigned int fd, unsigned int cmd, unsigned int arg);
int sys_fdatasync(unsigned int fd);
int sys_fgetxattr(int fd, const char *name, void *value, size_t size);
int sys_finit_module(int fd, const char *uargs, int flags);
int sys_flistxattr(int fd, char *list, size_t size);
int sys_flock(unsigned int fd, unsigned int cmd);
int sys_fork(void);
int sys_fremovexattr(int fd, const char *name);
int sys_fsetxattr(int fd, const char *name, const void *value, size_t size, int flags);
int sys_fstat(unsigned int fd, struct __old_kernel_stat *statbuf);
int sys_fstatfs(unsigned int fd, struct statfs *buf);
int sys_fstatfs64(unsigned int fd, size_t sz, struct statfs64 *buf);
int sys_fsync(unsigned int fd);
int sys_ftruncate(unsigned int fd, unsigned int length);
int sys_futex(u32 *uaddr, int op, u32 val, struct timespec *utime, u32 *uaddr2, u32 val3);
int sys_futimesat(int dfd, const char *filename, struct timeval *utimes);
int sys_get_mempolicy(int *policy, unsigned int *nmask, unsigned int maxnode, unsigned int addr, unsigned int flags);
int sys_get_robust_list(int pid, struct robust_list_head **head_ptr, size_t *len_ptr);
int sys_getcpu(unsigned int *cpu, unsigned int *node, struct getcpu_cache *cache);
int sys_getcwd(char *buf, unsigned int size);
int sys_getdents(unsigned int fd, struct linux_dirent *dirent, unsigned int count);
int sys_getdents64(unsigned int fd, struct linux_dirent64 *dirent, unsigned int count);
int sys_getegid(void);
int sys_geteuid(void);
int sys_getgid(void);
int sys_getgroups(int gidsetsize, gid_t *grouplist);
int sys_gethostname(char *name, int len);
int sys_getitimer(int which, struct itimerval *value);
int sys_getpeername(int, struct sockaddr *, int *);
int sys_getpgid(pid_t pid);
int sys_getpgrp(void);
int sys_getpid(void);
int sys_getppid(void);
int sys_getpriority(int which, int who);
int sys_getrandom(char *buf, size_t count, unsigned int flags);
int sys_getresgid(gid_t *rgid, gid_t *egid, gid_t *sgid);
int sys_getresuid(uid_t *ruid, uid_t *euid, uid_t *suid);
int sys_getrlimit(unsigned int resource, struct rlimit *rlim);
int sys_getrusage(int who, struct rusage *ru);
int sys_getsid(pid_t pid);
int sys_getsockname(int, struct sockaddr *, int *);
int sys_getsockopt(int fd, int level, int optname, char *optval, int *optlen);
int sys_gettid(void);
int sys_gettimeofday(struct timeval *tv, struct timezone *tz);
int sys_getuid(void);
int sys_getxattr(const char *path, const char *name, void *value, size_t size);
int sys_init_module(void *umod, unsigned int len, const char *uargs);
int sys_inotify_add_watch(int fd, const char *path, u32 mask);
int sys_inotify_init(void);
int sys_inotify_init1(int flags);
int sys_inotify_rm_watch(int fd, __s32 wd);
int sys_io_cancel(aio_context_t ctx_id, struct iocb *iocb, struct io_event *result);
int sys_io_destroy(aio_context_t ctx);
int sys_io_getevents(aio_context_t ctx_id, int min_nr, int nr, struct io_event *events, struct timespec *timeout);
int sys_io_setup(unsigned int nr_reqs, aio_context_t *ctx);
int sys_io_submit(aio_context_t, int, struct iocb **);
int sys_ioctl(unsigned int fd, unsigned int cmd, unsigned int arg);
int sys_ioperm(unsigned int from, unsigned int num, int on);
int sys_ioprio_get(int which, int who);
int sys_ioprio_set(int which, int who, int ioprio);
int sys_ipc(unsigned int call, int first, unsigned int second, unsigned int third, void *ptr, int fifth);
int sys_kcmp(pid_t pid1, pid_t pid2, int type, unsigned int idx1, unsigned int idx2);
int sys_kexec_file_load(int kernel_fd, int initrd_fd, unsigned int cmdline_len, const char *cmdline_ptr, unsigned int flags);
int sys_kexec_load(unsigned int entry, unsigned int nr_segments, struct kexec_segment *segments, unsigned int flags);
int sys_keyctl(int cmd, unsigned int arg2, unsigned int arg3, unsigned int arg4, unsigned int arg5);
int sys_kill(pid_t pid, int sig);
int sys_lchown(const char *filename, uid_t user, gid_t group);
int sys_lgetxattr(const char *path, const char *name, void *value, size_t size);
int sys_link(const char *oldname, const char *newname);
int sys_linkat(int olddfd, const char *oldname, int newdfd, const char *newname, int flags);
int sys_listen(int, int);
int sys_listxattr(const char *path, char *list, size_t size);
int sys_llistxattr(const char *path, char *list, size_t size);
int sys_llseek(unsigned int fd, unsigned int offset_high, unsigned int offset_low, loff_t *result, unsigned int whence);
int sys_lookup_dcookie(u64 cookie64, char *buf, size_t len);
int sys_lremovexattr(const char *path, const char *name);
int sys_lseek(unsigned int fd, off_t offset, unsigned int whence);
int sys_lsetxattr(const char *path, const char *name, const void *value, size_t size, int flags);
int sys_lstat(const char *filename, struct __old_kernel_stat *statbuf);
int sys_madvise(unsigned int start, size_t len, int behavior);
int sys_mbind(unsigned int start, unsigned int len, unsigned int mode, const unsigned int *nmask, unsigned int maxnode, unsigned int flags);
int sys_membarrier(int cmd, int flags);
int sys_memfd_create(const char *uname_ptr, unsigned int flags);
int sys_migrate_pages(pid_t pid, unsigned int maxnode, const unsigned int *from, const unsigned int *to);
int sys_mincore(unsigned int start, size_t len, unsigned __int8 *vec);
int sys_mkdir(const char *pathname, umode_t mode);
int sys_mkdirat(int dfd, const char *pathname, umode_t mode);
int sys_mknod(const char *filename, umode_t mode, unsigned int dev);
int sys_mknodat(int dfd, const char *filename, umode_t mode, unsigned int dev);
int sys_mlock(unsigned int start, size_t len);
int sys_mlock2(unsigned int start, size_t len, int flags);
int sys_mlockall(int flags);
int sys_mmap_pgoff(unsigned int addr, unsigned int len, unsigned int prot, unsigned int flags, unsigned int fd, unsigned int pgoff);
int sys_mount(char *dev_name, char *dir_name, char *type, unsigned int flags, void *data);
int sys_move_pages(pid_t pid, unsigned int nr_pages, const void **pages, const int *nodes, int *status, int flags);
int sys_mprotect(unsigned int start, size_t len, unsigned int prot);
int sys_mq_getsetattr(mqd_t mqdes, const struct mq_attr *mqstat, struct mq_attr *omqstat);
int sys_mq_notify(mqd_t mqdes, const struct sigevent *notification);
int sys_mq_open(const char *name, int oflag, umode_t mode, struct mq_attr *attr);
int sys_mq_timedreceive(mqd_t mqdes, char *msg_ptr, size_t msg_len, unsigned int *msg_prio, const struct timespec *abs_timeout);
int sys_mq_timedsend(mqd_t mqdes, const char *msg_ptr, size_t msg_len, unsigned int msg_prio, const struct timespec *abs_timeout);
int sys_mq_unlink(const char *name);
int sys_mremap(unsigned int addr, unsigned int old_len, unsigned int new_len, unsigned int flags, unsigned int new_addr);
int sys_msgctl(int msqid, int cmd, struct msqid_ds *buf);
int sys_msgget(key_t key, int msgflg);
int sys_msgrcv(int msqid, struct msgbuf *msgp, size_t msgsz, int msgtyp, int msgflg);
int sys_msgsnd(int msqid, struct msgbuf *msgp, size_t msgsz, int msgflg);
int sys_msync(unsigned int start, size_t len, int flags);
int sys_munlock(unsigned int start, size_t len);
int sys_munlockall(void);
int sys_munmap(unsigned int addr, size_t len);
int sys_name_to_handle_at(int dfd, const char *name, struct file_handle *handle, int *mnt_id, int flag);
int sys_nanosleep(struct timespec *rqtp, struct timespec *rmtp);
int sys_newfstat(unsigned int fd, struct stat *statbuf);
int sys_newfstatat(int dfd, const char *filename, struct stat *statbuf, int flag);
int sys_newlstat(const char *filename, struct stat *statbuf);
int sys_newstat(const char *filename, struct stat *statbuf);
int sys_newuname(struct new_utsname *name);
int sys_ni_syscall(void);
int sys_nice(int increment);
int sys_old_getrlimit(unsigned int resource, struct rlimit *rlim);
int sys_old_mmap(struct mmap_arg_struct *arg);
int sys_old_readdir(unsigned int, struct old_linux_dirent *, unsigned int);
int sys_old_select(struct sel_arg_struct *arg);
int sys_oldumount(char *name);
int sys_olduname(struct oldold_utsname *);
int sys_open(const char *filename, int flags, umode_t mode);
int sys_open_by_handle_at(int mountdirfd, struct file_handle *handle, int flags);
int sys_openat(int dfd, const char *filename, int flags, umode_t mode);
int sys_pause(void);
int sys_pciconfig_iobase(int which, unsigned int bus, unsigned int devfn);
int sys_pciconfig_read(unsigned int bus, unsigned int dfn, unsigned int off, unsigned int len, void *buf);
int sys_pciconfig_write(unsigned int bus, unsigned int dfn, unsigned int off, unsigned int len, void *buf);
int sys_perf_event_open(struct perf_event_attr *attr_uptr, pid_t pid, int cpu, int group_fd, unsigned int flags);
int sys_personality(unsigned int personality);
int sys_pipe(int *fildes);
int sys_pipe2(int *fildes, int flags);
int sys_pivot_root(const char *new_root, const char *put_old);
int sys_poll(struct pollfd *ufds, unsigned int nfds, int timeout);
int sys_ppoll(struct pollfd *, unsigned int, struct timespec *, const sigset_t *, size_t);
int sys_prctl(int option, unsigned int arg2, unsigned int arg3, unsigned int arg4, unsigned int arg5);
int sys_pread64(unsigned int fd, char *buf, size_t count, loff_t pos);
int sys_preadv(unsigned int fd, const struct iovec *vec, unsigned int vlen, unsigned int pos_l, unsigned int pos_h);
int sys_preadv2(unsigned int fd, const struct iovec *vec, unsigned int vlen, unsigned int pos_l, unsigned int pos_h, int flags);
int sys_prlimit64(pid_t pid, unsigned int resource, const struct rlimit64 *new_rlim, struct rlimit64 *old_rlim);
int sys_process_vm_readv(pid_t pid, const struct iovec *lvec, unsigned int liovcnt, const struct iovec *rvec, unsigned int riovcnt, unsigned int flags);
int sys_process_vm_writev(pid_t pid, const struct iovec *lvec, unsigned int liovcnt, const struct iovec *rvec, unsigned int riovcnt, unsigned int flags);
int sys_pselect6(int, fd_set *, fd_set *, fd_set *, struct timespec *, void *);
int sys_ptrace(int request, int pid, unsigned int addr, unsigned int data);
int sys_pwrite64(unsigned int fd, const char *buf, size_t count, loff_t pos);
int sys_pwritev(unsigned int fd, const struct iovec *vec, unsigned int vlen, unsigned int pos_l, unsigned int pos_h);
int sys_pwritev2(unsigned int fd, const struct iovec *vec, unsigned int vlen, unsigned int pos_l, unsigned int pos_h, int flags);
int sys_quotactl(unsigned int cmd, const char *special, qid_t id, void *addr);
int sys_read(unsigned int fd, char *buf, size_t count);
int sys_readahead(int fd, loff_t offset, size_t count);
int sys_readlink(const char *path, char *buf, int bufsiz);
int sys_readlinkat(int dfd, const char *path, char *buf, int bufsiz);
int sys_readv(unsigned int fd, const struct iovec *vec, unsigned int vlen);
int sys_reboot(int magic1, int magic2, unsigned int cmd, void *arg);
int sys_recv(int, void *, size_t, unsigned int);
int sys_recvfrom(int, void *, size_t, unsigned int, struct sockaddr *, int *);
int sys_recvmmsg(int fd, struct mmsghdr *msg, unsigned int vlen, unsigned int flags, struct timespec *timeout);
int sys_recvmsg(int fd, struct user_msghdr *msg, unsigned int flags);
int sys_remap_file_pages(unsigned int start, unsigned int size, unsigned int prot, unsigned int pgoff, unsigned int flags);
int sys_removexattr(const char *path, const char *name);
int sys_rename(const char *oldname, const char *newname);
int sys_renameat(int olddfd, const char *oldname, int newdfd, const char *newname);
int sys_renameat2(int olddfd, const char *oldname, int newdfd, const char *newname, unsigned int flags);
int sys_request_key(const char *type, const char *description, const char *callout_info, key_serial_t destringid);
int sys_restart_syscall(void);
int sys_rmdir(const char *pathname);
int sys_rt_sigaction(int, const struct sigaction *, struct sigaction *, size_t);
int sys_rt_sigpending(sigset_t *set, size_t sigsetsize);
int sys_rt_sigprocmask(int how, sigset_t *set, sigset_t *oset, size_t sigsetsize);
int sys_rt_sigqueueinfo(pid_t pid, int sig, siginfo_t *uinfo);
int sys_rt_sigsuspend(sigset_t *unewset, size_t sigsetsize);
int sys_rt_sigtimedwait(const sigset_t *uthese, siginfo_t *uinfo, const struct timespec *uts, size_t sigsetsize);
int sys_rt_tgsigqueueinfo(pid_t tgid, pid_t pid, int sig, siginfo_t *uinfo);
int sys_sched_get_priority_max(int policy);
int sys_sched_get_priority_min(int policy);
int sys_sched_getaffinity(pid_t pid, unsigned int len, unsigned int *user_mask_ptr);
int sys_sched_getattr(pid_t pid, struct sched_attr *attr, unsigned int size, unsigned int flags);
int sys_sched_getparam(pid_t pid, struct sched_param *param);
int sys_sched_getscheduler(pid_t pid);
int sys_sched_rr_get_interval(pid_t pid, struct timespec *interval);
int sys_sched_setaffinity(pid_t pid, unsigned int len, unsigned int *user_mask_ptr);
int sys_sched_setattr(pid_t pid, struct sched_attr *attr, unsigned int flags);
int sys_sched_setparam(pid_t pid, struct sched_param *param);
int sys_sched_setscheduler(pid_t pid, int policy, struct sched_param *param);
int sys_sched_yield(void);
int sys_seccomp(unsigned int op, unsigned int flags, const char *uargs);
int sys_select(int n, fd_set *inp, fd_set *outp, fd_set *exp, struct timeval *tvp);
int sys_semctl(int semid, int semnum, int cmd, unsigned int arg);
int sys_semget(key_t key, int nsems, int semflg);
int sys_semop(int semid, struct sembuf *sops, unsigned int nsops);
int sys_semtimedop(int semid, struct sembuf *sops, unsigned int nsops, const struct timespec *timeout);
int sys_send(int, void *, size_t, unsigned int);
int sys_sendfile(int out_fd, int in_fd, off_t *offset, size_t count);
int sys_sendfile64(int out_fd, int in_fd, loff_t *offset, size_t count);
int sys_sendmmsg(int fd, struct mmsghdr *msg, unsigned int vlen, unsigned int flags);
int sys_sendmsg(int fd, struct user_msghdr *msg, unsigned int flags);
int sys_sendto(int, void *, size_t, unsigned int, struct sockaddr *, int);
int sys_set_mempolicy(int mode, const unsigned int *nmask, unsigned int maxnode);
int sys_set_robust_list(struct robust_list_head *head, size_t len);
int sys_set_tid_address(int *tidptr);
int sys_setdomainname(char *name, int len);
int sys_setfsgid(gid_t gid);
int sys_setfsuid(uid_t uid);
int sys_setgid(gid_t gid);
int sys_setgroups(int gidsetsize, gid_t *grouplist);
int sys_sethostname(char *name, int len);
int sys_setitimer(int which, struct itimerval *value, struct itimerval *ovalue);
int sys_setns(int fd, int nstype);
int sys_setpgid(pid_t pid, pid_t pgid);
int sys_setpriority(int which, int who, int niceval);
int sys_setregid(gid_t rgid, gid_t egid);
int sys_setresgid(gid_t rgid, gid_t egid, gid_t sgid);
int sys_setresuid(uid_t ruid, uid_t euid, uid_t suid);
int sys_setreuid(uid_t ruid, uid_t euid);
int sys_setrlimit(unsigned int resource, struct rlimit *rlim);
int sys_setsid(void);
int sys_setsockopt(int fd, int level, int optname, char *optval, int optlen);
int sys_settimeofday(struct timeval *tv, struct timezone *tz);
int sys_setuid(uid_t uid);
int sys_setxattr(const char *path, const char *name, const void *value, size_t size, int flags);
int sys_sgetmask(void);
int sys_shmat(int shmid, char *shmaddr, int shmflg);
int sys_shmctl(int shmid, int cmd, struct shmid_ds *buf);
int sys_shmdt(char *shmaddr);
int sys_shmget(key_t key, size_t size, int flag);
int sys_shutdown(int, int);
int sys_sigaltstack(const struct sigaltstack *uss, struct sigaltstack *uoss);
int sys_signal(int sig, __sighandler_t handler);
int sys_signalfd(int ufd, sigset_t *user_mask, size_t sizemask);
int sys_signalfd4(int ufd, sigset_t *user_mask, size_t sizemask, int flags);
int sys_sigpending(old_sigset_t *set);
int sys_sigprocmask(int how, old_sigset_t *set, old_sigset_t *oset);
int sys_socket(int, int, int);
int sys_socketcall(int call, unsigned int *args);
int sys_socketpair(int, int, int, int *);
int sys_splice(int fd_in, loff_t *off_in, int fd_out, loff_t *off_out, size_t len, unsigned int flags);
int sys_spu_create(const char *name, unsigned int flags, umode_t mode, int fd);
int sys_spu_run(int fd, __u32 *unpc, __u32 *ustatus);
int sys_ssetmask(int newmask);
int sys_stat(const char *filename, struct __old_kernel_stat *statbuf);
int sys_statfs(const char *path, struct statfs *buf);
int sys_statfs64(const char *path, size_t sz, struct statfs64 *buf);
int sys_stime(time_t *tptr);
int sys_swapoff(const char *specialfile);
int sys_swapon(const char *specialfile, int swap_flags);
int sys_symlink(const char *old, const char *new);
int sys_symlinkat(const char *oldname, int newdfd, const char *newname);
int sys_sync(void);
int sys_sync_file_range(int fd, loff_t offset, loff_t nbytes, unsigned int flags);
int sys_sync_file_range2(int fd, unsigned int flags, loff_t offset, loff_t nbytes);
int sys_syncfs(int fd);
int sys_sysctl(struct __sysctl_args *args);
int sys_sysfs(int option, unsigned int arg1, unsigned int arg2);
int sys_sysinfo(struct sysinfo *info);
int sys_syslog(int type, char *buf, int len);
int sys_tee(int fdin, int fdout, size_t len, unsigned int flags);
int sys_tgkill(pid_t tgid, pid_t pid, int sig);
int sys_time(time_t *tloc);
int sys_timer_create(clockid_t which_clock, struct sigevent *timer_event_spec, timer_t *created_timer_id);
int sys_timer_delete(timer_t timer_id);
int sys_timer_getoverrun(timer_t timer_id);
int sys_timer_gettime(timer_t timer_id, struct itimerspec *setting);
int sys_timer_settime(timer_t timer_id, int flags, const struct itimerspec *new_setting, struct itimerspec *old_setting);
int sys_timerfd_create(int clockid, int flags);
int sys_timerfd_gettime(int ufd, struct itimerspec *otmr);
int sys_timerfd_settime(int ufd, int flags, const struct itimerspec *utmr, struct itimerspec *otmr);
int sys_times(struct tms *tbuf);
int sys_tkill(pid_t pid, int sig);
int sys_truncate(const char *path, int length);
int sys_umask(int mask);
int sys_umount(char *name, int flags);
int sys_uname(struct old_utsname *);
int sys_unlink(const char *pathname);
int sys_unlinkat(int dfd, const char *pathname, int flag);
int sys_unshare(unsigned int unshare_flags);
int sys_uselib(const char *library);
int sys_userfaultfd(int flags);
int sys_ustat(unsigned int dev, struct ustat *ubuf);
int sys_utime(char *filename, struct utimbuf *times);
int sys_utimensat(int dfd, const char *filename, struct timespec *utimes, int flags);
int sys_utimes(char *filename, struct timeval *utimes);
int sys_vfork(void);
int sys_vhangup(void);
int sys_vmsplice(int fd, const struct iovec *iov, unsigned int nr_segs, unsigned int flags);
int sys_wait4(pid_t pid, int *stat_addr, int options, struct rusage *ru);
int sys_waitid(int which, pid_t pid, struct siginfo *infop, int options, struct rusage *ru);
int sys_waitpid(pid_t pid, int *stat_addr, int options);
int sys_write(unsigned int fd, const char *buf, size_t count);
int sys_writev(unsigned int fd, const struct iovec *vec, unsigned int vlen);
