enum MACRO_SYS {SYS_read = 0,SYS_write = 1,SYS_open = 2,SYS_close = 3,SYS_stat = 4,SYS_fstat = 5,SYS_lstat = 6,SYS_poll = 7,SYS_lseek = 8,SYS_mmap = 9,SYS_mprotect = 10,SYS_munmap = 11,SYS_brk = 12,SYS_rt_sigaction = 13,SYS_rt_sigprocmask = 14,SYS_rt_sigreturn = 15,SYS_ioctl = 16,SYS_pread64 = 17,SYS_pwrite64 = 18,SYS_readv = 19,SYS_writev = 20,SYS_access = 21,SYS_pipe = 22,SYS_select = 23,SYS_sched_yield = 24,SYS_mremap = 25,SYS_msync = 26,SYS_mincore = 27,SYS_madvise = 28,SYS_shmget = 29,SYS_shmat = 30,SYS_shmctl = 31,SYS_dup = 32,SYS_dup2 = 33,SYS_pause = 34,SYS_nanosleep = 35,SYS_getitimer = 36,SYS_alarm = 37,SYS_setitimer = 38,SYS_getpid = 39,SYS_sendfile = 40,SYS_socket = 41,SYS_connect = 42,SYS_accept = 43,SYS_sendto = 44,SYS_recvfrom = 45,SYS_sendmsg = 46,SYS_recvmsg = 47,SYS_shutdown = 48,SYS_bind = 49,SYS_listen = 50,SYS_getsockname = 51,SYS_getpeername = 52,SYS_socketpair = 53,SYS_setsockopt = 54,SYS_getsockopt = 55,SYS_clone = 56,SYS_fork = 57,SYS_vfork = 58,SYS_execve = 59,SYS_exit = 60,SYS_wait4 = 61,SYS_kill = 62,SYS_uname = 63,SYS_semget = 64,SYS_semop = 65,SYS_semctl = 66,SYS_shmdt = 67,SYS_msgget = 68,SYS_msgsnd = 69,SYS_msgrcv = 70,SYS_msgctl = 71,SYS_fcntl = 72,SYS_flock = 73,SYS_fsync = 74,SYS_fdatasync = 75,SYS_truncate = 76,SYS_ftruncate = 77,SYS_getdents = 78,SYS_getcwd = 79,SYS_chdir = 80,SYS_fchdir = 81,SYS_rename = 82,SYS_mkdir = 83,SYS_rmdir = 84,SYS_creat = 85,SYS_link = 86,SYS_unlink = 87,SYS_symlink = 88,SYS_readlink = 89,SYS_chmod = 90,SYS_fchmod = 91,SYS_chown = 92,SYS_fchown = 93,SYS_lchown = 94,SYS_umask = 95,SYS_gettimeofday = 96,SYS_getrlimit = 97,SYS_getrusage = 98,SYS_sysinfo = 99,SYS_times = 100,SYS_ptrace = 101,SYS_getuid = 102,SYS_syslog = 103,SYS_getgid = 104,SYS_setuid = 105,SYS_setgid = 106,SYS_geteuid = 107,SYS_getegid = 108,SYS_setpgid = 109,SYS_getppid = 110,SYS_getpgrp = 111,SYS_setsid = 112,SYS_setreuid = 113,SYS_setregid = 114,SYS_getgroups = 115,SYS_setgroups = 116,SYS_setresuid = 117,SYS_getresuid = 118,SYS_setresgid = 119,SYS_getresgid = 120,SYS_getpgid = 121,SYS_setfsuid = 122,SYS_setfsgid = 123,SYS_getsid = 124,SYS_capget = 125,SYS_capset = 126,SYS_rt_sigpending = 127,SYS_rt_sigtimedwait = 128,SYS_rt_sigqueueinfo = 129,SYS_rt_sigsuspend = 130,SYS_sigaltstack = 131,SYS_utime = 132,SYS_mknod = 133,SYS_uselib = 134,SYS_personality = 135,SYS_ustat = 136,SYS_statfs = 137,SYS_fstatfs = 138,SYS_sysfs = 139,SYS_getpriority = 140,SYS_setpriority = 141,SYS_sched_setparam = 142,SYS_sched_getparam = 143,SYS_sched_setscheduler = 144,SYS_sched_getscheduler = 145,SYS_sched_get_priority_max = 146,SYS_sched_get_priority_min = 147,SYS_sched_rr_get_interval = 148,SYS_mlock = 149,SYS_munlock = 150,SYS_mlockall = 151,SYS_munlockall = 152,SYS_vhangup = 153,SYS_modify_ldt = 154,SYS_pivot_root = 155,SYS__sysctl = 156,SYS_prctl = 157,SYS_arch_prctl = 158,SYS_adjtimex = 159,SYS_setrlimit = 160,SYS_chroot = 161,SYS_sync = 162,SYS_acct = 163,SYS_settimeofday = 164,SYS_mount = 165,SYS_umount2 = 166,SYS_swapon = 167,SYS_swapoff = 168,SYS_reboot = 169,SYS_sethostname = 170,SYS_setdomainname = 171,SYS_iopl = 172,SYS_ioperm = 173,SYS_create_module = 174,SYS_init_module = 175,SYS_delete_module = 176,SYS_get_kernel_syms = 177,SYS_query_module = 178,SYS_quotactl = 179,SYS_nfsservctl = 180,SYS_getpmsg = 181,SYS_putpmsg = 182,SYS_afs_syscall = 183,SYS_tuxcall = 184,SYS_security = 185,SYS_gettid = 186,SYS_readahead = 187,SYS_setxattr = 188,SYS_lsetxattr = 189,SYS_fsetxattr = 190,SYS_getxattr = 191,SYS_lgetxattr = 192,SYS_fgetxattr = 193,SYS_listxattr = 194,SYS_llistxattr = 195,SYS_flistxattr = 196,SYS_removexattr = 197,SYS_lremovexattr = 198,SYS_fremovexattr = 199,SYS_tkill = 200,SYS_time = 201,SYS_futex = 202,SYS_sched_setaffinity = 203,SYS_sched_getaffinity = 204,SYS_set_thread_area = 205,SYS_io_setup = 206,SYS_io_destroy = 207,SYS_io_getevents = 208,SYS_io_submit = 209,SYS_io_cancel = 210,SYS_get_thread_area = 211,SYS_lookup_dcookie = 212,SYS_epoll_create = 213,SYS_epoll_ctl_old = 214,SYS_epoll_wait_old = 215,SYS_remap_file_pages = 216,SYS_getdents64 = 217,SYS_set_tid_address = 218,SYS_restart_syscall = 219,SYS_semtimedop = 220,SYS_fadvise64 = 221,SYS_timer_create = 222,SYS_timer_settime = 223,SYS_timer_gettime = 224,SYS_timer_getoverrun = 225,SYS_timer_delete = 226,SYS_clock_settime = 227,SYS_clock_gettime = 228,SYS_clock_getres = 229,SYS_clock_nanosleep = 230,SYS_exit_group = 231,SYS_epoll_wait = 232,SYS_epoll_ctl = 233,SYS_tgkill = 234,SYS_utimes = 235,SYS_vserver = 236,SYS_mbind = 237,SYS_set_mempolicy = 238,SYS_get_mempolicy = 239,SYS_mq_open = 240,SYS_mq_unlink = 241,SYS_mq_timedsend = 242,SYS_mq_timedreceive = 243,SYS_mq_notify = 244,SYS_mq_getsetattr = 245,SYS_kexec_load = 246,SYS_waitid = 247,SYS_add_key = 248,SYS_request_key = 249,SYS_keyctl = 250,SYS_ioprio_set = 251,SYS_ioprio_get = 252,SYS_inotify_init = 253,SYS_inotify_add_watch = 254,SYS_inotify_rm_watch = 255,SYS_migrate_pages = 256,SYS_openat = 257,SYS_mkdirat = 258,SYS_mknodat = 259,SYS_fchownat = 260,SYS_futimesat = 261,SYS_newfstatat = 262,SYS_unlinkat = 263,SYS_renameat = 264,SYS_linkat = 265,SYS_symlinkat = 266,SYS_readlinkat = 267,SYS_fchmodat = 268,SYS_faccessat = 269,SYS_pselect6 = 270,SYS_ppoll = 271,SYS_unshare = 272,SYS_set_robust_list = 273,SYS_get_robust_list = 274,SYS_splice = 275,SYS_tee = 276,SYS_sync_file_range = 277,SYS_vmsplice = 278,SYS_move_pages = 279,SYS_utimensat = 280,SYS_epoll_pwait = 281,SYS_signalfd = 282,SYS_timerfd_create = 283,SYS_eventfd = 284,SYS_fallocate = 285,SYS_timerfd_settime = 286,SYS_timerfd_gettime = 287,SYS_accept4 = 288,SYS_signalfd4 = 289,SYS_eventfd2 = 290,SYS_epoll_create1 = 291,SYS_dup3 = 292,SYS_pipe2 = 293,SYS_inotify_init1 = 294,SYS_preadv = 295,SYS_pwritev = 296,SYS_rt_tgsigqueueinfo = 297,SYS_perf_event_open = 298,SYS_recvmmsg = 299,SYS_fanotify_init = 300,SYS_fanotify_mark = 301,SYS_prlimit64 = 302,SYS_name_to_handle_at = 303,SYS_open_by_handle_at = 304,SYS_clock_adjtime = 305,SYS_syncfs = 306,SYS_sendmmsg = 307,SYS_setns = 308,SYS_getcpu = 309,SYS_process_vm_readv = 310,SYS_process_vm_writev = 311,SYS_kcmp = 312,SYS_finit_module = 313,SYS_sched_setattr = 314,SYS_sched_getattr = 315,SYS_renameat2 = 316,SYS_seccomp = 317,SYS_getrandom = 318,SYS_memfd_create = 319,SYS_kexec_file_load = 320,SYS_bpf = 321,SYS_execveat = 322,SYS_userfaultfd = 323,SYS_membarrier = 324,SYS_mlock2 = 325,SYS_copy_file_range = 326,SYS_preadv2 = 327,SYS_pwritev2 = 328,};
enum MACRO___NR {__NR_read = 0,__NR_write = 1,__NR_open = 2,__NR_close = 3,__NR_stat = 4,__NR_fstat = 5,__NR_lstat = 6,__NR_poll = 7,__NR_lseek = 8,__NR_mmap = 9,__NR_mprotect = 10,__NR_munmap = 11,__NR_brk = 12,__NR_rt_sigaction = 13,__NR_rt_sigprocmask = 14,__NR_rt_sigreturn = 15,__NR_ioctl = 16,__NR_pread64 = 17,__NR_pwrite64 = 18,__NR_readv = 19,__NR_writev = 20,__NR_access = 21,__NR_pipe = 22,__NR_select = 23,__NR_sched_yield = 24,__NR_mremap = 25,__NR_msync = 26,__NR_mincore = 27,__NR_madvise = 28,__NR_shmget = 29,__NR_shmat = 30,__NR_shmctl = 31,__NR_dup = 32,__NR_dup2 = 33,__NR_pause = 34,__NR_nanosleep = 35,__NR_getitimer = 36,__NR_alarm = 37,__NR_setitimer = 38,__NR_getpid = 39,__NR_sendfile = 40,__NR_socket = 41,__NR_connect = 42,__NR_accept = 43,__NR_sendto = 44,__NR_recvfrom = 45,__NR_sendmsg = 46,__NR_recvmsg = 47,__NR_shutdown = 48,__NR_bind = 49,__NR_listen = 50,__NR_getsockname = 51,__NR_getpeername = 52,__NR_socketpair = 53,__NR_setsockopt = 54,__NR_getsockopt = 55,__NR_clone = 56,__NR_fork = 57,__NR_vfork = 58,__NR_execve = 59,__NR_exit = 60,__NR_wait4 = 61,__NR_kill = 62,__NR_uname = 63,__NR_semget = 64,__NR_semop = 65,__NR_semctl = 66,__NR_shmdt = 67,__NR_msgget = 68,__NR_msgsnd = 69,__NR_msgrcv = 70,__NR_msgctl = 71,__NR_fcntl = 72,__NR_flock = 73,__NR_fsync = 74,__NR_fdatasync = 75,__NR_truncate = 76,__NR_ftruncate = 77,__NR_getdents = 78,__NR_getcwd = 79,__NR_chdir = 80,__NR_fchdir = 81,__NR_rename = 82,__NR_mkdir = 83,__NR_rmdir = 84,__NR_creat = 85,__NR_link = 86,__NR_unlink = 87,__NR_symlink = 88,__NR_readlink = 89,__NR_chmod = 90,__NR_fchmod = 91,__NR_chown = 92,__NR_fchown = 93,__NR_lchown = 94,__NR_umask = 95,__NR_gettimeofday = 96,__NR_getrlimit = 97,__NR_getrusage = 98,__NR_sysinfo = 99,__NR_times = 100,__NR_ptrace = 101,__NR_getuid = 102,__NR_syslog = 103,__NR_getgid = 104,__NR_setuid = 105,__NR_setgid = 106,__NR_geteuid = 107,__NR_getegid = 108,__NR_setpgid = 109,__NR_getppid = 110,__NR_getpgrp = 111,__NR_setsid = 112,__NR_setreuid = 113,__NR_setregid = 114,__NR_getgroups = 115,__NR_setgroups = 116,__NR_setresuid = 117,__NR_getresuid = 118,__NR_setresgid = 119,__NR_getresgid = 120,__NR_getpgid = 121,__NR_setfsuid = 122,__NR_setfsgid = 123,__NR_getsid = 124,__NR_capget = 125,__NR_capset = 126,__NR_rt_sigpending = 127,__NR_rt_sigtimedwait = 128,__NR_rt_sigqueueinfo = 129,__NR_rt_sigsuspend = 130,__NR_sigaltstack = 131,__NR_utime = 132,__NR_mknod = 133,__NR_uselib = 134,__NR_personality = 135,__NR_ustat = 136,__NR_statfs = 137,__NR_fstatfs = 138,__NR_sysfs = 139,__NR_getpriority = 140,__NR_setpriority = 141,__NR_sched_setparam = 142,__NR_sched_getparam = 143,__NR_sched_setscheduler = 144,__NR_sched_getscheduler = 145,__NR_sched_get_priority_max = 146,__NR_sched_get_priority_min = 147,__NR_sched_rr_get_interval = 148,__NR_mlock = 149,__NR_munlock = 150,__NR_mlockall = 151,__NR_munlockall = 152,__NR_vhangup = 153,__NR_modify_ldt = 154,__NR_pivot_root = 155,__NR__sysctl = 156,__NR_prctl = 157,__NR_arch_prctl = 158,__NR_adjtimex = 159,__NR_setrlimit = 160,__NR_chroot = 161,__NR_sync = 162,__NR_acct = 163,__NR_settimeofday = 164,__NR_mount = 165,__NR_umount2 = 166,__NR_swapon = 167,__NR_swapoff = 168,__NR_reboot = 169,__NR_sethostname = 170,__NR_setdomainname = 171,__NR_iopl = 172,__NR_ioperm = 173,__NR_create_module = 174,__NR_init_module = 175,__NR_delete_module = 176,__NR_get_kernel_syms = 177,__NR_query_module = 178,__NR_quotactl = 179,__NR_nfsservctl = 180,__NR_getpmsg = 181,__NR_putpmsg = 182,__NR_afs_syscall = 183,__NR_tuxcall = 184,__NR_security = 185,__NR_gettid = 186,__NR_readahead = 187,__NR_setxattr = 188,__NR_lsetxattr = 189,__NR_fsetxattr = 190,__NR_getxattr = 191,__NR_lgetxattr = 192,__NR_fgetxattr = 193,__NR_listxattr = 194,__NR_llistxattr = 195,__NR_flistxattr = 196,__NR_removexattr = 197,__NR_lremovexattr = 198,__NR_fremovexattr = 199,__NR_tkill = 200,__NR_time = 201,__NR_futex = 202,__NR_sched_setaffinity = 203,__NR_sched_getaffinity = 204,__NR_set_thread_area = 205,__NR_io_setup = 206,__NR_io_destroy = 207,__NR_io_getevents = 208,__NR_io_submit = 209,__NR_io_cancel = 210,__NR_get_thread_area = 211,__NR_lookup_dcookie = 212,__NR_epoll_create = 213,__NR_epoll_ctl_old = 214,__NR_epoll_wait_old = 215,__NR_remap_file_pages = 216,__NR_getdents64 = 217,__NR_set_tid_address = 218,__NR_restart_syscall = 219,__NR_semtimedop = 220,__NR_fadvise64 = 221,__NR_timer_create = 222,__NR_timer_settime = 223,__NR_timer_gettime = 224,__NR_timer_getoverrun = 225,__NR_timer_delete = 226,__NR_clock_settime = 227,__NR_clock_gettime = 228,__NR_clock_getres = 229,__NR_clock_nanosleep = 230,__NR_exit_group = 231,__NR_epoll_wait = 232,__NR_epoll_ctl = 233,__NR_tgkill = 234,__NR_utimes = 235,__NR_vserver = 236,__NR_mbind = 237,__NR_set_mempolicy = 238,__NR_get_mempolicy = 239,__NR_mq_open = 240,__NR_mq_unlink = 241,__NR_mq_timedsend = 242,__NR_mq_timedreceive = 243,__NR_mq_notify = 244,__NR_mq_getsetattr = 245,__NR_kexec_load = 246,__NR_waitid = 247,__NR_add_key = 248,__NR_request_key = 249,__NR_keyctl = 250,__NR_ioprio_set = 251,__NR_ioprio_get = 252,__NR_inotify_init = 253,__NR_inotify_add_watch = 254,__NR_inotify_rm_watch = 255,__NR_migrate_pages = 256,__NR_openat = 257,__NR_mkdirat = 258,__NR_mknodat = 259,__NR_fchownat = 260,__NR_futimesat = 261,__NR_newfstatat = 262,__NR_unlinkat = 263,__NR_renameat = 264,__NR_linkat = 265,__NR_symlinkat = 266,__NR_readlinkat = 267,__NR_fchmodat = 268,__NR_faccessat = 269,__NR_pselect6 = 270,__NR_ppoll = 271,__NR_unshare = 272,__NR_set_robust_list = 273,__NR_get_robust_list = 274,__NR_splice = 275,__NR_tee = 276,__NR_sync_file_range = 277,__NR_vmsplice = 278,__NR_move_pages = 279,__NR_utimensat = 280,__NR_epoll_pwait = 281,__NR_signalfd = 282,__NR_timerfd_create = 283,__NR_eventfd = 284,__NR_fallocate = 285,__NR_timerfd_settime = 286,__NR_timerfd_gettime = 287,__NR_accept4 = 288,__NR_signalfd4 = 289,__NR_eventfd2 = 290,__NR_epoll_create1 = 291,__NR_dup3 = 292,__NR_pipe2 = 293,__NR_inotify_init1 = 294,__NR_preadv = 295,__NR_pwritev = 296,__NR_rt_tgsigqueueinfo = 297,__NR_perf_event_open = 298,__NR_recvmmsg = 299,__NR_fanotify_init = 300,__NR_fanotify_mark = 301,__NR_prlimit64 = 302,__NR_name_to_handle_at = 303,__NR_open_by_handle_at = 304,__NR_clock_adjtime = 305,__NR_syncfs = 306,__NR_sendmmsg = 307,__NR_setns = 308,__NR_getcpu = 309,__NR_process_vm_readv = 310,__NR_process_vm_writev = 311,__NR_kcmp = 312,__NR_finit_module = 313,__NR_sched_setattr = 314,__NR_sched_getattr = 315,__NR_renameat2 = 316,__NR_seccomp = 317,__NR_getrandom = 318,__NR_memfd_create = 319,__NR_kexec_file_load = 320,__NR_bpf = 321,__NR_execveat = 322,__NR_userfaultfd = 323,__NR_membarrier = 324,__NR_mlock2 = 325,__NR_copy_file_range = 326,__NR_preadv2 = 327,__NR_pwritev2 = 328,};
struct __old_kernel_stat;
union bpf_attr;
struct compat_stat;
struct compat_timeval;
struct getcpu_cache;
struct iattr;
struct inode;
typedef int32_t key_serial_t;
struct linux_dirent;
struct linux_dirent64;
struct list_head;
struct mmap_arg_struct;
typedef __kernel_mqd_t mqd_t;
struct nfsctl_arg;
struct old_linux_dirent;
typedef unsigned __int64 old_sigset_t;
struct perf_event_attr;
typedef __kernel_uid32_t qid_t;
struct sched_attr;
struct sel_arg_struct;
struct semaphore;
typedef unsigned int u32;
typedef unsigned __int64 u64;
typedef unsigned __int16 umode_t;
struct user_msghdr;

MACRO_SYS SYS__sysctl;
MACRO_SYS SYS_accept;
MACRO_SYS SYS_accept4;
MACRO_SYS SYS_access;
MACRO_SYS SYS_acct;
MACRO_SYS SYS_add_key;
MACRO_SYS SYS_adjtimex;
MACRO_SYS SYS_afs_syscall;
MACRO_SYS SYS_alarm;
MACRO_SYS SYS_arch_prctl;
MACRO_SYS SYS_bind;
MACRO_SYS SYS_bpf;
MACRO_SYS SYS_brk;
MACRO_SYS SYS_capget;
MACRO_SYS SYS_capset;
MACRO_SYS SYS_chdir;
MACRO_SYS SYS_chmod;
MACRO_SYS SYS_chown;
MACRO_SYS SYS_chroot;
MACRO_SYS SYS_clock_adjtime;
MACRO_SYS SYS_clock_getres;
MACRO_SYS SYS_clock_gettime;
MACRO_SYS SYS_clock_nanosleep;
MACRO_SYS SYS_clock_settime;
MACRO_SYS SYS_clone;
MACRO_SYS SYS_close;
MACRO_SYS SYS_connect;
MACRO_SYS SYS_copy_file_range;
MACRO_SYS SYS_creat;
MACRO_SYS SYS_create_module;
MACRO_SYS SYS_delete_module;
MACRO_SYS SYS_dup;
MACRO_SYS SYS_dup2;
MACRO_SYS SYS_dup3;
MACRO_SYS SYS_epoll_create;
MACRO_SYS SYS_epoll_create1;
MACRO_SYS SYS_epoll_ctl;
MACRO_SYS SYS_epoll_ctl_old;
MACRO_SYS SYS_epoll_pwait;
MACRO_SYS SYS_epoll_wait;
MACRO_SYS SYS_epoll_wait_old;
MACRO_SYS SYS_eventfd;
MACRO_SYS SYS_eventfd2;
MACRO_SYS SYS_execve;
MACRO_SYS SYS_execveat;
MACRO_SYS SYS_exit;
MACRO_SYS SYS_exit_group;
MACRO_SYS SYS_faccessat;
MACRO_SYS SYS_fadvise64;
MACRO_SYS SYS_fallocate;
MACRO_SYS SYS_fanotify_init;
MACRO_SYS SYS_fanotify_mark;
MACRO_SYS SYS_fchdir;
MACRO_SYS SYS_fchmod;
MACRO_SYS SYS_fchmodat;
MACRO_SYS SYS_fchown;
MACRO_SYS SYS_fchownat;
MACRO_SYS SYS_fcntl;
MACRO_SYS SYS_fdatasync;
MACRO_SYS SYS_fgetxattr;
MACRO_SYS SYS_finit_module;
MACRO_SYS SYS_flistxattr;
MACRO_SYS SYS_flock;
MACRO_SYS SYS_fork;
MACRO_SYS SYS_fremovexattr;
MACRO_SYS SYS_fsetxattr;
MACRO_SYS SYS_fstat;
MACRO_SYS SYS_fstatfs;
MACRO_SYS SYS_fsync;
MACRO_SYS SYS_ftruncate;
MACRO_SYS SYS_futex;
MACRO_SYS SYS_futimesat;
MACRO_SYS SYS_get_kernel_syms;
MACRO_SYS SYS_get_mempolicy;
MACRO_SYS SYS_get_robust_list;
MACRO_SYS SYS_get_thread_area;
MACRO_SYS SYS_getcpu;
MACRO_SYS SYS_getcwd;
MACRO_SYS SYS_getdents;
MACRO_SYS SYS_getdents64;
MACRO_SYS SYS_getegid;
MACRO_SYS SYS_geteuid;
MACRO_SYS SYS_getgid;
MACRO_SYS SYS_getgroups;
MACRO_SYS SYS_getitimer;
MACRO_SYS SYS_getpeername;
MACRO_SYS SYS_getpgid;
MACRO_SYS SYS_getpgrp;
MACRO_SYS SYS_getpid;
MACRO_SYS SYS_getpmsg;
MACRO_SYS SYS_getppid;
MACRO_SYS SYS_getpriority;
MACRO_SYS SYS_getrandom;
MACRO_SYS SYS_getresgid;
MACRO_SYS SYS_getresuid;
MACRO_SYS SYS_getrlimit;
MACRO_SYS SYS_getrusage;
MACRO_SYS SYS_getsid;
MACRO_SYS SYS_getsockname;
MACRO_SYS SYS_getsockopt;
MACRO_SYS SYS_gettid;
MACRO_SYS SYS_gettimeofday;
MACRO_SYS SYS_getuid;
MACRO_SYS SYS_getxattr;
MACRO_SYS SYS_init_module;
MACRO_SYS SYS_inotify_add_watch;
MACRO_SYS SYS_inotify_init;
MACRO_SYS SYS_inotify_init1;
MACRO_SYS SYS_inotify_rm_watch;
MACRO_SYS SYS_io_cancel;
MACRO_SYS SYS_io_destroy;
MACRO_SYS SYS_io_getevents;
MACRO_SYS SYS_io_setup;
MACRO_SYS SYS_io_submit;
MACRO_SYS SYS_ioctl;
MACRO_SYS SYS_ioperm;
MACRO_SYS SYS_iopl;
MACRO_SYS SYS_ioprio_get;
MACRO_SYS SYS_ioprio_set;
MACRO_SYS SYS_kcmp;
MACRO_SYS SYS_kexec_file_load;
MACRO_SYS SYS_kexec_load;
MACRO_SYS SYS_keyctl;
MACRO_SYS SYS_kill;
MACRO_SYS SYS_lchown;
MACRO_SYS SYS_lgetxattr;
MACRO_SYS SYS_link;
MACRO_SYS SYS_linkat;
MACRO_SYS SYS_listen;
MACRO_SYS SYS_listxattr;
MACRO_SYS SYS_llistxattr;
MACRO_SYS SYS_lookup_dcookie;
MACRO_SYS SYS_lremovexattr;
MACRO_SYS SYS_lseek;
MACRO_SYS SYS_lsetxattr;
MACRO_SYS SYS_lstat;
MACRO_SYS SYS_madvise;
MACRO_SYS SYS_mbind;
MACRO_SYS SYS_membarrier;
MACRO_SYS SYS_memfd_create;
MACRO_SYS SYS_migrate_pages;
MACRO_SYS SYS_mincore;
MACRO_SYS SYS_mkdir;
MACRO_SYS SYS_mkdirat;
MACRO_SYS SYS_mknod;
MACRO_SYS SYS_mknodat;
MACRO_SYS SYS_mlock;
MACRO_SYS SYS_mlock2;
MACRO_SYS SYS_mlockall;
MACRO_SYS SYS_mmap;
MACRO_SYS SYS_modify_ldt;
MACRO_SYS SYS_mount;
MACRO_SYS SYS_move_pages;
MACRO_SYS SYS_mprotect;
MACRO_SYS SYS_mq_getsetattr;
MACRO_SYS SYS_mq_notify;
MACRO_SYS SYS_mq_open;
MACRO_SYS SYS_mq_timedreceive;
MACRO_SYS SYS_mq_timedsend;
MACRO_SYS SYS_mq_unlink;
MACRO_SYS SYS_mremap;
MACRO_SYS SYS_msgctl;
MACRO_SYS SYS_msgget;
MACRO_SYS SYS_msgrcv;
MACRO_SYS SYS_msgsnd;
MACRO_SYS SYS_msync;
MACRO_SYS SYS_munlock;
MACRO_SYS SYS_munlockall;
MACRO_SYS SYS_munmap;
MACRO_SYS SYS_name_to_handle_at;
MACRO_SYS SYS_nanosleep;
MACRO_SYS SYS_newfstatat;
MACRO_SYS SYS_nfsservctl;
MACRO_SYS SYS_open;
MACRO_SYS SYS_open_by_handle_at;
MACRO_SYS SYS_openat;
MACRO_SYS SYS_pause;
MACRO_SYS SYS_perf_event_open;
MACRO_SYS SYS_personality;
MACRO_SYS SYS_pipe;
MACRO_SYS SYS_pipe2;
MACRO_SYS SYS_pivot_root;
MACRO_SYS SYS_poll;
MACRO_SYS SYS_ppoll;
MACRO_SYS SYS_prctl;
MACRO_SYS SYS_pread64;
MACRO_SYS SYS_preadv;
MACRO_SYS SYS_preadv2;
MACRO_SYS SYS_prlimit64;
MACRO_SYS SYS_process_vm_readv;
MACRO_SYS SYS_process_vm_writev;
MACRO_SYS SYS_pselect6;
MACRO_SYS SYS_ptrace;
MACRO_SYS SYS_putpmsg;
MACRO_SYS SYS_pwrite64;
MACRO_SYS SYS_pwritev;
MACRO_SYS SYS_pwritev2;
MACRO_SYS SYS_query_module;
MACRO_SYS SYS_quotactl;
MACRO_SYS SYS_read;
MACRO_SYS SYS_readahead;
MACRO_SYS SYS_readlink;
MACRO_SYS SYS_readlinkat;
MACRO_SYS SYS_readv;
MACRO_SYS SYS_reboot;
MACRO_SYS SYS_recvfrom;
MACRO_SYS SYS_recvmmsg;
MACRO_SYS SYS_recvmsg;
MACRO_SYS SYS_remap_file_pages;
MACRO_SYS SYS_removexattr;
MACRO_SYS SYS_rename;
MACRO_SYS SYS_renameat;
MACRO_SYS SYS_renameat2;
MACRO_SYS SYS_request_key;
MACRO_SYS SYS_restart_syscall;
MACRO_SYS SYS_rmdir;
MACRO_SYS SYS_rt_sigaction;
MACRO_SYS SYS_rt_sigpending;
MACRO_SYS SYS_rt_sigprocmask;
MACRO_SYS SYS_rt_sigqueueinfo;
MACRO_SYS SYS_rt_sigreturn;
MACRO_SYS SYS_rt_sigsuspend;
MACRO_SYS SYS_rt_sigtimedwait;
MACRO_SYS SYS_rt_tgsigqueueinfo;
MACRO_SYS SYS_sched_get_priority_max;
MACRO_SYS SYS_sched_get_priority_min;
MACRO_SYS SYS_sched_getaffinity;
MACRO_SYS SYS_sched_getattr;
MACRO_SYS SYS_sched_getparam;
MACRO_SYS SYS_sched_getscheduler;
MACRO_SYS SYS_sched_rr_get_interval;
MACRO_SYS SYS_sched_setaffinity;
MACRO_SYS SYS_sched_setattr;
MACRO_SYS SYS_sched_setparam;
MACRO_SYS SYS_sched_setscheduler;
MACRO_SYS SYS_sched_yield;
MACRO_SYS SYS_seccomp;
MACRO_SYS SYS_security;
MACRO_SYS SYS_select;
MACRO_SYS SYS_semctl;
MACRO_SYS SYS_semget;
MACRO_SYS SYS_semop;
MACRO_SYS SYS_semtimedop;
MACRO_SYS SYS_sendfile;
MACRO_SYS SYS_sendmmsg;
MACRO_SYS SYS_sendmsg;
MACRO_SYS SYS_sendto;
MACRO_SYS SYS_set_mempolicy;
MACRO_SYS SYS_set_robust_list;
MACRO_SYS SYS_set_thread_area;
MACRO_SYS SYS_set_tid_address;
MACRO_SYS SYS_setdomainname;
MACRO_SYS SYS_setfsgid;
MACRO_SYS SYS_setfsuid;
MACRO_SYS SYS_setgid;
MACRO_SYS SYS_setgroups;
MACRO_SYS SYS_sethostname;
MACRO_SYS SYS_setitimer;
MACRO_SYS SYS_setns;
MACRO_SYS SYS_setpgid;
MACRO_SYS SYS_setpriority;
MACRO_SYS SYS_setregid;
MACRO_SYS SYS_setresgid;
MACRO_SYS SYS_setresuid;
MACRO_SYS SYS_setreuid;
MACRO_SYS SYS_setrlimit;
MACRO_SYS SYS_setsid;
MACRO_SYS SYS_setsockopt;
MACRO_SYS SYS_settimeofday;
MACRO_SYS SYS_setuid;
MACRO_SYS SYS_setxattr;
MACRO_SYS SYS_shmat;
MACRO_SYS SYS_shmctl;
MACRO_SYS SYS_shmdt;
MACRO_SYS SYS_shmget;
MACRO_SYS SYS_shutdown;
MACRO_SYS SYS_sigaltstack;
MACRO_SYS SYS_signalfd;
MACRO_SYS SYS_signalfd4;
MACRO_SYS SYS_socket;
MACRO_SYS SYS_socketpair;
MACRO_SYS SYS_splice;
MACRO_SYS SYS_stat;
MACRO_SYS SYS_statfs;
MACRO_SYS SYS_swapoff;
MACRO_SYS SYS_swapon;
MACRO_SYS SYS_symlink;
MACRO_SYS SYS_symlinkat;
MACRO_SYS SYS_sync;
MACRO_SYS SYS_sync_file_range;
MACRO_SYS SYS_syncfs;
MACRO_SYS SYS_sysfs;
MACRO_SYS SYS_sysinfo;
MACRO_SYS SYS_syslog;
MACRO_SYS SYS_tee;
MACRO_SYS SYS_tgkill;
MACRO_SYS SYS_time;
MACRO_SYS SYS_timer_create;
MACRO_SYS SYS_timer_delete;
MACRO_SYS SYS_timer_getoverrun;
MACRO_SYS SYS_timer_gettime;
MACRO_SYS SYS_timer_settime;
MACRO_SYS SYS_timerfd_create;
MACRO_SYS SYS_timerfd_gettime;
MACRO_SYS SYS_timerfd_settime;
MACRO_SYS SYS_times;
MACRO_SYS SYS_tkill;
MACRO_SYS SYS_truncate;
MACRO_SYS SYS_tuxcall;
MACRO_SYS SYS_umask;
MACRO_SYS SYS_umount2;
MACRO_SYS SYS_uname;
MACRO_SYS SYS_unlink;
MACRO_SYS SYS_unlinkat;
MACRO_SYS SYS_unshare;
MACRO_SYS SYS_uselib;
MACRO_SYS SYS_userfaultfd;
MACRO_SYS SYS_ustat;
MACRO_SYS SYS_utime;
MACRO_SYS SYS_utimensat;
MACRO_SYS SYS_utimes;
MACRO_SYS SYS_vfork;
MACRO_SYS SYS_vhangup;
MACRO_SYS SYS_vmsplice;
MACRO_SYS SYS_vserver;
MACRO_SYS SYS_wait4;
MACRO_SYS SYS_waitid;
MACRO_SYS SYS_write;
MACRO_SYS SYS_writev;
MACRO___NR __NR__sysctl;
MACRO___NR __NR_accept;
MACRO___NR __NR_accept4;
MACRO___NR __NR_access;
MACRO___NR __NR_acct;
MACRO___NR __NR_add_key;
MACRO___NR __NR_adjtimex;
MACRO___NR __NR_afs_syscall;
MACRO___NR __NR_alarm;
MACRO___NR __NR_arch_prctl;
MACRO___NR __NR_bind;
MACRO___NR __NR_bpf;
MACRO___NR __NR_brk;
MACRO___NR __NR_capget;
MACRO___NR __NR_capset;
MACRO___NR __NR_chdir;
MACRO___NR __NR_chmod;
MACRO___NR __NR_chown;
MACRO___NR __NR_chroot;
MACRO___NR __NR_clock_adjtime;
MACRO___NR __NR_clock_getres;
MACRO___NR __NR_clock_gettime;
MACRO___NR __NR_clock_nanosleep;
MACRO___NR __NR_clock_settime;
MACRO___NR __NR_clone;
MACRO___NR __NR_close;
MACRO___NR __NR_connect;
MACRO___NR __NR_copy_file_range;
MACRO___NR __NR_creat;
MACRO___NR __NR_create_module;
MACRO___NR __NR_delete_module;
MACRO___NR __NR_dup;
MACRO___NR __NR_dup2;
MACRO___NR __NR_dup3;
MACRO___NR __NR_epoll_create;
MACRO___NR __NR_epoll_create1;
MACRO___NR __NR_epoll_ctl;
MACRO___NR __NR_epoll_ctl_old;
MACRO___NR __NR_epoll_pwait;
MACRO___NR __NR_epoll_wait;
MACRO___NR __NR_epoll_wait_old;
MACRO___NR __NR_eventfd;
MACRO___NR __NR_eventfd2;
MACRO___NR __NR_execve;
MACRO___NR __NR_execveat;
MACRO___NR __NR_exit;
MACRO___NR __NR_exit_group;
MACRO___NR __NR_faccessat;
MACRO___NR __NR_fadvise64;
MACRO___NR __NR_fallocate;
MACRO___NR __NR_fanotify_init;
MACRO___NR __NR_fanotify_mark;
MACRO___NR __NR_fchdir;
MACRO___NR __NR_fchmod;
MACRO___NR __NR_fchmodat;
MACRO___NR __NR_fchown;
MACRO___NR __NR_fchownat;
MACRO___NR __NR_fcntl;
MACRO___NR __NR_fdatasync;
MACRO___NR __NR_fgetxattr;
MACRO___NR __NR_finit_module;
MACRO___NR __NR_flistxattr;
MACRO___NR __NR_flock;
MACRO___NR __NR_fork;
MACRO___NR __NR_fremovexattr;
MACRO___NR __NR_fsetxattr;
MACRO___NR __NR_fstat;
MACRO___NR __NR_fstatfs;
MACRO___NR __NR_fsync;
MACRO___NR __NR_ftruncate;
MACRO___NR __NR_futex;
MACRO___NR __NR_futimesat;
MACRO___NR __NR_get_kernel_syms;
MACRO___NR __NR_get_mempolicy;
MACRO___NR __NR_get_robust_list;
MACRO___NR __NR_get_thread_area;
MACRO___NR __NR_getcpu;
MACRO___NR __NR_getcwd;
MACRO___NR __NR_getdents;
MACRO___NR __NR_getdents64;
MACRO___NR __NR_getegid;
MACRO___NR __NR_geteuid;
MACRO___NR __NR_getgid;
MACRO___NR __NR_getgroups;
MACRO___NR __NR_getitimer;
MACRO___NR __NR_getpeername;
MACRO___NR __NR_getpgid;
MACRO___NR __NR_getpgrp;
MACRO___NR __NR_getpid;
MACRO___NR __NR_getpmsg;
MACRO___NR __NR_getppid;
MACRO___NR __NR_getpriority;
MACRO___NR __NR_getrandom;
MACRO___NR __NR_getresgid;
MACRO___NR __NR_getresuid;
MACRO___NR __NR_getrlimit;
MACRO___NR __NR_getrusage;
MACRO___NR __NR_getsid;
MACRO___NR __NR_getsockname;
MACRO___NR __NR_getsockopt;
MACRO___NR __NR_gettid;
MACRO___NR __NR_gettimeofday;
MACRO___NR __NR_getuid;
MACRO___NR __NR_getxattr;
MACRO___NR __NR_init_module;
MACRO___NR __NR_inotify_add_watch;
MACRO___NR __NR_inotify_init;
MACRO___NR __NR_inotify_init1;
MACRO___NR __NR_inotify_rm_watch;
MACRO___NR __NR_io_cancel;
MACRO___NR __NR_io_destroy;
MACRO___NR __NR_io_getevents;
MACRO___NR __NR_io_setup;
MACRO___NR __NR_io_submit;
MACRO___NR __NR_ioctl;
MACRO___NR __NR_ioperm;
MACRO___NR __NR_iopl;
MACRO___NR __NR_ioprio_get;
MACRO___NR __NR_ioprio_set;
MACRO___NR __NR_kcmp;
MACRO___NR __NR_kexec_file_load;
MACRO___NR __NR_kexec_load;
MACRO___NR __NR_keyctl;
MACRO___NR __NR_kill;
MACRO___NR __NR_lchown;
MACRO___NR __NR_lgetxattr;
MACRO___NR __NR_link;
MACRO___NR __NR_linkat;
MACRO___NR __NR_listen;
MACRO___NR __NR_listxattr;
MACRO___NR __NR_llistxattr;
MACRO___NR __NR_lookup_dcookie;
MACRO___NR __NR_lremovexattr;
MACRO___NR __NR_lseek;
MACRO___NR __NR_lsetxattr;
MACRO___NR __NR_lstat;
MACRO___NR __NR_madvise;
MACRO___NR __NR_mbind;
MACRO___NR __NR_membarrier;
MACRO___NR __NR_memfd_create;
MACRO___NR __NR_migrate_pages;
MACRO___NR __NR_mincore;
MACRO___NR __NR_mkdir;
MACRO___NR __NR_mkdirat;
MACRO___NR __NR_mknod;
MACRO___NR __NR_mknodat;
MACRO___NR __NR_mlock;
MACRO___NR __NR_mlock2;
MACRO___NR __NR_mlockall;
MACRO___NR __NR_mmap;
MACRO___NR __NR_modify_ldt;
MACRO___NR __NR_mount;
MACRO___NR __NR_move_pages;
MACRO___NR __NR_mprotect;
MACRO___NR __NR_mq_getsetattr;
MACRO___NR __NR_mq_notify;
MACRO___NR __NR_mq_open;
MACRO___NR __NR_mq_timedreceive;
MACRO___NR __NR_mq_timedsend;
MACRO___NR __NR_mq_unlink;
MACRO___NR __NR_mremap;
MACRO___NR __NR_msgctl;
MACRO___NR __NR_msgget;
MACRO___NR __NR_msgrcv;
MACRO___NR __NR_msgsnd;
MACRO___NR __NR_msync;
MACRO___NR __NR_munlock;
MACRO___NR __NR_munlockall;
MACRO___NR __NR_munmap;
MACRO___NR __NR_name_to_handle_at;
MACRO___NR __NR_nanosleep;
MACRO___NR __NR_newfstatat;
MACRO___NR __NR_nfsservctl;
MACRO___NR __NR_open;
MACRO___NR __NR_open_by_handle_at;
MACRO___NR __NR_openat;
MACRO___NR __NR_pause;
MACRO___NR __NR_perf_event_open;
MACRO___NR __NR_personality;
MACRO___NR __NR_pipe;
MACRO___NR __NR_pipe2;
MACRO___NR __NR_pivot_root;
MACRO___NR __NR_poll;
MACRO___NR __NR_ppoll;
MACRO___NR __NR_prctl;
MACRO___NR __NR_pread64;
MACRO___NR __NR_preadv;
MACRO___NR __NR_preadv2;
MACRO___NR __NR_prlimit64;
MACRO___NR __NR_process_vm_readv;
MACRO___NR __NR_process_vm_writev;
MACRO___NR __NR_pselect6;
MACRO___NR __NR_ptrace;
MACRO___NR __NR_putpmsg;
MACRO___NR __NR_pwrite64;
MACRO___NR __NR_pwritev;
MACRO___NR __NR_pwritev2;
MACRO___NR __NR_query_module;
MACRO___NR __NR_quotactl;
MACRO___NR _NR_read;
MACRO___NR __NR_readahead;
MACRO___NR __NR_readlink;
MACRO___NR __NR_readlinkat;
MACRO___NR __NR_readv;
MACRO___NR __NR_reboot;
MACRO___NR __NR_recvfrom;
MACRO___NR __NR_recvmmsg;
MACRO___NR __NR_recvmsg;
MACRO___NR __NR_remap_file_pages;
MACRO___NR __NR_removexattr;
MACRO___NR __NR_rename;
MACRO___NR __NR_renameat;
MACRO___NR __NR_renameat2;
MACRO___NR __NR_request_key;
MACRO___NR __NR_restart_syscall;
MACRO___NR __NR_rmdir;
MACRO___NR __NR_rt_sigaction;
MACRO___NR __NR_rt_sigpending;
MACRO___NR __NR_rt_sigprocmask;
MACRO___NR __NR_rt_sigqueueinfo;
MACRO___NR __NR_rt_sigreturn;
MACRO___NR __NR_rt_sigsuspend;
MACRO___NR __NR_rt_sigtimedwait;
MACRO___NR __NR_rt_tgsigqueueinfo;
MACRO___NR __NR_sched_get_priority_max;
MACRO___NR __NR_sched_get_priority_min;
MACRO___NR __NR_sched_getaffinity;
MACRO___NR __NR_sched_getattr;
MACRO___NR __NR_sched_getparam;
MACRO___NR __NR_sched_getscheduler;
MACRO___NR __NR_sched_rr_get_interval;
MACRO___NR __NR_sched_setaffinity;
MACRO___NR __NR_sched_setattr;
MACRO___NR __NR_sched_setparam;
MACRO___NR __NR_sched_setscheduler;
MACRO___NR __NR_sched_yield;
MACRO___NR __NR_seccomp;
MACRO___NR __NR_security;
MACRO___NR __NR_select;
MACRO___NR __NR_semctl;
MACRO___NR __NR_semget;
MACRO___NR __NR_semop;
MACRO___NR __NR_semtimedop;
MACRO___NR __NR_sendfile;
MACRO___NR __NR_sendmmsg;
MACRO___NR __NR_sendmsg;
MACRO___NR __NR_sendto;
MACRO___NR __NR_set_mempolicy;
MACRO___NR __NR_set_robust_list;
MACRO___NR __NR_set_thread_area;
MACRO___NR __NR_set_tid_address;
MACRO___NR __NR_setdomainname;
MACRO___NR __NR_setfsgid;
MACRO___NR __NR_setfsuid;
MACRO___NR __NR_setgid;
MACRO___NR __NR_setgroups;
MACRO___NR __NR_sethostname;
MACRO___NR __NR_setitimer;
MACRO___NR __NR_setns;
MACRO___NR __NR_setpgid;
MACRO___NR __NR_setpriority;
MACRO___NR __NR_setregid;
MACRO___NR __NR_setresgid;
MACRO___NR __NR_setresuid;
MACRO___NR __NR_setreuid;
MACRO___NR __NR_setrlimit;
MACRO___NR __NR_setsid;
MACRO___NR __NR_setsockopt;
MACRO___NR __NR_settimeofday;
MACRO___NR __NR_setuid;
MACRO___NR __NR_setxattr;
MACRO___NR __NR_shmat;
MACRO___NR __NR_shmctl;
MACRO___NR __NR_shmdt;
MACRO___NR __NR_shmget;
MACRO___NR __NR_shutdown;
MACRO___NR __NR_sigaltstack;
MACRO___NR __NR_signalfd;
MACRO___NR __NR_signalfd4;
MACRO___NR __NR_socket;
MACRO___NR __NR_socketpair;
MACRO___NR __NR_splice;
MACRO___NR __NR_stat;
MACRO___NR __NR_statfs;
MACRO___NR __NR_swapoff;
MACRO___NR __NR_swapon;
MACRO___NR __NR_symlink;
MACRO___NR __NR_symlinkat;
MACRO___NR __NR_sync;
MACRO___NR __NR_sync_file_range;
MACRO___NR __NR_syncfs;
MACRO___NR __NR_sysfs;
MACRO___NR __NR_sysinfo;
MACRO___NR __NR_syslog;
MACRO___NR __NR_tee;
MACRO___NR __NR_tgkill;
MACRO___NR __NR_time;
MACRO___NR __NR_timer_create;
MACRO___NR __NR_timer_delete;
MACRO___NR __NR_timer_getoverrun;
MACRO___NR __NR_timer_gettime;
MACRO___NR __NR_timer_settime;
MACRO___NR __NR_timerfd_create;
MACRO___NR __NR_timerfd_gettime;
MACRO___NR __NR_timerfd_settime;
MACRO___NR __NR_times;
MACRO___NR __NR_tkill;
MACRO___NR __NR_truncate;
MACRO___NR __NR_tuxcall;
MACRO___NR __NR_umask;
MACRO___NR __NR_umount2;
MACRO___NR __NR_uname;
MACRO___NR __NR_unlink;
MACRO___NR __NR_unlinkat;
MACRO___NR __NR_unshare;
MACRO___NR __NR_uselib;
MACRO___NR __NR_userfaultfd;
MACRO___NR __NR_ustat;
MACRO___NR __NR_utime;
MACRO___NR __NR_utimensat;
MACRO___NR __NR_utimes;
MACRO___NR __NR_vfork;
MACRO___NR __NR_vhangup;
MACRO___NR __NR_vmsplice;
MACRO___NR __NR_vserver;
MACRO___NR __NR_wait4;
MACRO___NR __NR_waitid;
MACRO___NR __NR_write;
MACRO___NR __NR_writev;
__int64 sys32_quotactl(unsigned int cmd, const char *special, qid_t id, void *addr);
__int64 sys_accept(int, struct sockaddr *, int *);
__int64 sys_accept4(int, struct sockaddr *, int *, int);
__int64 sys_access(const char *filename, int mode);
__int64 sys_acct(const char *name);
__int64 sys_add_key(const char *type, const char *description, const void *payload, size_t plen, key_serial_t destringid);
__int64 sys_adjtimex(struct timex *txc_p);
__int64 sys_alarm(unsigned int seconds);
__int64 sys_bdflush(int func, __int64 data);
__int64 sys_bind(int, struct sockaddr *, int);
__int64 sys_bpf(int cmd, union bpf_attr *attr, unsigned int size);
__int64 sys_brk(unsigned __int64 brk);
__int64 sys_capget(cap_user_header_t header, cap_user_data_t dataptr);
__int64 sys_capset(cap_user_header_t header, const cap_user_data_t data);
__int64 sys_chdir(const char *filename);
__int64 sys_chmod(const char *filename, umode_t mode);
__int64 sys_chown(const char *filename, uid_t user, gid_t group);
__int64 sys_chroot(const char *filename);
__int64 sys_clock_adjtime(clockid_t which_clock, struct timex *tx);
__int64 sys_clock_getres(clockid_t which_clock, struct timespec *tp);
__int64 sys_clock_gettime(clockid_t which_clock, struct timespec *tp);
__int64 sys_clock_nanosleep(clockid_t which_clock, int flags, const struct timespec *rqtp, struct timespec *rmtp);
__int64 sys_clock_settime(clockid_t which_clock, const struct timespec *tp);
__int64 sys_clone(unsigned __int64, unsigned __int64, int *, int *, unsigned __int64);
__int64 sys_close(unsigned int fd);
__int64 sys_connect(int, struct sockaddr *, int);
__int64 sys_copy_file_range(int fd_in, loff_t *off_in, int fd_out, loff_t *off_out, size_t len, unsigned int flags);
__int64 sys_creat(const char *pathname, umode_t mode);
__int64 sys_delete_module(const char *name_user, unsigned int flags);
__int64 sys_dup(unsigned int fildes);
__int64 sys_dup2(unsigned int oldfd, unsigned int newfd);
__int64 sys_dup3(unsigned int oldfd, unsigned int newfd, int flags);
__int64 sys_epoll_create(int size);
__int64 sys_epoll_create1(int flags);
__int64 sys_epoll_ctl(int epfd, int op, int fd, struct epoll_event *event);
__int64 sys_epoll_pwait(int epfd, struct epoll_event *events, int maxevents, int timeout, const sigset_t *sigmask, size_t sigsetsize);
__int64 sys_epoll_wait(int epfd, struct epoll_event *events, int maxevents, int timeout);
__int64 sys_eventfd(unsigned int count);
__int64 sys_eventfd2(unsigned int count, int flags);
__int64 sys_execve(const char *filename, const char *const *argv, const char *const *envp);
__int64 sys_execveat(int dfd, const char *filename, const char *const *argv, const char *const *envp, int flags);
__int64 sys_exit(int error_code);
__int64 sys_exit_group(int error_code);
__int64 sys_faccessat(int dfd, const char *filename, int mode);
__int64 sys_fadvise64(int fd, loff_t offset, size_t len, int advice);
__int64 sys_fadvise64_64(int fd, loff_t offset, loff_t len, int advice);
__int64 sys_fallocate(int fd, int mode, loff_t offset, loff_t len);
__int64 sys_fanotify_init(unsigned int flags, unsigned int event_f_flags);
__int64 sys_fanotify_mark(int fanotify_fd, unsigned int flags, u64 mask, int fd, const char *pathname);
__int64 sys_fchdir(unsigned int fd);
__int64 sys_fchmod(unsigned int fd, umode_t mode);
__int64 sys_fchmodat(int dfd, const char *filename, umode_t mode);
__int64 sys_fchown(unsigned int fd, uid_t user, gid_t group);
__int64 sys_fchownat(int dfd, const char *filename, uid_t user, gid_t group, int flag);
__int64 sys_fcntl(unsigned int fd, unsigned int cmd, unsigned __int64 arg);
__int64 sys_fdatasync(unsigned int fd);
__int64 sys_fgetxattr(int fd, const char *name, void *value, size_t size);
__int64 sys_finit_module(int fd, const char *uargs, int flags);
__int64 sys_flistxattr(int fd, char *list, size_t size);
__int64 sys_flock(unsigned int fd, unsigned int cmd);
__int64 sys_fork(void);
__int64 sys_fremovexattr(int fd, const char *name);
__int64 sys_fsetxattr(int fd, const char *name, const void *value, size_t size, int flags);
__int64 sys_fstat(unsigned int fd, struct __old_kernel_stat *statbuf);
__int64 sys_fstatfs(unsigned int fd, struct statfs *buf);
__int64 sys_fstatfs64(unsigned int fd, size_t sz, struct statfs64 *buf);
__int64 sys_fsync(unsigned int fd);
__int64 sys_ftruncate(unsigned int fd, unsigned __int64 length);
__int64 sys_futex(u32 *uaddr, int op, u32 val, struct timespec *utime, u32 *uaddr2, u32 val3);
__int64 sys_futimesat(int dfd, const char *filename, struct timeval *utimes);
__int64 sys_get_mempolicy(int *policy, unsigned __int64 *nmask, unsigned __int64 maxnode, unsigned __int64 addr, unsigned __int64 flags);
__int64 sys_get_robust_list(int pid, struct robust_list_head **head_ptr, size_t *len_ptr);
__int64 sys_getcpu(unsigned int *cpu, unsigned int *node, struct getcpu_cache *cache);
__int64 sys_getcwd(char *buf, unsigned __int64 size);
__int64 sys_getdents(unsigned int fd, struct linux_dirent *dirent, unsigned int count);
__int64 sys_getdents64(unsigned int fd, struct linux_dirent64 *dirent, unsigned int count);
__int64 sys_getegid(void);
__int64 sys_geteuid(void);
__int64 sys_getgid(void);
__int64 sys_getgroups(int gidsetsize, gid_t *grouplist);
__int64 sys_gethostname(char *name, int len);
__int64 sys_getitimer(int which, struct itimerval *value);
__int64 sys_getpeername(int, struct sockaddr *, int *);
__int64 sys_getpgid(pid_t pid);
__int64 sys_getpgrp(void);
__int64 sys_getpid(void);
__int64 sys_getppid(void);
__int64 sys_getpriority(int which, int who);
__int64 sys_getrandom(char *buf, size_t count, unsigned int flags);
__int64 sys_getresgid(gid_t *rgid, gid_t *egid, gid_t *sgid);
__int64 sys_getresuid(uid_t *ruid, uid_t *euid, uid_t *suid);
__int64 sys_getrlimit(unsigned int resource, struct rlimit *rlim);
__int64 sys_getrusage(int who, struct rusage *ru);
__int64 sys_getsid(pid_t pid);
__int64 sys_getsockname(int, struct sockaddr *, int *);
__int64 sys_getsockopt(int fd, int level, int optname, char *optval, int *optlen);
__int64 sys_gettid(void);
__int64 sys_gettimeofday(struct timeval *tv, struct timezone *tz);
__int64 sys_getuid(void);
__int64 sys_getxattr(const char *path, const char *name, void *value, size_t size);
__int64 sys_init_module(void *umod, unsigned __int64 len, const char *uargs);
__int64 sys_inotify_add_watch(int fd, const char *path, u32 mask);
__int64 sys_inotify_init(void);
__int64 sys_inotify_init1(int flags);
__int64 sys_inotify_rm_watch(int fd, __s32 wd);
__int64 sys_io_cancel(aio_context_t ctx_id, struct iocb *iocb, struct io_event *result);
__int64 sys_io_destroy(aio_context_t ctx);
__int64 sys_io_getevents(aio_context_t ctx_id, __int64 min_nr, __int64 nr, struct io_event *events, struct timespec *timeout);
__int64 sys_io_setup(unsigned int nr_reqs, aio_context_t *ctx);
__int64 sys_io_submit(aio_context_t, __int64, struct iocb **);
__int64 sys_ioctl(unsigned int fd, unsigned int cmd, unsigned __int64 arg);
__int64 sys_ioperm(unsigned __int64 from, unsigned __int64 num, int on);
__int64 sys_ioprio_get(int which, int who);
__int64 sys_ioprio_set(int which, int who, int ioprio);
__int64 sys_ipc(unsigned int call, int first, unsigned __int64 second, unsigned __int64 third, void *ptr, __int64 fifth);
__int64 sys_kcmp(pid_t pid1, pid_t pid2, int type, unsigned __int64 idx1, unsigned __int64 idx2);
__int64 sys_kexec_file_load(int kernel_fd, int initrd_fd, unsigned __int64 cmdline_len, const char *cmdline_ptr, unsigned __int64 flags);
__int64 sys_kexec_load(unsigned __int64 entry, unsigned __int64 nr_segments, struct kexec_segment *segments, unsigned __int64 flags);
__int64 sys_keyctl(int cmd, unsigned __int64 arg2, unsigned __int64 arg3, unsigned __int64 arg4, unsigned __int64 arg5);
__int64 sys_kill(pid_t pid, int sig);
__int64 sys_lchown(const char *filename, uid_t user, gid_t group);
__int64 sys_lgetxattr(const char *path, const char *name, void *value, size_t size);
__int64 sys_link(const char *oldname, const char *newname);
__int64 sys_linkat(int olddfd, const char *oldname, int newdfd, const char *newname, int flags);
__int64 sys_listen(int, int);
__int64 sys_listxattr(const char *path, char *list, size_t size);
__int64 sys_llistxattr(const char *path, char *list, size_t size);
__int64 sys_llseek(unsigned int fd, unsigned __int64 offset_high, unsigned __int64 offset_low, loff_t *result, unsigned int whence);
__int64 sys_lookup_dcookie(u64 cookie64, char *buf, size_t len);
__int64 sys_lremovexattr(const char *path, const char *name);
__int64 sys_lseek(unsigned int fd, off_t offset, unsigned int whence);
__int64 sys_lsetxattr(const char *path, const char *name, const void *value, size_t size, int flags);
__int64 sys_lstat(const char *filename, struct __old_kernel_stat *statbuf);
__int64 sys_madvise(unsigned __int64 start, size_t len, int behavior);
__int64 sys_mbind(unsigned __int64 start, unsigned __int64 len, unsigned __int64 mode, const unsigned __int64 *nmask, unsigned __int64 maxnode, unsigned int flags);
__int64 sys_membarrier(int cmd, int flags);
__int64 sys_memfd_create(const char *uname_ptr, unsigned int flags);
__int64 sys_migrate_pages(pid_t pid, unsigned __int64 maxnode, const unsigned __int64 *from, const unsigned __int64 *to);
__int64 sys_mincore(unsigned __int64 start, size_t len, unsigned __int8 *vec);
__int64 sys_mkdir(const char *pathname, umode_t mode);
__int64 sys_mkdirat(int dfd, const char *pathname, umode_t mode);
__int64 sys_mknod(const char *filename, umode_t mode, unsigned int dev);
__int64 sys_mknodat(int dfd, const char *filename, umode_t mode, unsigned int dev);
__int64 sys_mlock(unsigned __int64 start, size_t len);
__int64 sys_mlock2(unsigned __int64 start, size_t len, int flags);
__int64 sys_mlockall(int flags);
__int64 sys_mmap_pgoff(unsigned __int64 addr, unsigned __int64 len, unsigned __int64 prot, unsigned __int64 flags, unsigned __int64 fd, unsigned __int64 pgoff);
__int64 sys_mount(char *dev_name, char *dir_name, char *type, unsigned __int64 flags, void *data);
__int64 sys_move_pages(pid_t pid, unsigned __int64 nr_pages, const void **pages, const int *nodes, int *status, int flags);
__int64 sys_mprotect(unsigned __int64 start, size_t len, unsigned __int64 prot);
__int64 sys_mq_getsetattr(mqd_t mqdes, const struct mq_attr *mqstat, struct mq_attr *omqstat);
__int64 sys_mq_notify(mqd_t mqdes, const struct sigevent *notification);
__int64 sys_mq_open(const char *name, int oflag, umode_t mode, struct mq_attr *attr);
__int64 sys_mq_timedreceive(mqd_t mqdes, char *msg_ptr, size_t msg_len, unsigned int *msg_prio, const struct timespec *abs_timeout);
__int64 sys_mq_timedsend(mqd_t mqdes, const char *msg_ptr, size_t msg_len, unsigned int msg_prio, const struct timespec *abs_timeout);
__int64 sys_mq_unlink(const char *name);
__int64 sys_mremap(unsigned __int64 addr, unsigned __int64 old_len, unsigned __int64 new_len, unsigned __int64 flags, unsigned __int64 new_addr);
__int64 sys_msgctl(int msqid, int cmd, struct msqid_ds *buf);
__int64 sys_msgget(key_t key, int msgflg);
__int64 sys_msgrcv(int msqid, struct msgbuf *msgp, size_t msgsz, __int64 msgtyp, int msgflg);
__int64 sys_msgsnd(int msqid, struct msgbuf *msgp, size_t msgsz, int msgflg);
__int64 sys_msync(unsigned __int64 start, size_t len, int flags);
__int64 sys_munlock(unsigned __int64 start, size_t len);
__int64 sys_munlockall(void);
__int64 sys_munmap(unsigned __int64 addr, size_t len);
__int64 sys_name_to_handle_at(int dfd, const char *name, struct file_handle *handle, int *mnt_id, int flag);
__int64 sys_nanosleep(struct timespec *rqtp, struct timespec *rmtp);
__int64 sys_newfstat(unsigned int fd, struct stat *statbuf);
__int64 sys_newfstatat(int dfd, const char *filename, struct stat *statbuf, int flag);
__int64 sys_newlstat(const char *filename, struct stat *statbuf);
__int64 sys_newstat(const char *filename, struct stat *statbuf);
__int64 sys_newuname(struct new_utsname *name);
__int64 sys_ni_syscall(void);
__int64 sys_nice(int increment);
__int64 sys_old_getrlimit(unsigned int resource, struct rlimit *rlim);
__int64 sys_old_mmap(struct mmap_arg_struct *arg);
__int64 sys_old_readdir(unsigned int, struct old_linux_dirent *, unsigned int);
__int64 sys_old_select(struct sel_arg_struct *arg);
__int64 sys_oldumount(char *name);
__int64 sys_olduname(struct oldold_utsname *);
__int64 sys_open(const char *filename, int flags, umode_t mode);
__int64 sys_open_by_handle_at(int mountdirfd, struct file_handle *handle, int flags);
__int64 sys_openat(int dfd, const char *filename, int flags, umode_t mode);
__int64 sys_pause(void);
__int64 sys_pciconfig_iobase(__int64 which, unsigned __int64 bus, unsigned __int64 devfn);
__int64 sys_pciconfig_read(unsigned __int64 bus, unsigned __int64 dfn, unsigned __int64 off, unsigned __int64 len, void *buf);
__int64 sys_pciconfig_write(unsigned __int64 bus, unsigned __int64 dfn, unsigned __int64 off, unsigned __int64 len, void *buf);
__int64 sys_perf_event_open(struct perf_event_attr *attr_uptr, pid_t pid, int cpu, int group_fd, unsigned __int64 flags);
__int64 sys_personality(unsigned int personality);
__int64 sys_pipe(int *fildes);
__int64 sys_pipe2(int *fildes, int flags);
__int64 sys_pivot_root(const char *new_root, const char *put_old);
__int64 sys_poll(struct pollfd *ufds, unsigned int nfds, int timeout);
__int64 sys_ppoll(struct pollfd *, unsigned int, struct timespec *, const sigset_t *, size_t);
__int64 sys_prctl(int option, unsigned __int64 arg2, unsigned __int64 arg3, unsigned __int64 arg4, unsigned __int64 arg5);
__int64 sys_pread64(unsigned int fd, char *buf, size_t count, loff_t pos);
__int64 sys_preadv(unsigned __int64 fd, const struct iovec *vec, unsigned __int64 vlen, unsigned __int64 pos_l, unsigned __int64 pos_h);
__int64 sys_preadv2(unsigned __int64 fd, const struct iovec *vec, unsigned __int64 vlen, unsigned __int64 pos_l, unsigned __int64 pos_h, int flags);
__int64 sys_prlimit64(pid_t pid, unsigned int resource, const struct rlimit64 *new_rlim, struct rlimit64 *old_rlim);
__int64 sys_process_vm_readv(pid_t pid, const struct iovec *lvec, unsigned __int64 liovcnt, const struct iovec *rvec, unsigned __int64 riovcnt, unsigned __int64 flags);
__int64 sys_process_vm_writev(pid_t pid, const struct iovec *lvec, unsigned __int64 liovcnt, const struct iovec *rvec, unsigned __int64 riovcnt, unsigned __int64 flags);
__int64 sys_pselect6(int, fd_set *, fd_set *, fd_set *, struct timespec *, void *);
__int64 sys_ptrace(__int64 request, __int64 pid, unsigned __int64 addr, unsigned __int64 data);
__int64 sys_pwrite64(unsigned int fd, const char *buf, size_t count, loff_t pos);
__int64 sys_pwritev(unsigned __int64 fd, const struct iovec *vec, unsigned __int64 vlen, unsigned __int64 pos_l, unsigned __int64 pos_h);
__int64 sys_pwritev2(unsigned __int64 fd, const struct iovec *vec, unsigned __int64 vlen, unsigned __int64 pos_l, unsigned __int64 pos_h, int flags);
__int64 sys_quotactl(unsigned int cmd, const char *special, qid_t id, void *addr);
__int64 sys_read(unsigned int fd, char *buf, size_t count);
__int64 sys_readahead(int fd, loff_t offset, size_t count);
__int64 sys_readlink(const char *path, char *buf, int bufsiz);
__int64 sys_readlinkat(int dfd, const char *path, char *buf, int bufsiz);
__int64 sys_readv(unsigned __int64 fd, const struct iovec *vec, unsigned __int64 vlen);
__int64 sys_reboot(int magic1, int magic2, unsigned int cmd, void *arg);
__int64 sys_recv(int, void *, size_t, unsigned int);
__int64 sys_recvfrom(int, void *, size_t, unsigned int, struct sockaddr *, int *);
__int64 sys_recvmmsg(int fd, struct mmsghdr *msg, unsigned int vlen, unsigned int flags, struct timespec *timeout);
__int64 sys_recvmsg(int fd, struct user_msghdr *msg, unsigned int flags);
__int64 sys_remap_file_pages(unsigned __int64 start, unsigned __int64 size, unsigned __int64 prot, unsigned __int64 pgoff, unsigned __int64 flags);
__int64 sys_removexattr(const char *path, const char *name);
__int64 sys_rename(const char *oldname, const char *newname);
__int64 sys_renameat(int olddfd, const char *oldname, int newdfd, const char *newname);
__int64 sys_renameat2(int olddfd, const char *oldname, int newdfd, const char *newname, unsigned int flags);
__int64 sys_request_key(const char *type, const char *description, const char *callout_info, key_serial_t destringid);
__int64 sys_restart_syscall(void);
__int64 sys_rmdir(const char *pathname);
__int64 sys_rt_sigaction(int, const struct sigaction *, struct sigaction *, size_t);
__int64 sys_rt_sigpending(sigset_t *set, size_t sigsetsize);
__int64 sys_rt_sigprocmask(int how, sigset_t *set, sigset_t *oset, size_t sigsetsize);
__int64 sys_rt_sigqueueinfo(pid_t pid, int sig, siginfo_t *uinfo);
__int64 sys_rt_sigsuspend(sigset_t *unewset, size_t sigsetsize);
__int64 sys_rt_sigtimedwait(const sigset_t *uthese, siginfo_t *uinfo, const struct timespec *uts, size_t sigsetsize);
__int64 sys_rt_tgsigqueueinfo(pid_t tgid, pid_t pid, int sig, siginfo_t *uinfo);
__int64 sys_sched_get_priority_max(int policy);
__int64 sys_sched_get_priority_min(int policy);
__int64 sys_sched_getaffinity(pid_t pid, unsigned int len, unsigned __int64 *user_mask_ptr);
__int64 sys_sched_getattr(pid_t pid, struct sched_attr *attr, unsigned int size, unsigned int flags);
__int64 sys_sched_getparam(pid_t pid, struct sched_param *param);
__int64 sys_sched_getscheduler(pid_t pid);
__int64 sys_sched_rr_get_interval(pid_t pid, struct timespec *interval);
__int64 sys_sched_setaffinity(pid_t pid, unsigned int len, unsigned __int64 *user_mask_ptr);
__int64 sys_sched_setattr(pid_t pid, struct sched_attr *attr, unsigned int flags);
__int64 sys_sched_setparam(pid_t pid, struct sched_param *param);
__int64 sys_sched_setscheduler(pid_t pid, int policy, struct sched_param *param);
__int64 sys_sched_yield(void);
__int64 sys_seccomp(unsigned int op, unsigned int flags, const char *uargs);
__int64 sys_select(int n, fd_set *inp, fd_set *outp, fd_set *exp, struct timeval *tvp);
__int64 sys_semctl(int semid, int semnum, int cmd, unsigned __int64 arg);
__int64 sys_semget(key_t key, int nsems, int semflg);
__int64 sys_semop(int semid, struct sembuf *sops, unsigned int nsops);
__int64 sys_semtimedop(int semid, struct sembuf *sops, unsigned int nsops, const struct timespec *timeout);
__int64 sys_send(int, void *, size_t, unsigned int);
__int64 sys_sendfile(int out_fd, int in_fd, off_t *offset, size_t count);
__int64 sys_sendfile64(int out_fd, int in_fd, loff_t *offset, size_t count);
__int64 sys_sendmmsg(int fd, struct mmsghdr *msg, unsigned int vlen, unsigned int flags);
__int64 sys_sendmsg(int fd, struct user_msghdr *msg, unsigned int flags);
__int64 sys_sendto(int, void *, size_t, unsigned int, struct sockaddr *, int);
__int64 sys_set_mempolicy(int mode, const unsigned __int64 *nmask, unsigned __int64 maxnode);
__int64 sys_set_robust_list(struct robust_list_head *head, size_t len);
__int64 sys_set_tid_address(int *tidptr);
__int64 sys_setdomainname(char *name, int len);
__int64 sys_setfsgid(gid_t gid);
__int64 sys_setfsuid(uid_t uid);
__int64 sys_setgid(gid_t gid);
__int64 sys_setgroups(int gidsetsize, gid_t *grouplist);
__int64 sys_sethostname(char *name, int len);
__int64 sys_setitimer(int which, struct itimerval *value, struct itimerval *ovalue);
__int64 sys_setns(int fd, int nstype);
__int64 sys_setpgid(pid_t pid, pid_t pgid);
__int64 sys_setpriority(int which, int who, int niceval);
__int64 sys_setregid(gid_t rgid, gid_t egid);
__int64 sys_setresgid(gid_t rgid, gid_t egid, gid_t sgid);
__int64 sys_setresuid(uid_t ruid, uid_t euid, uid_t suid);
__int64 sys_setreuid(uid_t ruid, uid_t euid);
__int64 sys_setrlimit(unsigned int resource, struct rlimit *rlim);
__int64 sys_setsid(void);
__int64 sys_setsockopt(int fd, int level, int optname, char *optval, int optlen);
__int64 sys_settimeofday(struct timeval *tv, struct timezone *tz);
__int64 sys_setuid(uid_t uid);
__int64 sys_setxattr(const char *path, const char *name, const void *value, size_t size, int flags);
__int64 sys_sgetmask(void);
__int64 sys_shmat(int shmid, char *shmaddr, int shmflg);
__int64 sys_shmctl(int shmid, int cmd, struct shmid_ds *buf);
__int64 sys_shmdt(char *shmaddr);
__int64 sys_shmget(key_t key, size_t size, int flag);
__int64 sys_shutdown(int, int);
__int64 sys_sigaltstack(const struct sigaltstack *uss, struct sigaltstack *uoss);
__int64 sys_signal(int sig, __sighandler_t handler);
__int64 sys_signalfd(int ufd, sigset_t *user_mask, size_t sizemask);
__int64 sys_signalfd4(int ufd, sigset_t *user_mask, size_t sizemask, int flags);
__int64 sys_sigpending(old_sigset_t *set);
__int64 sys_sigprocmask(int how, old_sigset_t *set, old_sigset_t *oset);
__int64 sys_socket(int, int, int);
__int64 sys_socketcall(int call, unsigned __int64 *args);
__int64 sys_socketpair(int, int, int, int *);
__int64 sys_splice(int fd_in, loff_t *off_in, int fd_out, loff_t *off_out, size_t len, unsigned int flags);
__int64 sys_spu_create(const char *name, unsigned int flags, umode_t mode, int fd);
__int64 sys_spu_run(int fd, __u32 *unpc, __u32 *ustatus);
__int64 sys_ssetmask(int newmask);
__int64 sys_stat(const char *filename, struct __old_kernel_stat *statbuf);
__int64 sys_statfs(const char *path, struct statfs *buf);
__int64 sys_statfs64(const char *path, size_t sz, struct statfs64 *buf);
__int64 sys_stime(time_t *tptr);
__int64 sys_swapoff(const char *specialfile);
__int64 sys_swapon(const char *specialfile, int swap_flags);
__int64 sys_symlink(const char *old, const char *new);
__int64 sys_symlinkat(const char *oldname, int newdfd, const char *newname);
__int64 sys_sync(void);
__int64 sys_sync_file_range(int fd, loff_t offset, loff_t nbytes, unsigned int flags);
__int64 sys_sync_file_range2(int fd, unsigned int flags, loff_t offset, loff_t nbytes);
__int64 sys_syncfs(int fd);
__int64 sys_sysctl(struct __sysctl_args *args);
__int64 sys_sysfs(int option, unsigned __int64 arg1, unsigned __int64 arg2);
__int64 sys_sysinfo(struct sysinfo *info);
__int64 sys_syslog(int type, char *buf, int len);
__int64 sys_tee(int fdin, int fdout, size_t len, unsigned int flags);
__int64 sys_tgkill(pid_t tgid, pid_t pid, int sig);
__int64 sys_time(time_t *tloc);
__int64 sys_timer_create(clockid_t which_clock, struct sigevent *timer_event_spec, timer_t *created_timer_id);
__int64 sys_timer_delete(timer_t timer_id);
__int64 sys_timer_getoverrun(timer_t timer_id);
__int64 sys_timer_gettime(timer_t timer_id, struct itimerspec *setting);
__int64 sys_timer_settime(timer_t timer_id, int flags, const struct itimerspec *new_setting, struct itimerspec *old_setting);
__int64 sys_timerfd_create(int clockid, int flags);
__int64 sys_timerfd_gettime(int ufd, struct itimerspec *otmr);
__int64 sys_timerfd_settime(int ufd, int flags, const struct itimerspec *utmr, struct itimerspec *otmr);
__int64 sys_times(struct tms *tbuf);
__int64 sys_tkill(pid_t pid, int sig);
__int64 sys_truncate(const char *path, __int64 length);
__int64 sys_umask(int mask);
__int64 sys_umount(char *name, int flags);
__int64 sys_uname(struct old_utsname *);
__int64 sys_unlink(const char *pathname);
__int64 sys_unlinkat(int dfd, const char *pathname, int flag);
__int64 sys_unshare(unsigned __int64 unshare_flags);
__int64 sys_uselib(const char *library);
__int64 sys_userfaultfd(int flags);
__int64 sys_ustat(unsigned int dev, struct ustat *ubuf);
__int64 sys_utime(char *filename, struct utimbuf *times);
__int64 sys_utimensat(int dfd, const char *filename, struct timespec *utimes, int flags);
__int64 sys_utimes(char *filename, struct timeval *utimes);
__int64 sys_vfork(void);
__int64 sys_vhangup(void);
__int64 sys_vmsplice(int fd, const struct iovec *iov, unsigned __int64 nr_segs, unsigned int flags);
__int64 sys_wait4(pid_t pid, int *stat_addr, int options, struct rusage *ru);
__int64 sys_waitid(int which, pid_t pid, struct siginfo *infop, int options, struct rusage *ru);
__int64 sys_waitpid(pid_t pid, int *stat_addr, int options);
__int64 sys_write(unsigned int fd, const char *buf, size_t count);
__int64 sys_writev(unsigned __int64 fd, const struct iovec *vec, unsigned __int64 vlen);
