struct $49112922E8D3FA36A9D9A6626290371D {int x1;int y1;int x2;int y2;int border;int background;int borderstyle;int bordercolor;};
struct $5D287BBCEE976282B532DF578B48FE30 {char title[70];int titlecolor;int justify;};
struct $708EB2C8D47456B2C174260C174C4FAC {int grid;int gridstyle;_titletype axistitle;int axiscolor;int labeled;int rangetype;float logbase;int autoscale;float scalemin;float scalemax;float scalefactor;_titletype scaletitle;float ticinterval;int ticformat;int ticdecimals;};
struct $92231A9D73296187DBEF5930036406A4 {unsigned int color;unsigned int style;_fillmap fill;char plotchar;};
struct $95C3CB16824D66B4D3D3A1F25D6CE7B3 {int legend;int place;int textcolor;int autosize;_windowtype legendwindow;};
struct $F8345695F188CA62739CDC0353D986D0 {int charttype;int chartstyle;_windowtype chartwindow;_windowtype datawindow;_titletype maintitle;_titletype subtitle;_axistype xaxis;_axistype yaxis;_legendtype legend;};
struct BYTEREGS {unsigned __int8 al;unsigned __int8 ah;unsigned __int8 bl;unsigned __int8 bh;unsigned __int8 cl;unsigned __int8 ch;unsigned __int8 dl;unsigned __int8 dh;};
struct DOSERROR {int exterror;char c_class;char action;char locus;};
typedef struct _iobuf FILE;
enum MACRO_BUFSIZ {BUFSIZ = 512,};
enum MACRO_CHAR {CHAR_BIT = 8,};
enum MACRO_CLK {CLK_TCK = 1000,};
enum MACRO_CLOCKS {CLOCKS_PER_SEC = 1000,};
enum MACRO_DBL {DBL_DIG = 15,DBL_MANT_DIG = 53,DBL_MAX_10_EXP = 308,DBL_MAX_EXP = 1024,DBL_MIN_10_EXP = -307,DBL_MIN_EXP = -1021,};
enum MACRO_DBL_RADIX {DBL_RADIX = 2,DBL_ROUNDS = 1,};
enum MACRO_DOMAIN {DOMAIN = 1,SING = 2,};
enum MACRO_DOS_CW {CW_DEFAULT = 4914,};
enum MACRO_DOS_EM {EM_INVALID = 1,EM_DENORMAL = 2,EM_ZERODIVIDE = 4,EM_OVERFLOW = 8,EM_UNDERFLOW = 16,EM_INEXACT = 32,};
enum MACRO_DOS_LC {LC_ALL = 0,LC_COLLATE = 1,LC_CTYPE = 2,LC_MONETARY = 3,LC_NUMERIC = 4,LC_TIME = 5,LC_MIN = 0,LC_MAX = 5,};
enum MACRO_DOS_MAX {SCHAR_MAX = 127,UCHAR_MAX = 255,CHAR_MAX = 127,MB_LEN_MAX = 2,SHRT_MAX = 32767,USHRT_MAX = -1,INT_MAX = 32767,UINT_MAX = -1,LONG_MAX = -1,ULONG_MAX = -1,FILENAME_MAX = 128,FOPEN_MAX = 18,TMP_MAX = 32767,RAND_MAX = 32767,};
enum MACRO_DOS_PC {PC_24 = 0,PC_53 = 512,PC_64 = 768,};
enum MACRO_DOS_RC {RC_CHOP = 3072,RC_UP = 2048,RC_DOWN = 1024,RC_NEAR = 0,};
enum MACRO_DOS_SW {SW_INVALID = 1,SW_DENORMAL = 2,SW_ZERODIVIDE = 4,SW_OVERFLOW = 8,SW_UNDERFLOW = 16,SW_INEXACT = 32,SW_UNEMULATED = 64,SW_SQRTNEG = 128,SW_STACKOVERFLOW = 512,SW_STACKUNDERFLOW = 1024,};
enum MACRO_EOF {EOF = -1,};
enum MACRO_ERRNO {EZERO = 0,EPERM = 1,ENOENT = 2,ESRCH = 3,EINTR = 4,EIO = 5,ENXIO = 6,E2BIG = 7,ENOEXEC = 8,EBADF = 9,ECHILD = 10,EAGAIN = 11,ENOMEM = 12,EACCES = 13,EFAULT = 14,ENOTBLK = 15,EBUSY = 16,EEXIST = 17,EXDEV = 18,ENODEV = 19,ENOTDIR = 20,EISDIR = 21,EINVAL = 22,ENFILE = 23,EMFILE = 24,ENOTTY = 25,ETXTBSY = 26,EFBIG = 27,ENOSPC = 28,ESPIPE = 29,EROFS = 30,EMLINK = 31,EPIPE = 32,EDOM = 33,ERANGE = 34,EUCLEAN = 35,EDEADLOCK = 36,};
enum MACRO_EXIT {EXIT_SUCCESS = 0,EXIT_FAILURE = 1,};
enum MACRO_FILE_MODE {S_IFMT = -4096,S_IFDIR = 16384,S_IFCHR = 8192,S_IFREG = -32768,S_IREAD = 256,S_IWRITE = 128,S_IEXEC = 64,};
enum MACRO_FLT {FLT_DIG = 6,FLT_GUARD = 0,FLT_MANT_DIG = 24,FLT_MAX_10_EXP = 38,FLT_MAX_EXP = 128,FLT_MIN_10_EXP = -37,FLT_MIN_EXP = -125,FLT_NORMALIZE = 0,FLT_RADIX = 2,FLT_ROUNDS = 1,};
enum MACRO_FPE {FPE_INVALID = 129,FPE_DENORMAL = 130,FPE_ZERODIVIDE = 131,FPE_OVERFLOW = 132,FPE_UNDERFLOW = 133,FPE_INEXACT = 134,FPE_UNEMULATED = 135,FPE_SQRTNEG = 136,FPE_STACKOVERFLOW = 138,FPE_STACKUNDERFLOW = 139,FPE_EXPLICITGEN = 140,};
enum MACRO_IC {IC_AFFINE = 4096,IC_PROJECTIVE = 0,};
enum MACRO_LDBL {LDBL_DIG = 18,LDBL_MANT_DIG = 64,LDBL_MAX_10_EXP = 4932,LDBL_MAX_EXP = 16384,LDBL_MIN_10_EXP = -4931,LDBL_MIN_EXP = -16381,};
enum MACRO_LDBL_RADIX {LDBL_RADIX = 2,LDBL_ROUNDS = 1,};
enum MACRO_LK {LK_UNLCK = 0,LK_LOCK = 1,LK_NBLCK = 2,LK_RLCK = 3,LK_NBRLCK = 4,};
enum MACRO_MCW {MCW_EM = 63,MCW_IC = 4096,};
enum MACRO_MCW_RC {MCW_RC = 3072,MCW_PC = 768,};
enum MACRO_MIN {SCHAR_MIN = -127,CHAR_MIN = -127,SHRT_MIN = -32767,INT_MIN = -32767,LONG_MIN = 1,};
enum MACRO_MODE {_DOS_MODE = 0,_OS2_MODE = 1,_WIN_MODE = 2,_REAL_MODE = 0,_PROT_MODE = 1,DOS_MODE = 0,OS2_MODE = 1,};
enum MACRO_NSIG {NSIG = 23,};
enum MACRO_NULL {NULL = 0,};
enum MACRO_O {O_RDONLY = 0,O_WRONLY = 1,O_RDWR = 2,O_APPEND = 8,O_CREAT = 256,O_TRUNC = 512,O_EXCL = 1024,O_TEXT = 16384,O_BINARY = -32768,O_NOINHERIT = 128,};
enum MACRO_OLD {OLD_P_OVERLAY = 2,};
enum MACRO_OVERFLOW {OVERFLOW = 3,UNDERFLOW = 4,};
enum MACRO_P {P_WAIT = 0,P_NOWAIT = 1,};
enum MACRO_PLOSS {PLOSS = 6,};
enum MACRO_P_NOWAITO {P_NOWAITO = 3,P_DETACH = 4,};
enum MACRO_SEEK {SEEK_CUR = 1,SEEK_END = 2,SEEK_SET = 0,};
enum MACRO_SH {SH_COMPAT = 0,SH_DENYRW = 16,SH_DENYWR = 32,SH_DENYRD = 48,SH_DENYNO = 64,};
enum MACRO_SIGNAL {SIGINT = 2,SIGILL = 4,SIGFPE = 8,SIGSEGV = 11,SIGTERM = 15,SIGABRT = 22,};
enum MACRO_SYS {SYS_OPEN = 20,};
enum MACRO_TLOSS {TLOSS = 5,};
enum MACRO__A {_A_NORMAL = 0x0,_A_RDONLY = 0x1,_A_HIDDEN = 0x2,_A_SYSTEM = 0x4,_A_VOLID = 0x8,_A_SUBDIR = 0x10,_A_ARCH = 0x20,};
enum MACRO__ANALOG {_ANALOG = 0x18,};
enum MACRO__BLACK {_BLACK = 0x0,_BLUE = 0x0,};
enum MACRO__BRIGHTWHITE {_BRIGHTWHITE = 0x3F3F,};
enum MACRO__BROWN {_BROWN = 0x152A,};
enum MACRO__COM {_COM_INIT = 0,_COM_SEND = 1,_COM_RECEIVE = 2,_COM_STATUS = 3,_COM_CHR7 = 2,_COM_CHR8 = 3,_COM_STOP1 = 0,_COM_STOP2 = 4,_COM_NOPARITY = 0,_COM_ODDPARITY = 8,_COM_EVENPARITY = 24,_COM_110 = 0,_COM_150 = 32,_COM_300 = 64,_COM_600 = 96,_COM_1200 = 128,_COM_2400 = 160,_COM_4800 = 192,_COM_9600 = 224,};
enum MACRO__CW {_CW_DEFAULT = 4914,};
enum MACRO__CYAN {_CYAN = 0x2A00,};
enum MACRO__DBL {_DBL_RADIX = 2,_DBL_ROUNDS = 1,};
enum MACRO__DEFAULTMODE {_DEFAULTMODE = -1,};
enum MACRO__DISK {_DISK_RESET = 0,_DISK_STATUS = 1,_DISK_READ = 2,_DISK_WRITE = 3,_DISK_VERIFY = 4,_DISK_FORMAT = 5,};
enum MACRO__DOMAIN {_DOMAIN = 1,_SING = 2,};
enum MACRO__EM {_EM_INVALID = 0x1,_EM_DENORMAL = 0x2,_EM_ZERODIVIDE = 0x4,_EM_OVERFLOW = 0x8,_EM_UNDERFLOW = 0x10,_EM_INEXACT = 0x20,};
enum MACRO__ERESNOCOLOR {_ERESNOCOLOR = 15,_ERESCOLOR = 16,};
enum MACRO__FPE {_FPE_INVALID = 0x81,_FPE_DENORMAL = 0x82,_FPE_ZERODIVIDE = 0x83,_FPE_OVERFLOW = 0x84,_FPE_UNDERFLOW = 0x85,_FPE_INEXACT = 0x86,_FPE_UNEMULATED = 0x87,_FPE_SQRTNEG = 0x88,_FPE_STACKOVERFLOW = 0x8A,_FPE_STACKUNDERFLOW = 0x8B,_FPE_EXPLICITGEN = 0x8C,};
enum MACRO__FREEENTRY {_FREEENTRY = 0,_USEDENTRY = 1,};
enum MACRO__GAND {_GAND = 1,};
enum MACRO__GBORDER {_GBORDER = 2,};
enum MACRO__GCLEARSCREEN {_GCLEARSCREEN = 0,_GVIEWPORT = 1,_GWINDOW = 2,};
enum MACRO__GCURSOROFF {_GCURSOROFF = 0,_GCURSORON = 1,};
enum MACRO__GFILLINTERIOR {_GFILLINTERIOR = 3,};
enum MACRO__GOR {_GOR = 0,_GXOR = 4,};
enum MACRO__GPRESET {_GPRESET = 2,};
enum MACRO__GPSET {_GPSET = 3,};
enum MACRO__GRAY {_GRAY = 0x1515,};
enum MACRO__GRCORRUPTEDFONTFILE {_GRCORRUPTEDFONTFILE = -7,};
enum MACRO__GREEN {_GREEN = 0x2A00,};
enum MACRO__GRFONTFILENOTFOUND {_GRFONTFILENOTFOUND = -5,};
enum MACRO__GRINSUFFICIENTMEMORY {_GRINSUFFICIENTMEMORY = -8,};
enum MACRO__GRINVALIDFONTFILE {_GRINVALIDFONTFILE = -6,};
enum MACRO__GRINVALIDIMAGEBUFFER {_GRINVALIDIMAGEBUFFER = -9,};
enum MACRO__GRINVALIDPARAMETER {_GRINVALIDPARAMETER = -4,};
enum MACRO__GRMODENOTSUPPORTED {_GRMODENOTSUPPORTED = -2,};
enum MACRO__GRNOOUTPUT {_GRNOOUTPUT = 1,_GRCLIPPED = 2,};
enum MACRO__GRNOTINPROPERMODE {_GRNOTINPROPERMODE = -3,};
enum MACRO__GROK {_GROK = 0,_GRERROR = -1,};
enum MACRO__GRPARAMETERALTERED {_GRPARAMETERALTERED = 3,_GRTEXTNOTSUPPORTED = 4,};
enum MACRO__GSCROLLDOWN {_GSCROLLDOWN = -1,};
enum MACRO__GSCROLLUP {_GSCROLLUP = 1,};
enum MACRO__GWRAPOFF {_GWRAPOFF = 0,_GWRAPON = 1,};
enum MACRO__HARDERR {_HARDERR_IGNORE = 0,_HARDERR_RETRY = 1,_HARDERR_ABORT = 2,_HARDERR_FAIL = 3,};
enum MACRO__HEAP {_HEAP_MAXREQ = 0xFFE8,};
enum MACRO__HEAPBADBEGIN {_HEAPBADBEGIN = -3,};
enum MACRO__HEAPBADNODE {_HEAPBADNODE = -4,};
enum MACRO__HEAPBADPTR {_HEAPBADPTR = -6,};
enum MACRO__HEAPEMPTY {_HEAPEMPTY = -1,};
enum MACRO__HEAPEND {_HEAPEND = -5,};
enum MACRO__HEAPOK {_HEAPOK = -2,};
enum MACRO__HRES16COLOR {_HRES16COLOR = 14,};
enum MACRO__HRESBW {_HRESBW = 6,};
enum MACRO__IC {_IC_AFFINE = 0x1000,_IC_PROJECTIVE = 0x0,};
enum MACRO__IOFBF {_IOFBF = 0x0,_IOLBF = 0x40,};
enum MACRO__IONBF {_IONBF = 0x4,_IOMYBUF = 0x8,_IOEOF = 0x10,_IOERR = 0x20,_IOSTRG = 0x40,_IORW = 0x80,};
enum MACRO__IOREAD {_IOREAD = 0x1,_IOWRT = 0x2,};
enum MACRO__JBLEN {_JBLEN = 9,};
enum MACRO__KEYBRD {_KEYBRD_READ = 0,_KEYBRD_READY = 1,_KEYBRD_SHIFTSTATUS = 2,};
enum MACRO__LDBL {_LDBL_RADIX = 2,_LDBL_ROUNDS = 1,};
enum MACRO__LIGHTBLUE {_LIGHTBLUE = 0x1515,};
enum MACRO__LIGHTCYAN {_LIGHTCYAN = 0x3F15,};
enum MACRO__LIGHTGREEN {_LIGHTGREEN = 0x3F15,};
enum MACRO__LIGHTMAGENTA {_LIGHTMAGENTA = 0x153F,};
enum MACRO__LIGHTRED {_LIGHTRED = 0x153F,};
enum MACRO__LIGHTYELLOW {_LIGHTYELLOW = 16191,};
enum MACRO__LK {_LK_UNLCK = 0,_LK_LOCK = 1,_LK_NBLCK = 2,_LK_RLCK = 3,_LK_NBRLCK = 4,};
enum MACRO__MAGENTA {_MAGENTA = 0x2A,};
enum MACRO__MAX {_MAX_PATH = 260,_MAX_DRIVE = 3,_MAX_DIR = 256,_MAX_FNAME = 256,_MAX_EXT = 256,};
enum MACRO__MAXCOLORMODE {_MAXCOLORMODE = -2,};
enum MACRO__MAXRESMODE {_MAXRESMODE = -3,};
enum MACRO__MAXTEXTROWS {_MAXTEXTROWS = -1,};
enum MACRO__MCW {_MCW_EM = 0x3F,};
enum MACRO__MCW_IC {_MCW_IC = 0x1000,};
enum MACRO__MCW_PC {_MCW_PC = 0x300,};
enum MACRO__MCW_RC {_MCW_RC = 0xC00,};
enum MACRO__MDPA {_MDPA = 0x1,_CGA = 0x2,_EGA = 0x4,_VGA = 0x8,_MCGA = 0x10,_HGC = 0x20,_OCGA = 0x42,};
enum MACRO__MODE7OFF {_MODE7OFF = 0,_MODE7ON = 1,_MODE7HI = 2,};
enum MACRO__MODEFHITOOFF {_MODEFHITOOFF = 6,};
enum MACRO__MODEFHITOON {_MODEFHITOON = 7,_MODEFHI = 8,};
enum MACRO__MODEFOFF {_MODEFOFF = 0,_MODEFOFFTOON = 1,_MODEFOFFTOHI = 2,};
enum MACRO__MODEFONTOHI {_MODEFONTOHI = 5,};
enum MACRO__MODEFONTOOFF {_MODEFONTOOFF = 3,_MODEFON = 4,};
enum MACRO__MONO {_MONO = 0x1,_COLOR = 0x2,_ENHCOLOR = 0x4,_ANALOGMONO = 0x8,_ANALOGCOLOR = 0x10,};
enum MACRO__MRES16COLOR {_MRES16COLOR = 13,};
enum MACRO__MRES256COLOR {_MRES256COLOR = 19,_ORESCOLOR = 64,_ORES256COLOR = 256,};
enum MACRO__MRESNOCOLOR {_MRESNOCOLOR = 5,};
enum MACRO__NFILE {_NFILE = 20,};
enum MACRO__NKEYBRD {_NKEYBRD_READ = 0x10,_NKEYBRD_READY = 0x11,_NKEYBRD_SHIFTSTATUS = 0x12,};
enum MACRO__NULLSEG {_NULLSEG = 0,_NULLOFF = -1,};
enum MACRO__O {_O_RDONLY = 0x0,_O_WRONLY = 0x1,_O_RDWR = 0x2,_O_APPEND = 0x8,_O_CREAT = 0x100,_O_TRUNC = 0x200,_O_EXCL = 0x400,_O_TEXT = 0x4000,_O_BINARY = 0x8000,_O_RAW = 0x8000,_O_NOINHERIT = 0x80,};
enum MACRO__OEGA {_OEGA = 0x44,};
enum MACRO__OLD {_OLD_P_OVERLAY = 2,};
enum MACRO__OVERFLOW {_OVERFLOW = 3,_UNDERFLOW = 4,};
enum MACRO__OVGA {_OVGA = 0x48,};
enum MACRO__P {_P_WAIT = 0,_P_NOWAIT = 1,};
enum MACRO__PC {_PC_24 = 0x0,_PC_53 = 0x200,_PC_64 = 0x300,};
enum MACRO__PG {_PG_PALETTELEN = 16,_PG_MAXCHARTTYPE = 5,_PG_MAXCHARTSTYLE = 2,_PG_TITLELEN = 70,_PG_LEFT = 1,_PG_CENTER = 2,_PG_RIGHT = 3,_PG_BOTTOM = 4,_PG_OVERLAY = 5,_PG_LINEARAXIS = 1,_PG_LOGAXIS = 2,_PG_DECFORMAT = 1,_PG_EXPFORMAT = 2,_PG_BARCHART = 1,_PG_COLUMNCHART = 2,_PG_PLAINBARS = 1,_PG_STACKEDBARS = 2,_PG_LINECHART = 3,_PG_SCATTERCHART = 4,_PG_POINTANDLINE = 1,_PG_POINTONLY = 2,_PG_PIECHART = 5,_PG_PERCENT = 1,_PG_NOPERCENT = 2,_PG_NOTINITIALIZED = 102,_PG_BADSCREENMODE = 103,_PG_BADCHARTSTYLE = 4,_PG_BADCHARTTYPE = 104,_PG_BADLEGENDWINDOW = 105,_PG_BADCHARTWINDOW = 7,_PG_BADDATAWINDOW = 107,_PG_NOMEMORY = 108,_PG_BADLOGBASE = 5,_PG_BADSCALEFACTOR = 6,_PG_TOOSMALLN = 109,_PG_TOOFEWSERIES = 110,};
enum MACRO__PLOSS {_PLOSS = 6,};
enum MACRO__PRINTER {_PRINTER_WRITE = 0,_PRINTER_INIT = 1,_PRINTER_STATUS = 2,};
enum MACRO__P_NOWAITO {_P_NOWAITO = 3,_P_DETACH = 4,};
enum MACRO__RC {_RC_CHOP = 0xC00,_RC_UP = 0x800,_RC_DOWN = 0x400,_RC_NEAR = 0x0,};
enum MACRO__RED {_RED = 0x2A,};
enum MACRO__S {_S_IFMT = 0xF000,_S_IFDIR = 0x4000,_S_IFCHR = 0x2000,_S_IFREG = 0x8000,_S_IREAD = 0x100,_S_IWRITE = 0x80,_S_IEXEC = 0x40,};
enum MACRO__SH {_SH_COMPAT = 0x0,_SH_DENYRW = 0x10,_SH_DENYWR = 0x20,_SH_DENYRD = 0x30,_SH_DENYNO = 0x40,};
enum MACRO__SRES16COLOR {_SRES16COLOR = 0x102,};
enum MACRO__SRES256COLOR {_SRES256COLOR = 0x103,};
enum MACRO__SVGA {_SVGA = 0x88,};
enum MACRO__SW {_SW_INVALID = 0x1,_SW_DENORMAL = 0x2,_SW_ZERODIVIDE = 0x4,_SW_OVERFLOW = 0x8,_SW_UNDERFLOW = 0x10,_SW_INEXACT = 0x20,_SW_UNEMULATED = 0x40,_SW_SQRTNEG = 0x80,_SW_STACKOVERFLOW = 0x200,_SW_STACKUNDERFLOW = 0x400,};
enum MACRO__SYS {_SYS_OPEN = 20,};
enum MACRO__TEXTBW40 {_TEXTBW40 = 0,_TEXTC40 = 1,_TEXTBW80 = 2,};
enum MACRO__TEXTC80 {_TEXTC80 = 3,_MRES4COLOR = 4,};
enum MACRO__TEXTMONO {_TEXTMONO = 7,_HERCMONO = 8,};
enum MACRO__TIME {_TIME_GETCLOCK = 0,_TIME_SETCLOCK = 1,};
enum MACRO__TLOSS {_TLOSS = 5,};
enum MACRO__UPPER {_UPPER = 0x1,_LOWER = 0x2,_DIGIT = 0x4,_SPACE = 0x8,_PUNCT = 0x10,_CONTROL = 0x20,_BLANK = 0x40,_HEX = 0x80,};
enum MACRO__VM {_VM_NULL = 0,_VM_ALLDOS = 0,_VM_EMS = 1,_VM_XMS = 2,_VM_DISK = 4,_VM_ALLSWAP = 7,_VM_CLEAN = 0,_VM_DIRTY = 1,};
enum MACRO__VRES16COLOR {_VRES16COLOR = 18,};
enum MACRO__VRES256COLOR {_VRES256COLOR = 0x101,};
enum MACRO__VRES2COLOR {_VRES2COLOR = 17,};
enum MACRO__WHITE {_WHITE = 0x2A2A,};
enum MACRO__XRES16COLOR {_XRES16COLOR = 0x104,};
enum MACRO__XRES256COLOR {_XRES256COLOR = 0x105,};
enum MACRO__YELLOW {_YELLOW = 0x3F3F,};
enum MACRO__ZRES16COLOR {_ZRES16COLOR = 0x106,};
enum MACRO__ZRES256COLOR {_ZRES256COLOR = 0x107,};
union REGS {struct WORDREGS x;struct BYTEREGS h;};
struct SREGS {unsigned int es;unsigned int cs;unsigned int ss;unsigned int ds;};
struct WORDREGS {unsigned int ax;unsigned int bx;unsigned int cx;unsigned int dx;unsigned int si;unsigned int di;unsigned int cflag;};
struct _BYTEREGS {unsigned __int8 al;unsigned __int8 ah;unsigned __int8 bl;unsigned __int8 bh;unsigned __int8 cl;unsigned __int8 ch;unsigned __int8 dl;unsigned __int8 dh;};
struct _DOSERROR {int exterror;char errclass;char action;char locus;};
typedef struct _heapinfo _HEAPINFO;
union _REGS {struct _WORDREGS x;struct _BYTEREGS h;};
struct _SREGS {unsigned int es;unsigned int cs;unsigned int ss;unsigned int ds;};
struct _WORDREGS {unsigned int ax;unsigned int bx;unsigned int cx;unsigned int dx;unsigned int si;unsigned int di;unsigned int cflag;};
typedef unsigned int __segment;
typedef struct $708EB2C8D47456B2C174260C174C4FAC _axistype;
typedef unsigned __int8 _charmap[8];
typedef struct $F8345695F188CA62739CDC0353D986D0 _chartenv;
struct _complex {double x;double y;};
struct _complexl {long double x;long double y;};
typedef int _dev_t;
struct _diskfree_t {unsigned int total_clusters;unsigned int avail_clusters;unsigned int sectors_per_cluster;unsigned int bytes_per_sector;};
struct _diskinfo_t {unsigned int drive;unsigned int head;unsigned int track;unsigned int sector;unsigned int nsectors;void far *buffer;};
struct _div_t {int quot;int rem;};
struct _dosdate_t {unsigned __int8 day;unsigned __int8 month;unsigned int year;unsigned __int8 dayofweek;};
struct _dostime_t {unsigned __int8 hour;unsigned __int8 minute;unsigned __int8 second;unsigned __int8 hsecond;};
struct _exception {int type;char *name;double arg1;double arg2;double retval;};
struct _exceptionl {int type;char *name;long double arg1;long double arg2;long double retval;};
typedef unsigned __int8 _fillmap[8];
struct _find_t {char reserved[21];char attrib;unsigned int wr_time;unsigned int wr_date;__int32 size;char name[13];};
typedef int (__cdecl __far far *_fonexit_t)();
struct _fontinfo {int type;int ascent;int pixwidth;int pixheight;int avgwidth;char filename[81];char facename[32];};
struct _heapinfo {int far *_pentry;size_t _size;int _useflag;};
typedef unsigned int _ino_t;
struct _iobuf {char *_ptr;int _cnt;char *_base;char _flag;char _file;};
struct _ldiv_t {__int32 quot;__int32 rem;};
typedef struct $95C3CB16824D66B4D3D3A1F25D6CE7B3 _legendtype;
typedef __int32 _off_t;
typedef int (__cdecl *_onexit_t)();
typedef struct $92231A9D73296187DBEF5930036406A4 _paletteentry;
typedef _paletteentry _palettetype[16];
struct _rccoord {int row;int col;};
struct _stat {_dev_t st_dev;_ino_t st_ino;unsigned int st_mode;int st_nlink;int st_uid;int st_gid;_dev_t st_rdev;_off_t st_size;time_t st_atime;time_t st_mtime;time_t st_ctime;};
typedef unsigned int _styleset[16];
struct _timeb {time_t time;unsigned int millitm;int timezone;int dstflag;};
typedef struct $5D287BBCEE976282B532DF578B48FE30 _titletype;
struct _utimbuf {time_t actime;time_t modtime;};
struct _videoconfig {int numxpixels;int numypixels;int numtextcols;int numtextrows;int numcolors;int bitsperpixel;int numvideopages;int mode;int adapter;int monitor;int memory;};
typedef unsigned __int32 _vmhnd_t;
typedef struct $49112922E8D3FA36A9D9A6626290371D _windowtype;
struct _wxycoord {double wx;double wy;};
struct _xycoord {int xcoord;int ycoord;};
typedef __int32 clock_t;
struct complex {double x;double y;};
typedef int dev_t;
typedef struct _div_t div_t;
typedef __int32 fpos_t;
typedef unsigned int ino_t;
typedef int jmp_buf[9];
struct lconv {char *decimal_point;char *thousands_sep;char *grouping;char *int_curr_symbol;char *currency_symbol;char *mon_decimal_point;char *mon_thousands_sep;char *mon_grouping;char *positive_sign;char *negative_sign;char int_frac_digits;char frac_digits;char p_cs_precedes;char p_sep_by_space;char n_cs_precedes;char n_sep_by_space;char p_sign_posn;char n_sign_posn;};
typedef struct _ldiv_t ldiv_t;
typedef __int32 off_t;
typedef int (__cdecl *onexit_t)();
typedef int ptrdiff_t;
typedef int sig_atomic_t;
typedef unsigned int size_t;
struct stat {_dev_t st_dev;_ino_t st_ino;unsigned int st_mode;int st_nlink;int st_uid;int st_gid;_dev_t st_rdev;_off_t st_size;time_t st_atime;time_t st_mtime;time_t st_ctime;};
typedef unsigned __int32 time_t;
struct timeb {time_t time;unsigned int millitm;int timezone;int dstflag;};
struct tm {int tm_sec;int tm_min;int tm_hour;int tm_mday;int tm_mon;int tm_year;int tm_wday;int tm_yday;int tm_isdst;};
struct utimbuf {time_t actime;time_t modtime;};
typedef char *va_list;
typedef unsigned int wchar_t;

MACRO_BUFSIZ BUFSIZ;
MACRO_CHAR CHAR_BIT;
MACRO_DOS_MAX CHAR_MAX;
MACRO_MIN CHAR_MIN;
MACRO_CLK CLK_TCK;
MACRO_CLOCKS CLOCKS_PER_SEC;
MACRO_DOS_CW CW_DEFAULT;
MACRO_DBL DBL_DIG;
MACRO_DBL DBL_MANT_DIG;
MACRO_DBL DBL_MAX_10_EXP;
MACRO_DBL DBL_MAX_EXP;
MACRO_DBL DBL_MIN_10_EXP;
MACRO_DBL DBL_MIN_EXP;
MACRO_DBL_RADIX DBL_RADIX;
MACRO_DBL_RADIX DBL_ROUNDS;
MACRO_DOMAIN DOMAIN;
MACRO_MODE DOS_MODE;
MACRO_ERRNO E2BIG;
MACRO_ERRNO EACCES;
MACRO_ERRNO EAGAIN;
MACRO_ERRNO EBADF;
MACRO_ERRNO EBUSY;
MACRO_ERRNO ECHILD;
MACRO_ERRNO EDEADLOCK;
MACRO_ERRNO EDOM;
MACRO_ERRNO EEXIST;
MACRO_ERRNO EFAULT;
MACRO_ERRNO EFBIG;
MACRO_ERRNO EINTR;
MACRO_ERRNO EINVAL;
MACRO_ERRNO EIO;
MACRO_ERRNO EISDIR;
MACRO_ERRNO EMFILE;
MACRO_ERRNO EMLINK;
MACRO_DOS_EM EM_DENORMAL;
MACRO_DOS_EM EM_INEXACT;
MACRO_DOS_EM EM_INVALID;
MACRO_DOS_EM EM_OVERFLOW;
MACRO_DOS_EM EM_UNDERFLOW;
MACRO_DOS_EM EM_ZERODIVIDE;
MACRO_ERRNO ENFILE;
MACRO_ERRNO ENODEV;
MACRO_ERRNO ENOENT;
MACRO_ERRNO ENOEXEC;
MACRO_ERRNO ENOMEM;
MACRO_ERRNO ENOSPC;
MACRO_ERRNO ENOTBLK;
MACRO_ERRNO ENOTDIR;
MACRO_ERRNO ENOTTY;
MACRO_ERRNO ENXIO;
MACRO_EOF EOF;
MACRO_ERRNO EPERM;
MACRO_ERRNO EPIPE;
MACRO_ERRNO ERANGE;
MACRO_ERRNO EROFS;
MACRO_ERRNO ESPIPE;
MACRO_ERRNO ESRCH;
MACRO_ERRNO ETXTBSY;
MACRO_ERRNO EUCLEAN;
MACRO_ERRNO EXDEV;
MACRO_EXIT EXIT_FAILURE;
MACRO_EXIT EXIT_SUCCESS;
MACRO_ERRNO EZERO;
MACRO_DOS_MAX FILENAME_MAX;
MACRO_FLT FLT_DIG;
MACRO_FLT FLT_GUARD;
MACRO_FLT FLT_MANT_DIG;
MACRO_FLT FLT_MAX_10_EXP;
MACRO_FLT FLT_MAX_EXP;
MACRO_FLT FLT_MIN_10_EXP;
MACRO_FLT FLT_MIN_EXP;
MACRO_FLT FLT_NORMALIZE;
MACRO_FLT FLT_RADIX;
MACRO_FLT FLT_ROUNDS;
MACRO_DOS_MAX FOPEN_MAX;
MACRO_FPE FPE_DENORMAL;
MACRO_FPE FPE_EXPLICITGEN;
MACRO_FPE FPE_INEXACT;
MACRO_FPE FPE_INVALID;
MACRO_FPE FPE_OVERFLOW;
MACRO_FPE FPE_SQRTNEG;
MACRO_FPE FPE_STACKOVERFLOW;
MACRO_FPE FPE_STACKUNDERFLOW;
MACRO_FPE FPE_UNDERFLOW;
MACRO_FPE FPE_UNEMULATED;
MACRO_FPE FPE_ZERODIVIDE;
MACRO_IC IC_AFFINE;
MACRO_IC IC_PROJECTIVE;
MACRO_DOS_MAX INT_MAX;
MACRO_MIN INT_MIN;
MACRO_DOS_LC LC_ALL;
MACRO_DOS_LC LC_COLLATE;
MACRO_DOS_LC LC_CTYPE;
MACRO_DOS_LC LC_MAX;
MACRO_DOS_LC LC_MIN;
MACRO_DOS_LC LC_MONETARY;
MACRO_DOS_LC LC_NUMERIC;
MACRO_DOS_LC LC_TIME;
MACRO_LDBL LDBL_DIG;
MACRO_LDBL LDBL_MANT_DIG;
MACRO_LDBL LDBL_MAX_10_EXP;
MACRO_LDBL LDBL_MAX_EXP;
MACRO_LDBL LDBL_MIN_10_EXP;
MACRO_LDBL LDBL_MIN_EXP;
MACRO_LDBL_RADIX LDBL_RADIX;
MACRO_LDBL_RADIX LDBL_ROUNDS;
MACRO_LK LK_LOCK;
MACRO_LK LK_NBLCK;
MACRO_LK LK_NBRLCK;
MACRO_LK LK_RLCK;
MACRO_LK LK_UNLCK;
MACRO_DOS_MAX LONG_MAX;
MACRO_MIN LONG_MIN;
MACRO_DOS_MAX MB_LEN_MAX;
MACRO_MCW MCW_EM;
MACRO_MCW MCW_IC;
MACRO_MCW_RC MCW_PC;
MACRO_MCW_RC MCW_RC;
MACRO_NSIG NSIG;
MACRO_NULL NULL;
MACRO_OLD OLD_P_OVERLAY;
MACRO_MODE OS2_MODE;
MACRO_OVERFLOW OVERFLOW;
MACRO_O O_APPEND;
MACRO_O O_BINARY;
MACRO_O O_CREAT;
MACRO_O O_EXCL;
MACRO_O O_NOINHERIT;
MACRO_O O_RDONLY;
MACRO_O O_RDWR;
MACRO_O O_TEXT;
MACRO_O O_TRUNC;
MACRO_O O_WRONLY;
MACRO_DOS_PC PC_24;
MACRO_DOS_PC PC_53;
MACRO_DOS_PC PC_64;
MACRO_PLOSS PLOSS;
MACRO_P_NOWAITO P_DETACH;
MACRO_P P_NOWAIT;
MACRO_P_NOWAITO P_NOWAITO;
MACRO_P P_WAIT;
MACRO_DOS_MAX RAND_MAX;
MACRO_DOS_RC RC_CHOP;
MACRO_DOS_RC RC_DOWN;
MACRO_DOS_RC RC_NEAR;
MACRO_DOS_RC RC_UP;
MACRO_DOS_MAX SCHAR_MAX;
MACRO_MIN SCHAR_MIN;
MACRO_SEEK SEEK_CUR;
MACRO_SEEK SEEK_END;
MACRO_SEEK SEEK_SET;
MACRO_DOS_MAX SHRT_MAX;
MACRO_MIN SHRT_MIN;
MACRO_SH SH_COMPAT;
MACRO_SH SH_DENYNO;
MACRO_SH SH_DENYRD;
MACRO_SH SH_DENYRW;
MACRO_SH SH_DENYWR;
MACRO_SIGNAL SIGABRT;
MACRO_SIGNAL SIGFPE;
MACRO_SIGNAL SIGILL;
MACRO_SIGNAL SIGINT;
MACRO_SIGNAL SIGSEGV;
MACRO_SIGNAL SIGTERM;
MACRO_DOMAIN SING;
MACRO_DOS_SW SW_DENORMAL;
MACRO_DOS_SW SW_INEXACT;
MACRO_DOS_SW SW_INVALID;
MACRO_DOS_SW SW_OVERFLOW;
MACRO_DOS_SW SW_SQRTNEG;
MACRO_DOS_SW SW_STACKOVERFLOW;
MACRO_DOS_SW SW_STACKUNDERFLOW;
MACRO_DOS_SW SW_UNDERFLOW;
MACRO_DOS_SW SW_UNEMULATED;
MACRO_DOS_SW SW_ZERODIVIDE;
MACRO_SYS SYS_OPEN;
MACRO_FILE_MODE S_IEXEC;
MACRO_FILE_MODE S_IFCHR;
MACRO_FILE_MODE S_IFDIR;
MACRO_FILE_MODE S_IFMT;
MACRO_FILE_MODE S_IFREG;
MACRO_FILE_MODE S_IREAD;
MACRO_FILE_MODE S_IWRITE;
MACRO_TLOSS TLOSS;
MACRO_DOS_MAX TMP_MAX;
MACRO_DOS_MAX UCHAR_MAX;
MACRO_DOS_MAX UINT_MAX;
MACRO_DOS_MAX ULONG_MAX;
MACRO_OVERFLOW UNDERFLOW;
MACRO_DOS_MAX USHRT_MAX;
MACRO__ANALOG _ANALOG;
MACRO__MONO _ANALOGCOLOR;
MACRO__MONO _ANALOGMONO;
MACRO__A _A_ARCH;
MACRO__A _A_HIDDEN;
MACRO__A A_NORMAL;
MACRO__A _A_RDONLY;
MACRO__A _A_SUBDIR;
MACRO__A _A_SYSTEM;
MACRO__A _A_VOLID;
MACRO__BLACK BLACK;
MACRO__UPPER _BLANK;
MACRO__BLACK BLUE;
MACRO__BRIGHTWHITE _BRIGHTWHITE;
MACRO__BROWN _BROWN;
MACRO__MDPA _CGA;
MACRO__MONO _COLOR;
MACRO__COM COM_110;
MACRO__COM _COM_1200;
MACRO__COM _COM_150;
MACRO__COM _COM_2400;
MACRO__COM _COM_300;
MACRO__COM _COM_4800;
MACRO__COM _COM_600;
MACRO__COM _COM_9600;
MACRO__COM _COM_CHR7;
MACRO__COM _COM_CHR8;
MACRO__COM _COM_EVENPARITY;
MACRO__COM COM_INIT;
MACRO__COM COM_NOPARITY;
MACRO__COM _COM_ODDPARITY;
MACRO__COM _COM_RECEIVE;
MACRO__COM _COM_SEND;
MACRO__COM _COM_STATUS;
MACRO__COM COM_STOP1;
MACRO__COM _COM_STOP2;
MACRO__UPPER _CONTROL;
MACRO__CW _CW_DEFAULT;
MACRO__CYAN _CYAN;
MACRO__DBL _DBL_RADIX;
MACRO__DBL _DBL_ROUNDS;
MACRO__DEFAULTMODE _DEFAULTMODE;
MACRO__UPPER _DIGIT;
MACRO__DISK _DISK_FORMAT;
MACRO__DISK _DISK_READ;
MACRO__DISK DISK_RESET;
MACRO__DISK _DISK_STATUS;
MACRO__DISK _DISK_VERIFY;
MACRO__DISK _DISK_WRITE;
MACRO__DOMAIN _DOMAIN;
MACRO_MODE DOS_MODE;
MACRO__MDPA _EGA;
MACRO__EM _EM_DENORMAL;
MACRO__EM _EM_INEXACT;
MACRO__EM _EM_INVALID;
MACRO__EM _EM_OVERFLOW;
MACRO__EM _EM_UNDERFLOW;
MACRO__EM _EM_ZERODIVIDE;
MACRO__MONO _ENHCOLOR;
MACRO__ERESNOCOLOR _ERESCOLOR;
MACRO__ERESNOCOLOR _ERESNOCOLOR;
MACRO__FPE _FPE_DENORMAL;
MACRO__FPE _FPE_EXPLICITGEN;
MACRO__FPE _FPE_INEXACT;
MACRO__FPE _FPE_INVALID;
MACRO__FPE _FPE_OVERFLOW;
MACRO__FPE _FPE_SQRTNEG;
MACRO__FPE _FPE_STACKOVERFLOW;
MACRO__FPE _FPE_STACKUNDERFLOW;
MACRO__FPE _FPE_UNDERFLOW;
MACRO__FPE _FPE_UNEMULATED;
MACRO__FPE _FPE_ZERODIVIDE;
MACRO__FREEENTRY FREEENTRY;
MACRO__GAND _GAND;
MACRO__GBORDER _GBORDER;
MACRO__GCLEARSCREEN GCLEARSCREEN;
MACRO__GCURSOROFF GCURSOROFF;
MACRO__GCURSOROFF _GCURSORON;
MACRO__GFILLINTERIOR _GFILLINTERIOR;
MACRO__GOR GOR;
MACRO__GPRESET _GPRESET;
MACRO__GPSET _GPSET;
MACRO__GRAY _GRAY;
MACRO__GRNOOUTPUT _GRCLIPPED;
MACRO__GRCORRUPTEDFONTFILE _GRCORRUPTEDFONTFILE;
MACRO__GREEN _GREEN;
MACRO__GROK _GRERROR;
MACRO__GRFONTFILENOTFOUND _GRFONTFILENOTFOUND;
MACRO__GRINSUFFICIENTMEMORY _GRINSUFFICIENTMEMORY;
MACRO__GRINVALIDFONTFILE _GRINVALIDFONTFILE;
MACRO__GRINVALIDIMAGEBUFFER _GRINVALIDIMAGEBUFFER;
MACRO__GRINVALIDPARAMETER _GRINVALIDPARAMETER;
MACRO__GRMODENOTSUPPORTED _GRMODENOTSUPPORTED;
MACRO__GRNOOUTPUT _GRNOOUTPUT;
MACRO__GRNOTINPROPERMODE _GRNOTINPROPERMODE;
MACRO__GROK GROK;
MACRO__GRPARAMETERALTERED _GRPARAMETERALTERED;
MACRO__GRPARAMETERALTERED _GRTEXTNOTSUPPORTED;
MACRO__GSCROLLDOWN _GSCROLLDOWN;
MACRO__GSCROLLUP _GSCROLLUP;
MACRO__GCLEARSCREEN _GVIEWPORT;
MACRO__GCLEARSCREEN _GWINDOW;
MACRO__GWRAPOFF GWRAPOFF;
MACRO__GWRAPOFF _GWRAPON;
MACRO__GOR _GXOR;
MACRO__HARDERR _HARDERR_ABORT;
MACRO__HARDERR _HARDERR_FAIL;
MACRO__HARDERR HARDERR_IGNORE;
MACRO__HARDERR _HARDERR_RETRY;
MACRO__HEAPBADBEGIN _HEAPBADBEGIN;
MACRO__HEAPBADNODE _HEAPBADNODE;
MACRO__HEAPBADPTR _HEAPBADPTR;
MACRO__HEAPEMPTY _HEAPEMPTY;
MACRO__HEAPEND _HEAPEND;
MACRO__HEAPOK _HEAPOK;
MACRO__HEAP _HEAP_MAXREQ;
MACRO__TEXTMONO _HERCMONO;
MACRO__UPPER _HEX;
MACRO__MDPA _HGC;
MACRO__HRES16COLOR _HRES16COLOR;
MACRO__HRESBW _HRESBW;
double HUGE;
MACRO__IC _IC_AFFINE;
MACRO__IC IC_PROJECTIVE;
MACRO__IONBF _IOEOF;
MACRO__IONBF _IOERR;
MACRO__IOFBF IOFBF;
MACRO__IOFBF _IOLBF;
MACRO__IONBF _IOMYBUF;
MACRO__IONBF _IONBF;
MACRO__IOREAD _IOREAD;
MACRO__IONBF _IORW;
MACRO__IONBF _IOSTRG;
MACRO__IOREAD _IOWRT;
MACRO__JBLEN _JBLEN;
MACRO__KEYBRD KEYBRD_READ;
MACRO__KEYBRD _KEYBRD_READY;
MACRO__KEYBRD _KEYBRD_SHIFTSTATUS;
MACRO__LDBL _LDBL_RADIX;
MACRO__LDBL _LDBL_ROUNDS;
MACRO__LIGHTBLUE _LIGHTBLUE;
MACRO__LIGHTCYAN _LIGHTCYAN;
MACRO__LIGHTGREEN _LIGHTGREEN;
MACRO__LIGHTMAGENTA _LIGHTMAGENTA;
MACRO__LIGHTRED _LIGHTRED;
MACRO__LIGHTYELLOW _LIGHTYELLOW;
MACRO__LK _LK_LOCK;
MACRO__LK _LK_NBLCK;
MACRO__LK _LK_NBRLCK;
MACRO__LK _LK_RLCK;
MACRO__LK LK_UNLCK;
MACRO__UPPER _LOWER;
MACRO__MAGENTA _MAGENTA;
MACRO__MAXCOLORMODE _MAXCOLORMODE;
MACRO__MAXRESMODE _MAXRESMODE;
MACRO__MAXTEXTROWS _MAXTEXTROWS;
MACRO__MAX _MAX_DIR;
MACRO__MAX _MAX_DRIVE;
MACRO__MAX _MAX_EXT;
MACRO__MAX _MAX_FNAME;
MACRO__MAX _MAX_PATH;
MACRO__MDPA _MCGA;
MACRO__MCW _MCW_EM;
MACRO__MCW_IC _MCW_IC;
MACRO__MCW_PC _MCW_PC;
MACRO__MCW_RC _MCW_RC;
MACRO__MDPA _MDPA;
MACRO__MODE7OFF _MODE7HI;
MACRO__MODE7OFF MODE7OFF;
MACRO__MODE7OFF _MODE7ON;
MACRO__MODEFHITOON _MODEFHI;
MACRO__MODEFHITOOFF _MODEFHITOOFF;
MACRO__MODEFHITOON _MODEFHITOON;
MACRO__MODEFOFF MODEFOFF;
MACRO__MODEFOFF _MODEFOFFTOHI;
MACRO__MODEFOFF _MODEFOFFTOON;
MACRO__MODEFONTOOFF _MODEFON;
MACRO__MODEFONTOHI _MODEFONTOHI;
MACRO__MODEFONTOOFF _MODEFONTOOFF;
MACRO__MONO _MONO;
MACRO__MRES16COLOR _MRES16COLOR;
MACRO__MRES256COLOR _MRES256COLOR;
MACRO__TEXTC80 _MRES4COLOR;
MACRO__MRESNOCOLOR _MRESNOCOLOR;
MACRO__NFILE _NFILE;
MACRO__NKEYBRD _NKEYBRD_READ;
MACRO__NKEYBRD _NKEYBRD_READY;
MACRO__NKEYBRD _NKEYBRD_SHIFTSTATUS;
MACRO__NULLSEG _NULLOFF;
MACRO__NULLSEG NULLSEG;
MACRO__MDPA _OCGA;
MACRO__OEGA _OEGA;
MACRO__OLD _OLD_P_OVERLAY;
MACRO__MRES256COLOR _ORES256COLOR;
MACRO__MRES256COLOR _ORESCOLOR;
MACRO_MODE _OS2_MODE;
MACRO__OVERFLOW _OVERFLOW;
MACRO__OVGA _OVGA;
MACRO__O _O_APPEND;
MACRO__O _O_BINARY;
MACRO__O _O_CREAT;
MACRO__O _O_EXCL;
MACRO__O _O_NOINHERIT;
MACRO__O _O_RAW;
MACRO__O O_RDONLY;
MACRO__O _O_RDWR;
MACRO__O _O_TEXT;
MACRO__O _O_TRUNC;
MACRO__O _O_WRONLY;
MACRO__PC PC_24;
MACRO__PC _PC_53;
MACRO__PC _PC_64;
MACRO__PG _PG_BADCHARTSTYLE;
MACRO__PG _PG_BADCHARTTYPE;
MACRO__PG _PG_BADCHARTWINDOW;
MACRO__PG _PG_BADDATAWINDOW;
MACRO__PG _PG_BADLEGENDWINDOW;
MACRO__PG _PG_BADLOGBASE;
MACRO__PG _PG_BADSCALEFACTOR;
MACRO__PG _PG_BADSCREENMODE;
MACRO__PG _PG_BARCHART;
MACRO__PG _PG_BOTTOM;
MACRO__PG _PG_CENTER;
MACRO__PG _PG_COLUMNCHART;
MACRO__PG _PG_DECFORMAT;
MACRO__PG _PG_EXPFORMAT;
MACRO__PG _PG_LEFT;
MACRO__PG _PG_LINEARAXIS;
MACRO__PG _PG_LINECHART;
MACRO__PG _PG_LOGAXIS;
MACRO__PG _PG_MAXCHARTSTYLE;
MACRO__PG _PG_MAXCHARTTYPE;
MACRO__PG _PG_NOMEMORY;
MACRO__PG _PG_NOPERCENT;
MACRO__PG _PG_NOTINITIALIZED;
MACRO__PG _PG_OVERLAY;
MACRO__PG _PG_PALETTELEN;
MACRO__PG _PG_PERCENT;
MACRO__PG _PG_PIECHART;
MACRO__PG _PG_PLAINBARS;
MACRO__PG _PG_POINTANDLINE;
MACRO__PG _PG_POINTONLY;
MACRO__PG _PG_RIGHT;
MACRO__PG _PG_SCATTERCHART;
MACRO__PG _PG_STACKEDBARS;
MACRO__PG _PG_TITLELEN;
MACRO__PG _PG_TOOFEWSERIES;
MACRO__PG _PG_TOOSMALLN;
MACRO__PLOSS _PLOSS;
MACRO__PRINTER _PRINTER_INIT;
MACRO__PRINTER _PRINTER_STATUS;
MACRO__PRINTER PRINTER_WRITE;
MACRO_MODE _PROT_MODE;
MACRO__UPPER _PUNCT;
MACRO__P_NOWAITO _P_DETACH;
MACRO__P _P_NOWAIT;
MACRO__P_NOWAITO _P_NOWAITO;
MACRO__P P_WAIT;
MACRO__RC _RC_CHOP;
MACRO__RC _RC_DOWN;
MACRO__RC RC_NEAR;
MACRO__RC _RC_UP;
MACRO_MODE REAL_MODE;
MACRO__RED _RED;
MACRO__SH SH_COMPAT;
MACRO__SH _SH_DENYNO;
MACRO__SH _SH_DENYRD;
MACRO__SH _SH_DENYRW;
MACRO__SH _SH_DENYWR;
MACRO__DOMAIN _SING;
MACRO__UPPER _SPACE;
MACRO__SRES16COLOR _SRES16COLOR;
MACRO__SRES256COLOR _SRES256COLOR;
MACRO__SVGA _SVGA;
MACRO__SW _SW_DENORMAL;
MACRO__SW _SW_INEXACT;
MACRO__SW _SW_INVALID;
MACRO__SW _SW_OVERFLOW;
MACRO__SW _SW_SQRTNEG;
MACRO__SW _SW_STACKOVERFLOW;
MACRO__SW _SW_STACKUNDERFLOW;
MACRO__SW _SW_UNDERFLOW;
MACRO__SW _SW_UNEMULATED;
MACRO__SW _SW_ZERODIVIDE;
MACRO__SYS _SYS_OPEN;
MACRO__S _S_IEXEC;
MACRO__S _S_IFCHR;
MACRO__S _S_IFDIR;
MACRO__S _S_IFMT;
MACRO__S _S_IFREG;
MACRO__S _S_IREAD;
MACRO__S _S_IWRITE;
MACRO__TEXTBW40 TEXTBW40;
MACRO__TEXTBW40 _TEXTBW80;
MACRO__TEXTBW40 _TEXTC40;
MACRO__TEXTC80 _TEXTC80;
MACRO__TEXTMONO _TEXTMONO;
MACRO__TIME TIME_GETCLOCK;
MACRO__TIME _TIME_SETCLOCK;
MACRO__TLOSS _TLOSS;
MACRO__OVERFLOW _UNDERFLOW;
MACRO__UPPER _UPPER;
MACRO__FREEENTRY _USEDENTRY;
void __pascal __far VFREE(_vmhnd_t);
MACRO__MDPA _VGA;
int __pascal __far VHEAPINIT(unsigned int, unsigned int, unsigned int);
void __pascal __far VHEAPTERM();
void far *__pascal __far VLOAD(_vmhnd_t, int);
void far *__pascal __far VLOCK(_vmhnd_t);
unsigned int __pascal __far VLOCKCNT(_vmhnd_t);
_vmhnd_t __pascal __far VMALLOC(unsigned __int32);
unsigned __int32 __pascal __far VMSIZE(_vmhnd_t);
MACRO__VM VM_ALLDOS;
MACRO__VM _VM_ALLSWAP;
MACRO__VM VM_CLEAN;
MACRO__VM _VM_DIRTY;
MACRO__VM _VM_DISK;
MACRO__VM _VM_EMS;
MACRO__VM VM_NULL;
MACRO__VM _VM_XMS;
_vmhnd_t __pascal __far VREALLOC(_vmhnd_t, unsigned __int32);
MACRO__VRES16COLOR _VRES16COLOR;
MACRO__VRES256COLOR _VRES256COLOR;
MACRO__VRES2COLOR _VRES2COLOR;
void __pascal __far VUNLOCK(_vmhnd_t, int);
MACRO__WHITE _WHITE;
MACRO_MODE _WIN_MODE;
MACRO__XRES16COLOR _XRES16COLOR;
MACRO__XRES256COLOR _XRES256COLOR;
MACRO__YELLOW _YELLOW;
MACRO__ZRES16COLOR _ZRES16COLOR;
MACRO__ZRES256COLOR _ZRES256COLOR;
double _HUGE;
long double _LHUGE;
int __cdecl __isascii(int);
int __cdecl __iscsym(int);
int __cdecl __iscsymf(int);
unsigned int __mb_cur_max;
int __cdecl __toascii(int);
int __cdecl _access(const char *, int);
void *__cdecl _alloca(size_t);
unsigned int _amblksiz;
int __cdecl __far _arc(int, int, int, int, int, int, int, int);
int __cdecl __far _arc_w(double, double, double, double, double, double, double, double);
int __cdecl __far _arc_wxy(const struct _wxycoord far *, const struct _wxycoord far *, const struct _wxycoord far *, const struct _wxycoord far *);
int __cdecl __far _arc_xy(struct _xycoord, struct _xycoord, struct _xycoord, struct _xycoord);
void __cdecl _assert(void *, void *, unsigned int);
long double __cdecl _atold(const char *);
void *__cdecl _bcalloc(__segment, size_t, size_t);
int __cdecl _bdos(int, unsigned int, unsigned int);
void *__cdecl _bexpand(__segment, void *, size_t);
void __cdecl _bfree(__segment, void *);
int __cdecl _bfreeseg(__segment);
int __cdecl _bheapadd(__segment, void *, size_t);
int __cdecl _bheapchk(__segment);
int __cdecl _bheapmin(__segment);
__segment __cdecl _bheapseg(size_t);
int __cdecl _bheapset(__segment, unsigned int);
int __cdecl _bheapwalk(__segment, _HEAPINFO *);
unsigned int __cdecl _bios_disk(unsigned int, struct _diskinfo_t *);
unsigned int __cdecl _bios_equiplist();
unsigned int __cdecl _bios_keybrd(unsigned int);
unsigned int __cdecl _bios_memsize();
unsigned int __cdecl _bios_printer(unsigned int, unsigned int, unsigned int);
unsigned int __cdecl _bios_serialcom(unsigned int, unsigned int, unsigned int);
unsigned int __cdecl _bios_timeofday(unsigned int, __int32 *);
void *__cdecl _bmalloc(__segment, size_t);
size_t __cdecl _bmsize(__segment, void *);
void *__cdecl _brealloc(__segment, void *, size_t);
void __cdecl _c_exit();
double __cdecl _cabs(struct _complex);
long double __cdecl _cabsl(struct _complexl);
void __cdecl _cexit();
char *__cdecl _cgets(char *);
void __cdecl _chain_intr(void (__cdecl __far far *)());
int __cdecl _chdir(const char *);
int __cdecl _chdrive(int);
int __cdecl _chmod(const char *, int);
int __cdecl _chsize(int, __int32);
unsigned int __cdecl _clear87();
void __cdecl __far _clearscreen(int);
int __cdecl _close(int);
int __cdecl _commit(int);
unsigned int __cdecl _control87(unsigned int, unsigned int);
int _cprintf(const char *, ...);
unsigned __int8 _cpumode;
int __cdecl _cputs(const char *);
int __cdecl _creat(const char *, int);
int _cscanf(const char *, ...);
unsigned __int8 _ctype[];
int _daylight;
int __cdecl _dieeetomsbin(double *, double *);
void __cdecl _disable();
int __cdecl __far _displaycursor(int);
int __cdecl _dmsbintoieee(double *, double *);
unsigned int __cdecl _dos_allocmem(unsigned int, unsigned int *);
unsigned int __cdecl _dos_close(int);
unsigned int __cdecl _dos_commit(int);
unsigned int __cdecl _dos_creat(const char *, unsigned int, int *);
unsigned int __cdecl _dos_creatnew(const char *, unsigned int, int *);
unsigned int __cdecl _dos_findfirst(const char *, unsigned int, struct _find_t *);
unsigned int __cdecl _dos_findnext(struct _find_t *);
unsigned int __cdecl _dos_freemem(unsigned int);
void __cdecl _dos_getdate(struct _dosdate_t *);
unsigned int __cdecl _dos_getdiskfree(unsigned int, struct _diskfree_t *);
void __cdecl _dos_getdrive(unsigned int *);
unsigned int __cdecl _dos_getfileattr(const char *, unsigned int *);
unsigned int __cdecl _dos_getftime(int, unsigned int *, unsigned int *);
void __cdecl _dos_gettime(struct _dostime_t *);
void (__cdecl __far far *__cdecl _dos_getvect(unsigned int))();
void __cdecl _dos_keep(unsigned int, unsigned int);
unsigned int __cdecl _dos_lock(int, int, unsigned __int32, unsigned __int32);
unsigned int __cdecl _dos_open(const char *, unsigned int, int *);
unsigned int __cdecl _dos_read(int, void far *, unsigned int, unsigned int *);
unsigned __int32 __cdecl _dos_seek(int, unsigned __int32, int);
unsigned int __cdecl _dos_setblock(unsigned int, unsigned int, unsigned int *);
unsigned int __cdecl _dos_setdate(struct _dosdate_t *);
void __cdecl _dos_setdrive(unsigned int, unsigned int *);
unsigned int __cdecl _dos_setfileattr(const char *, unsigned int);
unsigned int __cdecl _dos_setftime(int, unsigned int, unsigned int);
unsigned int __cdecl _dos_settime(struct _dostime_t *);
void __cdecl _dos_setvect(unsigned int, void (__cdecl __far far *)());
unsigned int __cdecl _dos_write(int, const void far *, unsigned int, unsigned int *);
int _doserrno;
int __cdecl _dosexterr(struct _DOSERROR *);
int __cdecl _dup(int);
int __cdecl _dup2(int, int);
char *__cdecl _ecvt(double, int, int *, int *);
int __cdecl __far _ellipse(int, int, int, int, int);
int __cdecl __far _ellipse_w(int, double, double, double, double);
int __cdecl __far _ellipse_wxy(int, const struct _wxycoord far *, const struct _wxycoord far *);
int __cdecl __far _ellipse_xy(int, struct _xycoord, struct _xycoord);
void __cdecl _enable();
char **_environ;
int __cdecl _eof(int);
int _execl(const char *, const char *, ...);
int _execle(const char *, const char *, ...);
int _execlp(const char *, const char *, ...);
int _execlpe(const char *, const char *, ...);
int __cdecl _execv(const char *, const char *const *);
int __cdecl _execve(const char *, const char *const *, const char *const *);
int __cdecl _execvp(const char *, const char *const *);
int __cdecl _execvpe(const char *, const char *const *, const char *const *);
void __cdecl _exit(int);
void *__cdecl _expand(void *, size_t);
int __cdecl __far _fatexit(void (__cdecl __far far *)());
void far *__cdecl _fcalloc(size_t, size_t);
int __cdecl _fcloseall();
char *__cdecl _fcvt(double, int, int *, int *);
FILE *__cdecl _fdopen(int, const char *);
void far *__cdecl _fexpand(void far *, size_t);
void __cdecl _ffree(void far *);
int __cdecl _fgetchar();
int __cdecl _fheapchk();
int __cdecl _fheapmin();
int __cdecl _fheapset(unsigned int);
int __cdecl _fheapwalk(_HEAPINFO *);
int __cdecl _fieeetomsbin(float *, float *);
int __cdecl _filbuf(FILE *);
int _fileinfo;
__int32 __cdecl _filelength(int);
int __cdecl _fileno(FILE *);
int __cdecl __far _floodfill(int, int, int);
int __cdecl __far _floodfill_w(double, double, int);
int __cdecl __far _floodfill_xy(struct _xycoord, int);
int __cdecl _flsbuf(int, FILE *);
int __cdecl _flushall();
void far *__cdecl _fmalloc(size_t);
int __cdecl __far _fmblen(const char far *, size_t);
size_t __cdecl __far _fmbstowcs(wchar_t far *, const char far *, size_t);
int __cdecl __far _fmbtowc(wchar_t far *, const char far *, size_t);
void far *__cdecl __far _fmemccpy(void far *, const void far *, int, unsigned int);
void far *__cdecl __far _fmemchr(const void far *, int, size_t);
int __cdecl __far _fmemcmp(const void far *, const void far *, size_t);
void far *__cdecl __far _fmemcpy(void far *, const void far *, size_t);
int __cdecl __far _fmemicmp(const void far *, const void far *, unsigned int);
void far *__cdecl __far _fmemmove(void far *, const void far *, size_t);
void far *__cdecl __far _fmemset(void far *, int, size_t);
int _fmode;
int __cdecl _fmsbintoieee(float *, float *);
size_t __cdecl _fmsize(void far *);
_fonexit_t __cdecl __far _fonexit(_fonexit_t);
void __cdecl _fpreset();
int __cdecl _fputchar(int);
void far *__cdecl _frealloc(void far *, size_t);
unsigned int __cdecl _freect(size_t);
FILE *__cdecl _fsopen(const char *, const char *, int);
int __cdecl _fstat(int, struct _stat *);
char far *__cdecl __far _fstrcat(char far *, const char far *);
char far *__cdecl __far _fstrchr(const char far *, int);
int __cdecl __far _fstrcmp(const char far *, const char far *);
char far *__cdecl __far _fstrcpy(char far *, const char far *);
size_t __cdecl __far _fstrcspn(const char far *, const char far *);
char far *__cdecl __far _fstrdup(const char far *);
int __cdecl __far _fstricmp(const char far *, const char far *);
size_t __cdecl __far _fstrlen(const char far *);
char far *__cdecl __far _fstrlwr(char far *);
char far *__cdecl __far _fstrncat(char far *, const char far *, size_t);
int __cdecl __far _fstrncmp(const char far *, const char far *, size_t);
char far *__cdecl __far _fstrncpy(char far *, const char far *, size_t);
int __cdecl __far _fstrnicmp(const char far *, const char far *, size_t);
char far *__cdecl __far _fstrnset(char far *, int, size_t);
char far *__cdecl __far _fstrpbrk(const char far *, const char far *);
char far *__cdecl __far _fstrrchr(const char far *, int);
char far *__cdecl __far _fstrrev(char far *);
char far *__cdecl __far _fstrset(char far *, int);
size_t __cdecl __far _fstrspn(const char far *, const char far *);
char far *__cdecl __far _fstrstr(const char far *, const char far *);
char far *__cdecl __far _fstrtok(char far *, const char far *);
char far *__cdecl __far _fstrupr(char far *);
void __cdecl _ftime(struct _timeb *);
char *__cdecl _fullpath(char *, const char *, size_t);
size_t __cdecl __far _fwcstombs(char far *, const wchar_t far *, size_t);
int __cdecl __far _fwctomb(char far *, wchar_t);
char *__cdecl _gcvt(double, int, char *);
int __cdecl __far _getactivepage();
int __cdecl __far _getarcinfo(struct _xycoord far *, struct _xycoord far *, struct _xycoord far *);
__int32 __cdecl __far _getbkcolor();
int __cdecl _getch();
int __cdecl _getche();
int __cdecl __far _getcolor();
struct _xycoord __cdecl __far _getcurrentposition();
struct _wxycoord __cdecl __far _getcurrentposition_w();
char *__cdecl _getcwd(char *, int);
char *__cdecl _getdcwd(int, char *, int);
int __cdecl _getdrive();
unsigned __int8 far *__cdecl __far _getfillmask(unsigned __int8 far *);
int __cdecl __far _getfontinfo(struct _fontinfo far *);
int __cdecl __far _getgtextextent(const char far *);
struct _xycoord __cdecl __far _getgtextvector();
void __cdecl __far _getimage(int, int, int, int, char far *);
void __cdecl __far _getimage_w(double, double, double, double, char far *);
void __cdecl __far _getimage_wxy(const struct _wxycoord far *, const struct _wxycoord far *, char far *);
void __cdecl __far _getimage_xy(struct _xycoord, struct _xycoord, char far *);
unsigned int __cdecl __far _getlinestyle();
struct _xycoord __cdecl __far _getphyscoord(int, int);
int __cdecl _getpid();
int __cdecl __far _getpixel(int, int);
int __cdecl __far _getpixel_w(double, double);
int __cdecl __far _getpixel_xy(struct _xycoord);
int __cdecl __far _gettextcolor();
int __cdecl __far _gettextcursor();
struct _rccoord __cdecl __far _gettextposition();
void __cdecl __far _gettextwindow(int far *, int far *, int far *, int far *);
struct _videoconfig far *__cdecl __far _getvideoconfig(struct _videoconfig far *);
struct _xycoord __cdecl __far _getviewcoord(int, int);
struct _xycoord __cdecl __far _getviewcoord_w(double, double);
struct _xycoord __cdecl __far _getviewcoord_wxy(const struct _wxycoord far *);
int __cdecl __far _getvisualpage();
int __cdecl _getw(FILE *);
struct _wxycoord __cdecl __far _getwindowcoord(int, int);
struct _wxycoord __cdecl __far _getwindowcoord_xy(struct _xycoord);
int __cdecl __far _getwritemode();
int __cdecl __far _grstatus();
void far *__cdecl _halloc(__int32, size_t);
void __cdecl _harderr(void (__cdecl __far far *)(unsigned int, unsigned int, unsigned int far *));
void __cdecl _hardresume(int);
void __cdecl _hardretn(int);
int __cdecl _heapadd(void far *, size_t);
int __cdecl _heapchk();
int __cdecl _heapmin();
int __cdecl _heapset(unsigned int);
int __cdecl _heapwalk(_HEAPINFO *);
void __cdecl _hfree(void far *);
double __cdecl _hypot(double, double);
long double __cdecl _hypotl(long double, long double);
__int32 __cdecl __far _imagesize(int, int, int, int);
__int32 __cdecl __far _imagesize_w(double, double, double, double);
__int32 __cdecl __far _imagesize_wxy(const struct _wxycoord far *, const struct _wxycoord far *);
__int32 __cdecl __far _imagesize_xy(struct _xycoord, struct _xycoord);
int __cdecl __far _inchar();
int __cdecl _inp(unsigned int);
unsigned int __cdecl _inpw(unsigned int);
int __cdecl _int86(int, union _REGS *, union _REGS *);
int __cdecl _int86x(int, union _REGS *, union _REGS *, struct _SREGS *);
int __cdecl _intdos(union _REGS *, union _REGS *);
int __cdecl _intdosx(union _REGS *, union _REGS *, struct _SREGS *);
FILE _iob[];
int __cdecl _isatty(int);
char *__cdecl _itoa(int, char *, int);
double __cdecl _j0(double);
long double __cdecl _j0l(long double);
double __cdecl _j1(double);
long double __cdecl _j1l(long double);
double __cdecl _jn(int, double);
long double __cdecl _jnl(int, long double);
int __cdecl _kbhit();
void *__cdecl _lfind(const void *, const void *, unsigned int *, unsigned int, int (__cdecl *)(const void *, const void *));
int __cdecl __far _lineto(int, int);
int __cdecl __far _lineto_w(double, double);
int __cdecl __far _lineto_xy(struct _xycoord);
int __cdecl _locking(int, int, __int32);
unsigned __int32 __cdecl _lrotl(unsigned __int32, int);
unsigned __int32 __cdecl _lrotr(unsigned __int32, int);
void *__cdecl _lsearch(const void *, void *, unsigned int *, unsigned int, int (__cdecl *)(const void *, const void *));
__int32 __cdecl _lseek(int, __int32, int);
char *__cdecl _ltoa(__int32, char *, int);
void __cdecl _makepath(char *, const char *, const char *, const char *, const char *);
int __cdecl _matherr(struct _exception *);
int __cdecl _matherrl(struct _exceptionl *);
size_t __cdecl _memavl();
void *__cdecl _memccpy(void *, const void *, int, unsigned int);
int __cdecl _memicmp(const void *, const void *, unsigned int);
size_t __cdecl _memmax();
int __cdecl _mkdir(const char *);
char *__cdecl _mktemp(char *);
void __cdecl _movedata(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int);
struct _xycoord __cdecl __far _moveto(int, int);
struct _wxycoord __cdecl __far _moveto_w(double, double);
struct _xycoord __cdecl __far _moveto_xy(struct _xycoord);
size_t __cdecl _msize(void *);
void near *__cdecl _ncalloc(size_t, size_t);
void near *__cdecl _nexpand(void near *, size_t);
void __cdecl _nfree(void near *);
int __cdecl _nheapchk();
int __cdecl _nheapmin();
int __cdecl _nheapset(unsigned int);
int __cdecl _nheapwalk(_HEAPINFO *);
void near *__cdecl _nmalloc(size_t);
size_t __cdecl _nmsize(void near *);
void near *__cdecl _nrealloc(void near *, size_t);
char near *__cdecl __far _nstrdup(const char far *);
_onexit_t __cdecl _onexit(_onexit_t);
int _open(const char *, int, ...);
unsigned __int8 _osmajor;
unsigned __int8 _osminor;
unsigned __int8 _osmode;
unsigned int _osver;
unsigned int _osversion;
void __cdecl __far _outgtext(const char far *);
void __cdecl __far _outmem(const char far *, int);
int __cdecl _outp(unsigned int, int);
unsigned int __cdecl _outpw(unsigned int, unsigned int);
void __cdecl __far _outtext(const char far *);
int _p_overlay;
int __cdecl __far _pg_analyzechart(_chartenv far *, const char far *const far *, const float far *, int);
int __cdecl __far _pg_analyzechartms(_chartenv far *, const char far *const far *, const float far *, int, int, int, const char far *const far *);
int __cdecl __far _pg_analyzepie(_chartenv far *, const char far *const far *, const float far *, const int far *, int);
int __cdecl __far _pg_analyzescatter(_chartenv far *, const float far *, const float far *, int);
int __cdecl __far _pg_analyzescatterms(_chartenv far *, const float far *, const float far *, int, int, int, const char far *const far *);
int __cdecl __far _pg_chart(_chartenv far *, const char far *const far *, const float far *, int);
int __cdecl __far _pg_chartms(_chartenv far *, const char far *const far *, const float far *, int, int, int, const char far *const far *);
int __cdecl __far _pg_chartpie(_chartenv far *, const char far *const far *, const float far *, const int far *, int);
int __cdecl __far _pg_chartscatter(_chartenv far *, const float far *, const float far *, int);
int __cdecl __far _pg_chartscatterms(_chartenv far *, const float far *, const float far *, int, int, int, const char far *const far *);
int __cdecl __far _pg_defaultchart(_chartenv far *, int, int);
int __cdecl __far _pg_getchardef(int, unsigned __int8 far *);
int __cdecl __far _pg_getpalette(_paletteentry far *);
void __cdecl __far _pg_getstyleset(unsigned int far *);
int __cdecl __far _pg_hlabelchart(_chartenv far *, int, int, int, const char far *);
int __cdecl __far _pg_initchart();
int __cdecl __far _pg_resetpalette();
void __cdecl __far _pg_resetstyleset();
int __cdecl __far _pg_setchardef(int, const unsigned __int8 far *);
int __cdecl __far _pg_setpalette(const _paletteentry far *);
void __cdecl __far _pg_setstyleset(const unsigned int far *);
int __cdecl __far _pg_vlabelchart(_chartenv far *, int, int, int, const char far *);
char far *_pgmptr;
int __cdecl __far _pie(int, int, int, int, int, int, int, int, int);
int __cdecl __far _pie_w(int, double, double, double, double, double, double, double, double);
int __cdecl __far _pie_wxy(int, const struct _wxycoord far *, const struct _wxycoord far *, const struct _wxycoord far *, const struct _wxycoord far *);
int __cdecl __far _pie_xy(int, struct _xycoord, struct _xycoord, struct _xycoord, struct _xycoord);
int __cdecl __far _polygon(int, const struct _xycoord far *, int);
int __cdecl __far _polygon_w(int, const double far *, int);
int __cdecl __far _polygon_wxy(int, const struct _wxycoord far *, int);
unsigned int _psp;
int __cdecl _putch(int);
int __cdecl _putenv(const char *);
void __cdecl __far _putimage(int, int, char far *, int);
void __cdecl __far _putimage_w(double, double, char far *, int);
void __cdecl __far _putimage_xy(struct _xycoord, char far *, int);
int __cdecl _putw(int, FILE *);
int __cdecl _read(int, void *, unsigned int);
int __cdecl __far _rectangle(int, int, int, int, int);
int __cdecl __far _rectangle_w(int, double, double, double, double);
int __cdecl __far _rectangle_wxy(int, const struct _wxycoord far *, const struct _wxycoord far *);
int __cdecl __far _rectangle_xy(int, struct _xycoord, struct _xycoord);
int __cdecl __far _registerfonts(const char far *);
int __cdecl __far _remapallpalette(const __int32 far *);
__int32 __cdecl __far _remappalette(int, __int32);
int __cdecl _rmdir(const char *);
int __cdecl _rmtmp();
unsigned int __cdecl _rotl(unsigned int, int);
unsigned int __cdecl _rotr(unsigned int, int);
void __cdecl __far _scrolltextwindow(int);
void __cdecl _searchenv(const char *, const char *, char *);
void __cdecl _segread(struct _SREGS *);
int __cdecl __far _selectpalette(int);
int __cdecl __far _setactivepage(int);
__int32 __cdecl __far _setbkcolor(__int32);
void __cdecl __far _setcliprgn(int, int, int, int);
int __cdecl __far _setcolor(int);
void __cdecl __far _setfillmask(const unsigned __int8 far *);
int __cdecl __far _setfont(const char far *);
struct _xycoord __cdecl __far _setgtextvector(int, int);
int __cdecl _setjmp(jmp_buf);
void __cdecl __far _setlinestyle(unsigned int);
int __cdecl _setmode(int, int);
int __cdecl __far _setpixel(int, int);
int __cdecl __far _setpixel_w(double, double);
int __cdecl __far _setpixel_xy(struct _xycoord);
int __cdecl __far _settextcolor(int);
int __cdecl __far _settextcursor(int);
struct _rccoord __cdecl __far _settextposition(int, int);
int __cdecl __far _settextrows(int);
void __cdecl __far _settextwindow(int, int, int, int);
int __cdecl __far _setvideomode(int);
int __cdecl __far _setvideomoderows(int, int);
struct _xycoord __cdecl __far _setvieworg(int, int);
void __cdecl __far _setviewport(int, int, int, int);
int __cdecl __far _setvisualpage(int);
int __cdecl __far _setwindow(int, double, double, double, double);
int __cdecl __far _setwritemode(int);
int _snprintf(char *, size_t, const char *, ...);
int _sopen(const char *, int, int, ...);
int _spawnl(int, const char *, const char *, ...);
int _spawnle(int, const char *, const char *, ...);
int _spawnlp(int, const char *, const char *, ...);
int _spawnlpe(int, const char *, const char *, ...);
int __cdecl _spawnv(int, const char *, const char *const *);
int __cdecl _spawnve(int, const char *, const char *const *, const char *const *);
int __cdecl _spawnvp(int, const char *, const char *const *);
int __cdecl _spawnvpe(int, const char *, const char *const *, const char *const *);
void __cdecl _splitpath(const char *, char *, char *, char *, char *);
size_t __cdecl _stackavail();
int __cdecl _stat(const char *, struct _stat *);
unsigned int __cdecl _status87();
int __cdecl _strcmpi(const char *, const char *);
char *__cdecl _strdate(char *);
char *__cdecl _strdup(const char *);
char *__cdecl _strerror(const char *);
int __cdecl _stricmp(const char *, const char *);
char *__cdecl _strlwr(char *);
int __cdecl _strnicmp(const char *, const char *, size_t);
char *__cdecl _strnset(char *, int, size_t);
char *__cdecl _strrev(char *);
char *__cdecl _strset(char *, int);
char *__cdecl _strtime(char *);
long double __cdecl _strtold(const char *, char **);
char *__cdecl _strupr(char *);
void __cdecl _swab(char *, char *, int);
char *_sys_errlist[];
int _sys_nerr;
__int32 __cdecl _tell(int);
char *__cdecl _tempnam(char *, char *);
__int32 _timezone;
int __cdecl _tolower(int);
int __cdecl _toupper(int);
char *_tzname[2];
void __cdecl _tzset();
char *__cdecl _ultoa(unsigned __int32, char *, int);
int __cdecl _umask(int);
int __cdecl _ungetch(int);
int __cdecl _unlink(const char *);
void __cdecl __far _unregisterfonts();
int __cdecl _utime(const char *, struct _utimbuf *);
int __cdecl _vsnprintf(char *, size_t, const char *, va_list);
unsigned __int8 _winmajor;
unsigned __int8 _winminor;
unsigned int _winver;
int __cdecl __far _wrapon(int);
int __cdecl _write(int, const void *, unsigned int);
double __cdecl _y0(double);
long double __cdecl _y0l(long double);
double __cdecl _y1(double);
long double __cdecl _y1l(long double);
double __cdecl _yn(int, double);
long double __cdecl _ynl(int, long double);
void __cdecl abort();
int __cdecl abs(int);
int __cdecl access(const char *, int);
double __cdecl acos(double);
long double __cdecl acosl(long double);
void *__cdecl alloca(size_t);
char *__cdecl asctime(const struct tm *);
double __cdecl asin(double);
long double __cdecl asinl(long double);
double __cdecl atan(double);
double __cdecl atan2(double, double);
long double __cdecl atan2l(long double, long double);
long double __cdecl atanl(long double);
int __cdecl atexit(void (__cdecl *)());
double __cdecl atof(const char *);
int __cdecl atoi(const char *);
__int32 __cdecl atol(const char *);
int __cdecl bdos(int, unsigned int, unsigned int);
void *__cdecl bsearch(const void *, const void *, size_t, size_t, int (__cdecl *)(const void *, const void *));
double __cdecl cabs(struct complex);
long double __cdecl cabsl(struct _complexl);
void *__cdecl calloc(size_t, size_t);
double __cdecl ceil(double);
long double __cdecl ceill(long double);
char *__cdecl cgets(char *);
int __cdecl chdir(const char *);
int __cdecl chmod(const char *, int);
int __cdecl chsize(int, __int32);
void __cdecl clearerr(FILE *);
clock_t __cdecl clock();
int __cdecl close(int);
double __cdecl cos(double);
double __cdecl cosh(double);
long double __cdecl coshl(long double);
long double __cdecl cosl(long double);
int cprintf(const char *, ...);
int __cdecl cputs(const char *);
int __cdecl creat(const char *, int);
int cscanf(const char *, ...);
char *__cdecl ctime(const time_t *);
int daylight;
int __cdecl dieeetomsbin(double *, double *);
double __cdecl difftime(time_t, time_t);
div_t __cdecl div(int, int);
int __cdecl dmsbintoieee(double *, double *);
int __cdecl dosexterr(struct DOSERROR *);
int __cdecl dup(int);
int __cdecl dup2(int, int);
char *__cdecl ecvt(double, int, int *, int *);
char **environ;
int __cdecl eof(int);
volatile int errno;
int execl(const char *, const char *, ...);
int execle(const char *, const char *, ...);
int execlp(const char *, const char *, ...);
int execlpe(const char *, const char *, ...);
int __cdecl execv(const char *, const char *const *);
int __cdecl execve(const char *, const char *const *, const char *const *);
int __cdecl execvp(const char *, const char *const *);
int __cdecl execvpe(const char *, const char *const *, const char *const *);
void __cdecl exit(int);
double __cdecl exp(double);
long double __cdecl expl(long double);
double __cdecl fabs(double);
long double __cdecl fabsl(long double);
int __cdecl fclose(FILE *);
int __cdecl fcloseall();
char *__cdecl fcvt(double, int, int *, int *);
FILE *__cdecl fdopen(int, const char *);
int __cdecl feof(FILE *);
int __cdecl ferror(FILE *);
int __cdecl fflush(FILE *);
int __cdecl fgetc(FILE *);
int __cdecl fgetchar();
int __cdecl fgetpos(FILE *, fpos_t *);
char *__cdecl fgets(char *, int, FILE *);
int __cdecl fieeetomsbin(float *, float *);
__int32 __cdecl filelength(int);
int __cdecl fileno(FILE *);
double __cdecl floor(double);
long double __cdecl floorl(long double);
int __cdecl flushall();
double __cdecl fmod(double, double);
long double __cdecl fmodl(long double, long double);
int __cdecl fmsbintoieee(float *, float *);
FILE *__cdecl fopen(const char *, const char *);
int fprintf(FILE *, const char *, ...);
int __cdecl fputc(int, FILE *);
int __cdecl fputchar(int);
int __cdecl fputs(const char *, FILE *);
size_t __cdecl fread(void *, size_t, size_t, FILE *);
void __cdecl free(void *);
FILE *__cdecl freopen(const char *, const char *, FILE *);
double __cdecl frexp(double, int *);
long double __cdecl frexpl(long double, int *);
int fscanf(FILE *, const char *, ...);
int __cdecl fseek(FILE *, __int32, int);
int __cdecl fsetpos(FILE *, const fpos_t *);
int __cdecl fstat(int, struct stat *);
__int32 __cdecl ftell(FILE *);
void __cdecl ftime(struct timeb *);
size_t __cdecl fwrite(const void *, size_t, size_t, FILE *);
char *__cdecl gcvt(double, int, char *);
int __cdecl getc(FILE *);
int __cdecl getch();
int __cdecl getchar();
int __cdecl getche();
char *__cdecl getcwd(char *, int);
char *__cdecl getenv(const char *);
int __cdecl getpid();
char *__cdecl gets(char *);
int __cdecl getw(FILE *);
struct tm *__cdecl gmtime(const time_t *);
void far *__cdecl halloc(__int32, size_t);
void __cdecl hfree(void far *);
double __cdecl hypot(double, double);
long double __cdecl hypotl(long double, long double);
int __cdecl inp(unsigned int);
unsigned int __cdecl inpw(unsigned int);
int __cdecl int86(int, union REGS *, union REGS *);
int __cdecl int86x(int, union REGS *, union REGS *, struct SREGS *);
int __cdecl intdos(union REGS *, union REGS *);
int __cdecl intdosx(union REGS *, union REGS *, struct SREGS *);
int __cdecl isalnum(int);
int __cdecl isalpha(int);
int __cdecl isatty(int);
int __cdecl iscntrl(int);
int __cdecl isdigit(int);
int __cdecl isgraph(int);
int __cdecl islower(int);
int __cdecl isprint(int);
int __cdecl ispunct(int);
int __cdecl isspace(int);
int __cdecl isupper(int);
int __cdecl isxdigit(int);
char *__cdecl itoa(int, char *, int);
double __cdecl j0(double);
double __cdecl j1(double);
double __cdecl jn(int, double);
int __cdecl kbhit();
__int32 __cdecl labs(__int32);
double __cdecl ldexp(double, int);
long double __cdecl ldexpl(long double, int);
ldiv_t __cdecl ldiv(__int32, __int32);
void *__cdecl lfind(const void *, const void *, unsigned int *, unsigned int, int (__cdecl *)(const void *, const void *));
struct lconv *__cdecl localeconv();
struct tm *__cdecl localtime(const time_t *);
int __cdecl locking(int, int, __int32);
double __cdecl log(double);
double __cdecl log10(double);
long double __cdecl log10l(long double);
long double __cdecl logl(long double);
void __cdecl longjmp(jmp_buf, int);
void *__cdecl lsearch(const void *, void *, unsigned int *, unsigned int, int (__cdecl *)(const void *, const void *));
__int32 __cdecl lseek(int, __int32, int);
char *__cdecl ltoa(__int32, char *, int);
void *__cdecl malloc(size_t);
int __cdecl mblen(const char *, size_t);
size_t __cdecl mbstowcs(wchar_t *, const char *, size_t);
int __cdecl mbtowc(wchar_t *, const char *, size_t);
void *__cdecl memccpy(void *, const void *, int, unsigned int);
void *__cdecl memchr(const void *, int, size_t);
int __cdecl memcmp(const void *, const void *, size_t);
void *__cdecl memcpy(void *, const void *, size_t);
int __cdecl memicmp(const void *, const void *, unsigned int);
void *__cdecl memmove(void *, const void *, size_t);
void *__cdecl memset(void *, int, size_t);
int __cdecl mkdir(const char *);
char *__cdecl mktemp(char *);
time_t __cdecl mktime(struct tm *);
double __cdecl modf(double, double *);
long double __cdecl modfl(long double, long double *);
void __cdecl movedata(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int);
onexit_t __cdecl onexit(onexit_t);
int open(const char *, int, ...);
int __cdecl outp(unsigned int, int);
unsigned int __cdecl outpw(unsigned int, unsigned int);
void __cdecl perror(const char *);
double __cdecl pow(double, double);
long double __cdecl powl(long double, long double);
int printf(const char *, ...);
int __cdecl putc(int, FILE *);
int __cdecl putch(int);
int __cdecl putchar(int);
int __cdecl putenv(const char *);
int __cdecl puts(const char *);
int __cdecl putw(int, FILE *);
void __cdecl qsort(void *, size_t, size_t, int (__cdecl *)(const void *, const void *));
int __cdecl raise(int);
int __cdecl rand();
int __cdecl read(int, void *, unsigned int);
void *__cdecl realloc(void *, size_t);
int __cdecl remove(const char *);
int __cdecl rename(const char *, const char *);
void __cdecl rewind(FILE *);
int __cdecl rmdir(const char *);
int __cdecl rmtmp();
int scanf(const char *, ...);
void __cdecl segread(struct SREGS *);
void __cdecl setbuf(FILE *, char *);
char *__cdecl setlocale(int, const char *);
int __cdecl setmode(int, int);
int __cdecl setvbuf(FILE *, char *, int, size_t);
void (__cdecl *__cdecl signal(int, void (__cdecl *)(int)))(int);
double __cdecl sin(double);
double __cdecl sinh(double);
long double __cdecl sinhl(long double);
long double __cdecl sinl(long double);
int sopen(const char *, int, int, ...);
int spawnl(int, const char *, const char *, ...);
int spawnle(int, const char *, const char *, ...);
int spawnlp(int, const char *, const char *, ...);
int spawnlpe(int, const char *, const char *, ...);
int __cdecl spawnv(int, const char *, const char *const *);
int __cdecl spawnve(int, const char *, const char *const *, const char *const *);
int __cdecl spawnvp(int, const char *, const char *const *);
int __cdecl spawnvpe(int, const char *, const char *const *, const char *const *);
int sprintf(char *, const char *, ...);
double __cdecl sqrt(double);
long double __cdecl sqrtl(long double);
void __cdecl srand(unsigned int);
int sscanf(const char *, const char *, ...);
size_t __cdecl stackavail();
int __cdecl stat(const char *, struct stat *);
char *__cdecl strcat(char *, const char *);
char *__cdecl strchr(const char *, int);
int __cdecl strcmp(const char *, const char *);
int __cdecl strcmpi(const char *, const char *);
int __cdecl strcoll(const char *, const char *);
char *__cdecl strcpy(char *, const char *);
size_t __cdecl strcspn(const char *, const char *);
char *__cdecl strdup(const char *);
char *__cdecl strerror(int);
size_t __cdecl strftime(char *, size_t, const char *, const struct tm *);
int __cdecl stricmp(const char *, const char *);
size_t __cdecl strlen(const char *);
char *__cdecl strlwr(char *);
char *__cdecl strncat(char *, const char *, size_t);
int __cdecl strncmp(const char *, const char *, size_t);
char *__cdecl strncpy(char *, const char *, size_t);
int __cdecl strnicmp(const char *, const char *, size_t);
char *__cdecl strnset(char *, int, size_t);
char *__cdecl strpbrk(const char *, const char *);
char *__cdecl strrchr(const char *, int);
char *__cdecl strrev(char *);
char *__cdecl strset(char *, int);
size_t __cdecl strspn(const char *, const char *);
char *__cdecl strstr(const char *, const char *);
double __cdecl strtod(const char *, char **);
char *__cdecl strtok(char *, const char *);
__int32 __cdecl strtol(const char *, char **, int);
unsigned __int32 __cdecl strtoul(const char *, char **, int);
char *__cdecl strupr(char *);
size_t __cdecl strxfrm(char *, const char *, size_t);
void __cdecl swab(char *, char *, int);
char *sys_errlist[];
int sys_nerr;
int __cdecl system(const char *);
double __cdecl tan(double);
double __cdecl tanh(double);
long double __cdecl tanhl(long double);
long double __cdecl tanl(long double);
__int32 __cdecl tell(int);
char *__cdecl tempnam(char *, char *);
time_t __cdecl time(time_t *);
__int32 timezone;
FILE *__cdecl tmpfile();
char *__cdecl tmpnam(char *);
int __cdecl tolower(int);
int __cdecl toupper(int);
char *tzname[2];
void __cdecl tzset();
char *__cdecl ultoa(unsigned __int32, char *, int);
int __cdecl umask(int);
int __cdecl ungetc(int, FILE *);
int __cdecl ungetch(int);
int __cdecl unlink(const char *);
int __cdecl utime(const char *, struct utimbuf *);
int __cdecl vfprintf(FILE *, const char *, va_list);
int __cdecl vprintf(const char *, va_list);
int __cdecl vsprintf(char *, const char *, va_list);
size_t __cdecl wcstombs(char *, const wchar_t *, size_t);
int __cdecl wctomb(char *, wchar_t);
int __cdecl write(int, const void *, unsigned int);
double __cdecl y0(double);
double __cdecl y1(double);
double __cdecl yn(int, double);
